import {boundedBytes,reportFiles,reportRows} from '../../../src/artifact-report.js';
import {readBoundedJSON} from '../../../src/ai.js';
import {digest} from '../../../src/value.js';
export class ConnectorError extends Error {constructor(code){super(code.replaceAll('_',' '));this.code=code;}}
const fail=code=>{throw new ConnectorError(code);},e=encodeURIComponent;
const text=v=>typeof v==='string'?v:'';
const id=value=>{const s=String(value??'');if(!/^[A-Za-z0-9_-]{1,150}$/.test(s))fail('invalid_external_identity');return s;};
// GitHub accepts a numeric workflow ID or its YAML filename; paths stay forbidden.
const workflowKey=value=>{const s=String(value??'');if(!/^(?:[0-9]{1,150}|[A-Za-z0-9_-][A-Za-z0-9_.-]{0,144}\.ya?ml)$/.test(s))fail('invalid_external_identity');return s;};
function htmlText(input){return text(input).replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<\/(p|div|h[1-6]|tr|li)>/gi,'\n').replace(/<\/?(td|th)\b[^>]*>/gi,'\t').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,'&').trim();}
export function relayGenerated(input){return /product-relay-origin[:=]|"format"\s*:\s*"product-relay(?:-reading-pack)?"/i.test(text(input));}
export function connectorCatalog(config){return Object.entries(config.providers??{}).map(([provider,c])=>({provider,label:c.label??provider,repositories:c.repositories??[],pageIds:c.pageIds??[],fileIds:c.fileIds??[],runIds:c.runIds??[],writeComments:c.writeComments===true,workItemIds:c.workItemIds??[],taskIds:c.taskIds??[],docIds:c.docIds??[],workflows:(c.workflows??[]).map(w=>({id:w.id,refs:w.refs,inputs:w.inputs,repository:w.repository,testOnly:w.testOnly===true}))}));}
export function createConnectorService({config,secrets=()=>'',fetchImpl=fetch,XMLParser=globalThis.DOMParser,beforeWrite=async()=>{}}){
 async function request(url,headers={},options={}){
  let response;try{response=await fetchImpl(url,{...options,headers:{Accept:'application/json',...headers,...options.headers},redirect:'error',signal:AbortSignal.timeout(8000)});}catch{fail(options.method&&options.method!=='GET'?'external_write_uncertain':'connector_timeout');}
  if(options.method&&options.method!=='GET'&&response.status>=500)fail('external_write_uncertain');
  if(response.status===403&&(response.headers.get('x-ratelimit-remaining')==='0'||response.headers.get('retry-after')))fail('connector_rate_limited');
  if(response.status===403){let body;try{body=await readBoundedJSON(response.clone(),20000);}catch{}if(/rate.?limit|quota.?exceeded|dailyLimitExceeded|secondary.?rate|abuse.?detection/i.test(JSON.stringify(body??{})))fail('connector_rate_limited');}
  if(response.status===401)fail('connector_auth_unavailable');if(response.status===403)fail('connector_access_lost');if(response.status===404)fail('external_missing_or_inaccessible');if(response.status===410)fail('external_expired');if(response.status===429||response.status===503)fail('connector_rate_limited');if(!response.ok)fail('connector_provider_error');
  if(response.status===204)return null;
  if(options.responseText){const reader=response.body?.getReader();if(!reader)fail('connector_empty');let size=0,body='',decoder=new TextDecoder();try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>200000){await reader.cancel();fail('connector_content_limit');}body+=decoder.decode(value,{stream:true});}body+=decoder.decode();}finally{reader.releaseLock();}return body;}
  try{return await readBoundedJSON(response,2000000);}catch(error){if(options.method&&options.method!=='GET')fail('external_write_uncertain');throw error;}
 }
 function settings(provider){const c=config.providers?.[provider];if(!c)fail('connector_not_configured');return c;}
 function credential(c){const token=secrets(c.credentialEnv);if(!token&&!c.publicOnly)fail('connector_not_configured');return token;}
 function allowed(list,value){if(!Array.isArray(list)||!list.map(String).includes(String(value)))fail('external_scope_denied');}
 async function github(locator){
  const c=settings('github');allowed(c.repositories,locator.repository);if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(locator.repository))fail('invalid_external_identity');
  const root='https://api.github.com/repos/'+locator.repository,token=credential(c),headers={'X-GitHub-Api-Version':c.apiVersion??'2026-03-10',...(token?{Authorization:'Bearer '+token}:{})},n=locator.type==='dispatch'?workflowKey(locator.id):id(locator.id);
  if(locator.type==='artifact'){
   const a=await request(root+'/actions/artifacts/'+n,headers);if(a.expired||a.size_in_bytes>10000000)fail('artifact_expired_or_too_large');const run=await request(root+'/actions/runs/'+id(a.workflow_run?.id),headers);
   const initial=await fetchImpl(root+'/actions/artifacts/'+n+'/zip',{headers,redirect:'manual',signal:AbortSignal.timeout(8000)});let response=initial;if(initial.status===302){const redirect=new URL(initial.headers.get('location'));if(redirect.protocol!=='https:'||redirect.username||redirect.password||!/(?:^|\.)(blob\.core\.windows\.net|githubusercontent\.com|actions\.githubusercontent\.com)$/.test(redirect.hostname))fail('artifact_redirect_denied');response=await fetchImpl(redirect,{redirect:'error',signal:AbortSignal.timeout(15000)});}if(!response.ok)fail('artifact_download_failed');const bytes=await boundedBytes(response,10000000),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');if(a.digest&&a.digest!=='sha256:'+hash)fail('artifact_digest_mismatch');const files=await reportFiles(bytes),results=[];for(const file of files)for(const r of reportRows(file.text,file.name,XMLParser))results.push({...r,externalCaseId:file.name+':'+results.length,reportFile:file.name});if(results.length>5000)fail('artifact_result_limit');return {provider:'github',type:'artifact',externalId:String(a.id),title:a.name,url:run.html_url,revision:a.updated_at??a.created_at,build:run.head_sha,executedAt:run.run_started_at,status:'actual-artifact-results',description:'Downloaded actual report artifact; case mapping, qualifiers and measurement review required.',artifactHash:hash,reportFiles:files.map(f=>f.name),caseResults:results,warnings:['Report names do not establish requirement coverage. Explicitly map approved case revisions.']};
  }
  if(locator.type==='dispatch'){const rows=await request(root+'/actions/workflows/'+n+'/runs?event=workflow_dispatch&per_page=100',headers),matches=(rows.workflow_runs??[]).filter(r=>text(r.display_title).includes(id(locator.commandId)));return {provider:'github',type:'dispatch-correlation',externalId:n,title:'Workflow dispatch correlation',url:'https://github.com/'+locator.repository+'/actions',revision:await digest(matches.map(r=>({id:r.id,status:r.status,conclusion:r.conclusion}))),status:matches.length===1?'matched':'unknown',description:matches.length===1?'One actual run matched the reviewed command marker. Fetch that exact run to inspect build/artifact metadata.':'No unique run matched this command. Do not redispatch until the earlier request is reconciled.',matchedRunIds:matches.map(r=>String(r.id)),caseResults:[],warnings:rows.total_count>100?['Only the latest 100 workflow runs were examined.']:[]};}
  if(locator.type==='deployment'){const r=await request(root+'/deployments/'+n,headers),statuses=await request(root+'/deployments/'+n+'/statuses?per_page=100',headers),latest=statuses[0];return {provider:'github',type:'deployment',externalId:String(r.id),title:'Deployment '+n+' · '+r.environment,url:'https://github.com/'+locator.repository+'/deployments',revision:String(latest?.id??r.created_at),status:latest?.state??'unknown',build:r.sha,environment:r.environment,description:JSON.stringify({environment:r.environment,sha:r.sha,ref:r.ref,manifest:r.payload,latestStatus:latest?.state??'unknown'}),observedAt:latest?.created_at??r.created_at,caseResults:[],warnings:['Provider deployment status is an observation; application health still needs its own checks.']};}
  if(locator.type==='run'){
   const r=await request(root+'/actions/runs/'+n,headers),artifacts=[];let truncated=false;
   for(let page=1;page<=5;page++){const a=await request(root+'/actions/runs/'+n+'/artifacts?per_page=100&page='+page,headers);artifacts.push(...a.artifacts??[]);if((a.artifacts?.length??0)<100)break;if(page===5)truncated=true;}
   return {provider:'github',type:'run',externalId:String(r.id),title:r.name??'Workflow run',url:r.html_url,revision:String(r.updated_at)+':'+r.run_attempt,status:r.status,description:`Workflow ${r.workflow_id}; conclusion ${r.conclusion??'unknown'}; build ${r.head_sha}. A workflow conclusion does not establish mapped case coverage.`,build:r.head_sha,executedAt:r.run_started_at,artifactMetadata:artifacts.map(a=>({id:String(a.id),name:a.name,size:a.size_in_bytes,expired:a.expired,expiresAt:a.expires_at,digest:a.digest??null})),warnings:truncated?['Artifact listing reached 500 entries; additional artifacts remain unknown.']:[],caseResults:[]};
  }
  if(!['issue','pull'].includes(locator.type))fail('unsupported_reference_type');const r=await request(root+(locator.type==='pull'?'/pulls/':'/issues/')+n,headers);
  if(locator.type==='issue'&&r.pull_request)fail('reference_is_pull_request');
  return {provider:'github',type:locator.type,externalId:String(r.id),title:r.title,url:r.html_url,revision:r.updated_at+':'+(r.head?.sha??''),status:r.merged_at?'merged':r.state,description:r.body??'',build:r.head?.sha??'',owner:r.assignee?.login??'',warnings:[],caseResults:[]};
 }
 async function confluence(locator){const c=settings('confluence');allowed(c.pageIds,locator.id);if(!/^https:\/\/[A-Za-z0-9-]+\.atlassian\.net$/.test(c.origin))fail('invalid_connector_origin');const headers={Authorization:c.oauth?'Bearer '+credential(c):'Basic '+btoa(c.email+':'+credential(c))};const api=c.oauth?'https://api.atlassian.com/ex/confluence/'+id(c.cloudId):c.origin;const r=await request(api+'/wiki/api/v2/pages/'+id(locator.id)+'?body-format=storage',headers);const raw=r.body?.storage?.value??'';if(relayGenerated(raw))fail('generated_feedback_loop');return {provider:'confluence',type:'page',externalId:String(r.id),title:r.title,url:c.origin+'/wiki'+(r._links?.webui??''),revision:String(r.version?.number),status:r.status,description:htmlText(raw),warnings:['Storage-format macros, attachments and original table layout require source review.'],caseResults:[]};}
 async function drive(locator){const c=settings('drive');allowed(c.fileIds,locator.id);const headers={Authorization:'Bearer '+credential(c)},root='https://www.googleapis.com/drive/v3/files/'+id(locator.id),r=await request(root+'?fields=id,name,mimeType,version,modifiedTime,trashed,webViewLink',headers);if(r.trashed)fail('external_deleted_confirmed');let mime,path;
  if(r.mimeType==='application/vnd.google-apps.document'){mime='text/plain';path='/export?mimeType='+e(mime);}else if(r.mimeType==='application/vnd.google-apps.spreadsheet'){mime='text/csv';path='/export?mimeType='+e(mime);}else if(['text/plain','text/markdown','text/csv'].includes(r.mimeType))path='?alt=media';else fail('external_format_needs_file_import');
  const raw=await request(root+path,headers,{responseText:true}),after=await request(root+'?fields=version,modifiedTime',headers);if(after.version!==r.version||after.modifiedTime!==r.modifiedTime)fail('external_revision_changed');if(relayGenerated(raw))fail('generated_feedback_loop');return {provider:'drive',type:'file',externalId:r.id,title:r.name,url:r.webViewLink??'https://drive.google.com/file/d/'+r.id,revision:String(r.version)+':'+r.modifiedTime,status:'available',description:raw,warnings:r.mimeType.includes('spreadsheet')?['CSV export covers the provider-selected sheet, not every tab or formula. Review the table.']:[],caseResults:[]};}
 async function azure(locator){const c=settings('azure');if(!/^[A-Za-z0-9-]+$/.test(c.organization))fail('invalid_connector_origin');const root='https://dev.azure.com/'+e(c.organization)+'/'+e(c.project),headers={Authorization:c.oauth?'Bearer '+credential(c):'Basic '+btoa(':'+credential(c))},n=id(locator.id);
  if(locator.type==='run'){allowed(c.runIds,n);const r=await request(root+'/_apis/test/runs/'+n+'?api-version=7.1',headers),results=[];let truncated=false;
   for(let page=0;page<5;page++){const rows=await request(root+'/_apis/test/runs/'+n+'/results?$top=100&$skip='+(page*100)+'&api-version=7.1',headers);results.push(...rows.value??[]);if((rows.value?.length??0)<100)break;if(page===4)truncated=true;}
   return {provider:'azure',type:'run',externalId:String(r.id),title:r.name,url:r.webAccessUrl??r.url,revision:r.lastUpdatedDate??r.completedDate??r.startedDate,status:r.state,build:String(r.build?.id??''),description:'Actual Azure test-run metadata; explicit case mapping and scope review required.',executedAt:r.completedDate,caseResults:results.map(x=>({externalCaseId:String(x.testCase?.id??x.id),title:x.testCaseTitle??x.automatedTestName??'Unmapped case',result:({Passed:'pass',Failed:'fail',Blocked:'blocked',NotExecuted:'not-run'})[x.outcome]??'inconclusive',note:text(x.errorMessage)})),warnings:truncated?['More than 500 results; this bounded import is partial.']:[]};
  }
  allowed(c.workItemIds,n);const r=await request(root+'/_apis/wit/workitems/'+n+'?api-version=7.1',headers);return {provider:'azure',type:'work-item',externalId:String(r.id),title:r.fields?.['System.Title']??'Work item',url:r._links?.html?.href??r.url,revision:String(r.rev),status:r.fields?.['System.State']??'unknown',description:htmlText(r.fields?.['System.Description']??''),owner:r.fields?.['System.AssignedTo']?.displayName??'',warnings:[],caseResults:[]};}
 async function clickup(locator){const c=settings('clickup'),headers={Authorization:credential(c)},n=id(locator.id);
  if(locator.type==='doc'){
   allowed(c.docIds,n);const root='https://api.clickup.com/api/v3/workspaces/'+id(c.workspaceId)+'/docs/'+n,r=await request(root,headers),response=await request(root+'/pages?max_page_depth=-1&content_format=text%2Fplain',headers);
   const roots=Array.isArray(response)?response:response?.pages;if(!Array.isArray(roots))fail('connector_schema_changed');
   const pages=[],seen=new Set();let length=0;
   function append(items,depth){if(depth>12)fail('connector_content_limit');for(const p of items){if(!p||typeof p.id!=='string'||typeof p.name!=='string'||typeof p.content!=='string'||seen.has(p.id))fail('connector_schema_changed');if(p.deleted||p.archived)continue;seen.add(p.id);const body='ClickUp page '+p.id+' · '+p.name+'\n'+p.content;length+=body.length+2;if(length>200000||pages.length>=50)fail('connector_content_limit');pages.push({id:p.id,title:p.name,content:body,providerUpdatedAt:String(p.date_updated??p.date_edited??'unknown')});if(p.pages!==undefined){if(!Array.isArray(p.pages))fail('connector_schema_changed');append(p.pages,depth+1);}}}
   append(roots,0);if(!pages.length)fail('connector_empty');const latest=await request(root,headers);if(String(r.date_updated??r.updated_at??'')!==String(latest.date_updated??latest.updated_at??''))fail('external_revision_changed');
   return {provider:'clickup',type:'doc',externalId:n,title:r.name??'ClickUp doc',url:'https://app.clickup.com/'+c.workspaceId+'/v/dc/'+n,revision:await digest({title:r.name??'ClickUp doc',pages}),providerRevision:String(r.date_updated??r.updated_at??'unknown'),status:'available',description:pages.map(p=>p.content).join('\n\n'),pageMetadata:pages.map(({content,...p})=>p),warnings:['Plain-text page extraction: formatting, inline elements, embedded views and attachments may be absent. Page IDs identify returned text, not original screen coordinates.','The provider does not supply an atomic multi-page snapshot. Review the retrieved page revisions before approving.'],caseResults:[]};
  }
  allowed(c.taskIds,n);const r=await request('https://api.clickup.com/api/v2/task/'+n,headers);return {provider:'clickup',type:'task',externalId:String(r.id),title:r.name,url:r.url,revision:String(r.date_updated),status:r.status?.status??'unknown',description:r.description??r.text_content??'',owner:r.assignees?.map(a=>a.username).join(', ')??'',warnings:[],caseResults:[]};}
 async function read(locator){if(!locator||typeof locator.provider!=='string')fail('invalid_connector_input');const fn={github,confluence,drive,azure,clickup}[locator.provider];if(!fn)fail('connector_not_configured');const result=await fn(locator);if(typeof result.description!=='string'||result.description.length>200000||!result.title||!result.revision)fail('connector_content_limit');if(relayGenerated(result.description))fail('generated_feedback_loop');return {...result,locator:structuredClone(locator),origin:'provider-retrieved',retrievedAt:new Date().toISOString(),contentHash:await digest({title:result.title,description:result.description,status:result.status,revision:result.revision})};}
 async function writeComment({locator,expectedRevision,body,commandId,projectId}){
  if(locator.provider!=='github'||!['issue','pull'].includes(locator.type))fail('write_adapter_not_configured');const c=settings('github');if(c.writeComments!==true||!body?.trim()||body.length>20000)fail('write_adapter_not_configured');const current=await read(locator);if(current.revision!==expectedRevision)fail('external_revision_changed');
  const root='https://api.github.com/repos/'+locator.repository,headers={Authorization:'Bearer '+credential(c),'X-GitHub-Api-Version':c.apiVersion??'2026-03-10','Content-Type':'application/json'},marker='<!-- product-relay-origin:'+projectId+':'+commandId+' -->';
  await beforeWrite();const result=await request(root+'/issues/'+id(locator.id)+'/comments',headers,{method:'POST',body:JSON.stringify({body:body+'\n\n'+marker})});if(!result||!Number.isSafeInteger(result.id)||result.id<1||typeof result.html_url!=='string'||!result.html_url.startsWith('https://github.com/'+locator.repository+'/'))fail('external_write_uncertain');return {id:String(result.id),url:result.html_url,origin:'relay-generated',marker};
 }
 async function dispatch({repository,workflowId,ref,expectedSha,inputs={},commandId}){
  const c=settings('github'),w=c.workflows?.find(w=>String(w.id)===String(workflowId)&&w.repository===repository&&w.testOnly===true);if(!w)fail('test_workflow_not_configured');allowed(c.repositories,repository);allowed(w.refs,ref);
  if(Object.keys(inputs).some(k=>!w.inputs?.includes(k))||Object.values(inputs).some(v=>typeof v!=='string'||v.length>2000)||!w.inputs?.includes('relay_command_id'))fail('workflow_inputs_not_allowed');
  const root='https://api.github.com/repos/'+repository,headers={Authorization:'Bearer '+credential(c),'X-GitHub-Api-Version':c.apiVersion??'2026-03-10','Content-Type':'application/json'};
  const head=await request(root+'/commits/'+e(ref),headers);if(!expectedSha||head.sha!==expectedSha)fail('workflow_ref_changed');
  await beforeWrite();await request(root+'/actions/workflows/'+workflowKey(workflowId)+'/dispatches',headers,{method:'POST',body:JSON.stringify({ref,inputs:{...inputs,relay_command_id:commandId}})});
  return {accepted:true,commandId,expectedSha,repository,workflowId,ref,state:'dispatch accepted; actual run and mapped results still unknown'};
 }
 return {read,writeComment,dispatch,catalog:()=>connectorCatalog(config)};
}
