import {readBoundedJSON} from '../../../src/ai.js';
import {repository} from './operations.js';
const encode=bytes=>btoa(String.fromCharCode(...bytes)),decode=text=>Uint8Array.from(atob(text),c=>c.charCodeAt(0)),url64=bytes=>encode(bytes).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const fail=code=>{throw Object.assign(new Error(code.replaceAll('_',' ')),{code});};
async function cipherKey(secrets){const bytes=decode(secrets('RELAY_CREDENTIAL_KEY'));if(bytes.length!==32)fail('credential_key_not_configured');return crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt']);}
async function seal(value,binding,secrets){const iv=crypto.getRandomValues(new Uint8Array(12)),bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(binding)},await cipherKey(secrets),new TextEncoder().encode(JSON.stringify(value)));return {iv:encode(iv),data:encode(new Uint8Array(bytes))};}
async function open(value,binding,secrets){return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(value.iv),additionalData:new TextEncoder().encode(binding)},await cipherKey(secrets),decode(value.data))));}
const binding=(project,user,provider)=>project+':'+user+':'+provider;
function settings(config,provider){const c=config.providers?.[provider];if(!c||!['github','drive','confluence','azure','clickup'].includes(provider))fail('oauth_not_configured');return c;}
function endpoints(provider,c){const tenant=c.tenantId;if(provider==='azure'&&!/^[a-zA-Z0-9-]+$/.test(tenant)||provider==='azure'&&['common','consumers'].includes(tenant))fail('specific_tenant_required');return ({github:['https://github.com/login/oauth/authorize','https://github.com/login/oauth/access_token'],drive:['https://accounts.google.com/o/oauth2/v2/auth','https://oauth2.googleapis.com/token'],confluence:['https://auth.atlassian.com/authorize','https://auth.atlassian.com/oauth/token'],azure:['https://login.microsoftonline.com/'+tenant+'/oauth2/v2.0/authorize','https://login.microsoftonline.com/'+tenant+'/oauth2/v2.0/token'],clickup:['https://app.clickup.com/api','https://api.clickup.com/api/v2/oauth/token']})[provider];}
async function tokenRequest(provider,c,parameters,secrets,fetchImpl){const [,url]=endpoints(provider,c),body={client_id:secrets(c.clientIdEnv),client_secret:secrets(c.clientSecretEnv),...parameters};if(!body.client_id||!body.client_secret)fail('oauth_not_configured');let response;try{response=await fetchImpl(url,{method:'POST',headers:{Accept:'application/json','Content-Type':['confluence','clickup'].includes(provider)?'application/json':'application/x-www-form-urlencoded'},body:['confluence','clickup'].includes(provider)?JSON.stringify(body):new URLSearchParams(body).toString(),redirect:'error',signal:AbortSignal.timeout(15000)});}catch{fail('token_exchange_uncertain');}const value=await readBoundedJSON(response,100000);if(!response.ok||value.error||typeof value.access_token!=='string')fail('oauth_reconnect_required');if(value.access_token.length>20000||value.refresh_token?.length>20000)fail('oauth_invalid_token');return {accessToken:value.access_token,refreshToken:value.refresh_token??'',expiresAt:value.expires_in?Date.now()+Number(value.expires_in)*1000:null,scope:value.scope??c.scopes??''};}
export function createOAuthService({admin,config,secrets,fetchImpl=fetch}){
 async function active(projectId,userId){const m=await repository(admin.from('relay_memberships').select('active,capability').eq('project_id',projectId).eq('user_id',userId).maybeSingle()),p=await repository(admin.from('relay_projects').select('active').eq('id',projectId).maybeSingle());if(!m?.active||!p?.active||!['owner','reviewer','editor'].includes(m.capability))fail('connector_access_lost');}
 async function start(projectId,userId,provider,returnUrl){await active(projectId,userId);const c=settings(config,provider),[endpoint]=endpoints(provider,c),callback=c.redirectUri,u=new URL(returnUrl);if(!config.returnUrls?.includes(u.href)||u.username||u.password||u.hash||u.search||!callback?.startsWith('https://')&&!callback?.startsWith('http://127.0.0.1:'))fail('oauth_return_denied');if(!secrets(c.clientIdEnv)||!secrets(c.clientSecretEnv))fail('oauth_not_configured');const state=crypto.randomUUID(),verifier=url64(crypto.getRandomValues(new Uint8Array(32))),challenge=url64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));await repository(admin.from('relay_oauth_states').insert({id:state,project_id:projectId,user_id:userId,provider,secret:await seal({verifier},state,secrets),return_url:returnUrl,expires_at:new Date(Date.now()+600000).toISOString()}));const url=new URL(endpoint);for(const [k,v]of Object.entries({client_id:secrets(c.clientIdEnv),redirect_uri:callback,response_type:'code',state,scope:c.scopes??''}))url.searchParams.set(k,v);if(['github','drive','azure'].includes(provider)){url.searchParams.set('code_challenge',challenge);url.searchParams.set('code_challenge_method','S256');}if(provider==='drive'){url.searchParams.set('access_type','offline');url.searchParams.set('prompt','consent select_account');}if(provider==='azure')url.searchParams.set('prompt','select_account');if(provider==='confluence'){url.searchParams.set('audience','api.atlassian.com');url.searchParams.set('prompt','consent');}return {url:url.href};}
 async function finish(stateId,code){if(!/^[a-f0-9-]{36}$/.test(stateId)||!code||code.length>4000)fail('oauth_invalid_callback');const state=(await repository(admin.rpc('relay_claim_oauth_state',{p_id:stateId})))?.[0];if(!state)fail('oauth_state_expired');await active(state.project_id,state.user_id);const c=settings(config,state.provider),secret=await open(state.secret,state.id,secrets),token=await tokenRequest(state.provider,c,{grant_type:'authorization_code',code,redirect_uri:c.redirectUri,...(['github','drive','azure'].includes(state.provider)?{code_verifier:secret.verifier}:{})},secrets,fetchImpl);let label=state.provider+' account';
 if(state.provider==='github'){const r=await fetchImpl('https://api.github.com/user',{headers:{Authorization:'Bearer '+token.accessToken},redirect:'error',signal:AbortSignal.timeout(8000)}),who=await readBoundedJSON(r,100000);if(!r.ok||!who.id)fail('oauth_account_unavailable');label=who.login+' · '+who.id;}
 if(state.provider==='drive'){const r=await fetchImpl('https://www.googleapis.com/drive/v3/about?fields=user',{headers:{Authorization:'Bearer '+token.accessToken},redirect:'error',signal:AbortSignal.timeout(8000)}),who=await readBoundedJSON(r,100000);if(!r.ok||!who.user)fail('oauth_account_unavailable');label=who.user.displayName+' · '+(who.user.emailAddress??who.user.permissionId??'');}
 if(state.provider==='clickup'){const r=await fetchImpl('https://api.clickup.com/api/v2/user',{headers:{Authorization:token.accessToken},redirect:'error',signal:AbortSignal.timeout(8000)}),who=await readBoundedJSON(r,100000);if(!r.ok||!who.user?.id)fail('oauth_account_unavailable');label=who.user.username+' · '+who.user.id;}
 if(state.provider==='confluence'){const r=await fetchImpl('https://api.atlassian.com/oauth/token/accessible-resources',{headers:{Authorization:'Bearer '+token.accessToken},redirect:'error',signal:AbortSignal.timeout(8000)}),sites=await readBoundedJSON(r,100000),site=Array.isArray(sites)&&sites.find(s=>s.id===c.cloudId&&s.url===c.siteOrigin);if(!r.ok||!site)fail('oauth_site_scope_denied');label=site.name+' · '+site.id;}
 await active(state.project_id,state.user_id);await repository(admin.from('relay_connector_accounts').upsert({project_id:state.project_id,user_id:state.user_id,provider:state.provider,account_label:label,secret:await seal(token,binding(state.project_id,state.user_id,state.provider),secrets),active:true,refresh_lease:null,refresh_until:null,updated_at:new Date().toISOString()}));return {returnUrl:state.return_url};}
 async function accessToken(projectId,userId,provider){await active(projectId,userId);const row=await repository(admin.from('relay_connector_accounts').select('*').eq('project_id',projectId).eq('user_id',userId).eq('provider',provider).eq('active',true).maybeSingle());if(!row)return null;let token=await open(row.secret,binding(projectId,userId,provider),secrets);if(token.expiresAt&&token.expiresAt<Date.now()+60000){if(!token.refreshToken)fail('oauth_reconnect_required');const lease=crypto.randomUUID(),locked=await repository(admin.rpc('relay_claim_token_refresh',{p_project:projectId,p_user:userId,p_provider:provider,p_revision:row.revision,p_lease:lease}));if(!locked)fail('oauth_refresh_requires_reconciliation');const refreshed=await tokenRequest(provider,settings(config,provider),{grant_type:'refresh_token',refresh_token:token.refreshToken},secrets,fetchImpl);token={...refreshed,refreshToken:refreshed.refreshToken||token.refreshToken};await active(projectId,userId);if(!await repository(admin.rpc('relay_store_token_refresh',{p_project:projectId,p_user:userId,p_provider:provider,p_lease:lease,p_secret:await seal(token,binding(projectId,userId,provider),secrets)})))fail('oauth_refresh_requires_reconciliation');}return token.accessToken;}
 return {start,finish,accessToken};
}
export function createOAuthHandler({admin,authenticate,config,secrets,allowedOrigins=[]}){const service=createOAuthService({admin,config,secrets});return async request=>{const origin=request.headers.get('origin'),headers={'Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Type':'application/json','Vary':'Origin',...(allowedOrigins.includes(origin)?{'Access-Control-Allow-Origin':origin}:{})};try{const url=new URL(request.url);if(request.method==='GET'){const result=await service.finish(url.searchParams.get('state'),url.searchParams.get('code'));return new Response(null,{status:303,headers:{...headers,Location:result.returnUrl}});}if(origin&&!allowedOrigins.includes(origin))fail('origin_denied');if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'authorization,apikey,content-type'}});const user=await authenticate(request.headers.get('authorization')?.replace(/^Bearer /,''));if(!user?.id)fail('auth_required');const input=await readBoundedJSON(request,10000);if(input.operation==='start'&&input.consent===true)return new Response(JSON.stringify(await service.start(input.projectId,user.id,input.provider,input.returnUrl)),{headers});if(input.operation==='disconnect'){await repository(admin.from('relay_connector_accounts').update({active:false}).eq('project_id',input.projectId).eq('user_id',user.id).eq('provider',input.provider));return new Response('{"ok":true}',{headers});}if(input.operation==='list'){const accounts=await repository(admin.from('relay_connector_accounts').select('provider,account_label,active,updated_at').eq('project_id',input.projectId).eq('user_id',user.id));return new Response(JSON.stringify({accounts,providers:Object.keys(config.providers??{})}),{headers});}fail('invalid_request');}catch(error){return new Response(JSON.stringify({error:{code:error.code??'oauth_unavailable',message:'Connection did not complete. Reconnect or inspect the account status.'}}),{status:error.code==='auth_required'?401:400,headers});}};}
