export async function repository(query){const {data,error}=await query;if(error)throw new Error('Operational repository unavailable.');return data;}
export const workerAuthorized=(request,secret)=>{const supplied=request.headers.get('authorization')??'',expected='Bearer '+secret;if(!secret||secret.length<32||supplied.length!==expected.length)return false;let d=0;for(let i=0;i<expected.length;i++)d|=supplied.charCodeAt(i)^expected.charCodeAt(i);return d===0;};
function targetURL(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.hostname==='localhost'||/^(127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/.test(u.hostname))throw new Error('Configured delivery endpoint must use public HTTPS.');return u;}
export async function operationalHealth(admin,projectId){
 const [jobs,controls,backups,restores]=await Promise.all([
  repository(admin.rpc('relay_project_job_health',{p_project:projectId})),
  repository(admin.from('relay_operational_controls').select('*').eq('project_id',projectId).maybeSingle()),
  repository(admin.from('relay_backup_receipts').select('*').eq('project_id',projectId).order('verified_at',{ascending:false}).limit(1)),
  repository(admin.from('relay_backup_receipts').select('restore_at,recovery_seconds').eq('project_id',projectId).not('restore_at','is',null).order('restore_at',{ascending:false}).limit(1))
 ]);const latest=backups?.[0],restore=restores?.[0],now=Date.now(),signals=[];
 if(!latest||now-Date.parse(latest.verified_at)>(controls?.backup_max_age_hours??48)*3600000)signals.push('backup-missing-or-overdue');
 if(jobs.oldestPendingAt&&now-Date.parse(jobs.oldestPendingAt)>(controls?.queue_max_age_minutes??30)*60000)signals.push('queue-stalled');
 if(jobs.uncertain||jobs.uncertainDeliveries)signals.push('external-outcome-uncertain');if(jobs.recentFailures)signals.push('recent-job-failure');
 return {...jobs,signals,alertOwner:controls?.alert_owner??'',latestBackup:latest??null,restoreDrill:restore?.restore_at??controls?.restore_drill_at??'No completed drill recorded',measuredRecoverySeconds:restore?.recovery_seconds??null,window:'All retained jobs; failure alert uses the last 24 hours',reconciliationAuthority:'Account-authenticated operator reports remain separate from provider observations'};
}
export function createOperationsHandler({admin,workerSecret,deliveryConfig={},secrets=()=>'',fetchImpl=fetch}){return async request=>{
 const reply=(status,value)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});if(request.method!=='POST'||!workerAuthorized(request,workerSecret))return reply(403,{error:'worker_auth_required'});let batch,sent=false;
 try{
  const projects=await repository(admin.rpc('relay_claim_health_projects',{p_limit:20}));
  for(const project of projects){const health=await operationalHealth(admin,project.id);await repository(admin.rpc('relay_record_health',{p_project:project.id,p_owner:project.owner_user_id,p_revision:project.revision,p_signals:health.signals}));await repository(admin.rpc('relay_prune_operations',{p_project:project.id}));}
  batch=(await repository(admin.rpc('relay_claim_delivery')))?.[0];if(!batch)return reply(200,{status:'idle',projectsObserved:projects.length});
  const [m,p,s,subscription]=await Promise.all([repository(admin.from('relay_memberships').select('active').eq('project_id',batch.project_id).eq('user_id',batch.user_id).maybeSingle()),repository(admin.from('relay_projects').select('active').eq('id',batch.project_id).maybeSingle()),repository(admin.from('relay_delivery_settings').select('enabled,destination').eq('project_id',batch.project_id).eq('user_id',batch.user_id).eq('channel',batch.channel).maybeSingle()),repository(admin.from('relay_subscriptions').select('enabled').eq('project_id',batch.project_id).eq('user_id',batch.user_id).maybeSingle())]);if(!m?.active||!p?.active||!s?.enabled||!subscription?.enabled||s.destination!==batch.destination){await repository(admin.rpc('relay_finish_delivery',{p_batch:batch.id,p_lease:batch.lease_token,p_status:'cancelled',p_error:'delivery_access_changed'}));return reply(200,{status:'cancelled'});}
  const destination=deliveryConfig.destinations?.[batch.destination];if(!destination||destination.channel!==batch.channel)throw Object.assign(new Error('Delivery destination unavailable.'),{code:'delivery_not_configured'});
  let url,body,headers={'Content-Type':'application/json'};
  if(batch.channel==='email'){const {data,error}=await admin.auth.admin.getUserById(batch.user_id);if(error||!data.user?.email_confirmed_at||!data.user.email)throw Object.assign(new Error('Verified account email required.'),{code:'verified_email_required'});url=targetURL('https://api.resend.com/emails');headers.Authorization='Bearer '+secrets(destination.apiKeyEnv);headers['Idempotency-Key']=batch.id;body={from:destination.from,to:[data.user.email],subject:'Product Relay updates',text:batch.summary};}
  else{url=targetURL(secrets(destination.urlEnv));body=batch.channel==='teams'?{type:'message',attachments:[{contentType:'application/vnd.microsoft.card.adaptive',content:{type:'AdaptiveCard',version:'1.2',body:[{type:'TextBlock',text:batch.summary,wrap:true}]}}]}:batch.channel==='slack'?{text:batch.summary}:{id:batch.id,projectId:batch.project_id,text:batch.summary};}
  let response;try{response=await fetchImpl(url,{method:'POST',headers,body:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(15000)});}catch{throw Object.assign(new Error('Delivery outcome unknown.'),{code:'delivery_outcome_uncertain'});}if(!response.ok)throw Object.assign(new Error('Delivery rejected.'),{code:response.status>=500?'delivery_outcome_uncertain':'delivery_rejected'});
  sent=true;if(!await repository(admin.rpc('relay_finish_delivery',{p_batch:batch.id,p_lease:batch.lease_token,p_status:'sent',p_error:null})))throw Object.assign(new Error('Delivery receipt could not be confirmed.'),{code:'delivery_outcome_uncertain'});return reply(200,{status:'sent',batchId:batch.id});
 }catch(error){if(batch)await admin.rpc('relay_finish_delivery',{p_batch:batch.id,p_lease:batch.lease_token,p_status:sent?'sent':error.code==='delivery_outcome_uncertain'?'uncertain':'failed',p_error:error.code??'operational_failure'});return reply(200,{status:'requires-attention',error:error.code??'operational_failure'});}
};}

export async function directoryOperation({admin,user,input}){if(input.action==='list'){const organizations=await repository(admin.from('relay_organizations').select('*').eq('owner_user_id',user.id));if(!organizations.length)return {organizations:[],groups:[],users:[]};const groups=await repository(admin.from('relay_directory_groups').select('*').in('organization_id',organizations.map(o=>o.id))),users=groups.length?await repository(admin.from('relay_directory_users').select('*').in('group_id',groups.map(g=>g.id))):[];return {organizations,groups,users};}if(!['create','group','user','grant'].includes(input.action)||input.action==='grant'&&(!Array.isArray(input.members)||input.members.length>100))throw Object.assign(new Error('Invalid directory command.'),{status:400,code:'invalid_request'});return {result:await repository(admin.rpc('relay_directory_command',{p_actor:user.id,p_operation:input.action,p_input:input}))};}
