import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';
import {sharedDatabase} from './helpers/shared-db.mjs';import {sqlAdmin} from './helpers/sql-admin.mjs';
import * as D from '../src/domain.js';import * as L from '../src/lifecycle.js';import {digest} from '../src/value.js';
import {createProjectsHandler,validateSharedMutation} from '../supabase/functions/_shared/projects.js';import {createJobsHandler} from '../supabase/functions/_shared/jobs.js';import {createOAuthService} from '../supabase/functions/_shared/oauth.js';import {assetOperation} from '../supabase/functions/_shared/assets.js';
import {createOperationsHandler} from '../supabase/functions/_shared/operations.js';
import {createProjectAIAuthorizer} from '../supabase/functions/_shared/project-ai.js';import * as K from '../src/knowledge.js';
let db,admin;before(async()=>{db=await sharedDatabase();admin=sqlAdmin(db);});after(async()=>{await db?.close();});
async function fixture(){const p=D.createProject('Fictional shared API journey'),members=['Product','QA','Development','Support'].map((role,i)=>D.addMember(p,'Fixture '+i,role)),users=members.map(()=>randomUUID());for(const id of users)await db.query('insert into auth.users values($1)',[id]);const created=await admin.rpc('relay_create_project',{p_actor:users[0],p_project:p,p_member:members[0].id});assert.ifError(created.error);for(let i=1;i<4;i++)assert.ifError((await admin.rpc('relay_set_membership',{p_project:p.id,p_actor:users[0],p_user:users[i],p_member:members[i].id,p_cap:['owner','reviewer','editor','reader'][i],p_active:true,p_perspective:members[i].role})).error);return {p,members,users};}
const origin='http://127.0.0.1:4187',secret=randomBytes(32).toString('hex');
const request=(input,token,extra={})=>new Request('https://fixture.example.test/functions/v1/relay-projects',{method:'POST',headers:{'content-type':'application/json',origin,...(token?{authorization:'Bearer '+token}:{}),...extra},body:JSON.stringify(input)});
const handler=()=>createProjectsHandler({admin,authenticate:async token=>({id:token}),allowedOrigins:[origin]});
async function call(f,operation,input={},actor=0){const r=await handler()(request({operation,projectId:f.p.id,...input},f.users[actor]));return {status:r.status,body:await r.json()};}
async function job(f,kind,input,actor=0){const result=await admin.rpc('relay_enqueue_job',{p_project:f.p.id,p_actor:f.users[actor],p_command:randomUUID(),p_revision:1,p_kind:kind,p_hash:await digest(input),p_input:input});assert.ifError(result.error);return result.data;}
const runWorker=async(f,fetchImpl,override={})=>{const worker=createJobsHandler({admin,workerSecret:secret,configuration:{projects:{[f.p.id]:{providers:{github:{repositories:['fixture/repo'],credentialEnv:'FIXTURE_TOKEN',writeComments:true}}}}},secrets:()=> 'fictional-token',fetchImpl,...override});return (await worker(new Request('https://fixture.example.test/worker',{method:'POST',headers:{authorization:'Bearer '+secret}}))).json();};
const locator={provider:'github',repository:'fixture/repo',type:'issue',id:'7'},issue={id:7,title:'Fixture issue',updated_at:'r1',state:'open',html_url:'https://github.com/fixture/repo/issues/7',body:'Fixture reviewed context.'};
test('HTTP boundary enforces origin, authentication, JSON and cross-project access',async()=>{const f=await fixture(),h=handler();assert.equal((await h(request({operation:'list'}))).status,401);assert.equal((await h(request({operation:'list'},f.users[0],{origin:'https://untrusted.example.test'}))).status,403);assert.equal((await h(request({operation:'list'},f.users[0],{'content-type':'text/plain'}))).status,415);const other=await fixture();assert.equal((await call(f,'read',{projectId:other.p.id})).status,403);assert.equal((await call(f,'read')).status,200);const reader=await call(f,'read',{},3);assert.equal(reader.status,200);assert.ok(reader.body.readingPack);assert.equal(reader.body.project,undefined);});
test('API commits exact authored content, replay deduplicates and stale commit conflicts',async()=>{const f=await fixture(),p=D.clone(f.p);D.updateProject(p,'Reviewed API change','');const commandId=randomUUID(),input={commandId,expectedRevision:1,baseHash:await digest(D.importProject(D.exportProject(f.p))),project:JSON.parse(D.exportProject(p))};const first=await call(f,'commit',input);assert.equal(first.status,200,JSON.stringify(first.body));assert.equal(first.body.revision,2);const replay=await call(f,'commit',input);assert.equal(replay.status,200);assert.equal(replay.body.duplicate,true);assert.equal((await call(f,'commit',{...input,commandId:randomUUID()})).status,409);});
test('server mutation blocks forged reviewer identity and stamps authenticated approvals',async()=>{const f=await fixture(),next=D.clone(f.p),r=L.addRecord(next,'requirements',{title:'Native agreement',scope:{state:'general'},data:{description:'Owner interpreted requirement.'}},f.members[0].id);L.approveRecord(next,'requirements',r.id,f.members[0].id,'Owner basis');const member={member_id:f.members[0].id,user_id:f.users[0],capability:'owner'};const accepted=validateSharedMutation(f.p,next,member,randomUUID());assert.equal(L.get(accepted,'requirements',r.id).approval.identity,'authenticated');assert.throws(()=>validateSharedMutation(f.p,next,{...member,capability:'editor'} ,randomUUID()),{code:'reviewer_required'});assert.throws(()=>validateSharedMutation(f.p,next,{...member,member_id:f.members[1].id},randomUUID()),{code:'actor_mismatch'});});
test('worker authenticates before touching jobs and preserves a provider read for review',async()=>{const f=await fixture();let requests=0;const worker=createJobsHandler({admin,workerSecret:secret,configuration:{},secrets:()=>'',fetchImpl:async()=>{requests++;}});assert.equal((await worker(new Request('https://fixture.example.test/worker',{method:'POST'}))).status,403);const id=await job(f,'connector-read',{locator});const result=await runWorker(f,async()=>{requests++;return Response.json(issue);});assert.equal(result.status,'review-required');assert.equal(requests,1);const row=(await db.query('select * from relay_jobs where id=$1',[id])).rows[0];assert.equal(row.output.origin,'provider-retrieved');assert.equal(row.output.locator.repository,'fixture/repo');});
test('worker retries safe rate-limited reads but rejects changed input before external calls',async()=>{const f=await fixture(),id=await job(f,'connector-read',{locator});const result=await runWorker(f,async()=>Response.json({}, {status:429}));assert.equal(result.error,'connector_rate_limited');assert.equal((await db.query('select status from relay_jobs where id=$1',[id])).rows[0].status,'queued');await db.query("update relay_jobs set status='cancelled' where id=$1",[id]);const invalid=await job(f,'connector-read',{locator});await db.query("update relay_jobs set input='{}' where id=$1",[invalid]);let sends=0;const rejected=await runWorker(f,async()=>{sends++;return Response.json(issue);});assert.equal(rejected.error,'input_redefined');assert.equal(sends,0);});
test('confirmed external send remains in outbox when the project changes before checkpoint',async()=>{const f=await fixture(),external=L.addRecord(f.p,'external',{title:'Reviewed issue',data:{locator}},f.members[0].id);await db.query('update relay_project_state set payload=$2 where project_id=$1',[f.p.id,JSON.stringify(f.p)]);const id=await job(f,'connector-write',{locator,externalRecordId:external.id,expectedRevision:'r1:',body:'Reviewed comment'});let sends=0;const result=await runWorker(f,async(url,options)=>{if(options.method==='POST'){sends++;await db.query('update relay_projects set revision=2 where id=$1',[f.p.id]);return Response.json({id:9,html_url:'https://github.com/fixture/repo/issues/7#issuecomment-9'});}return Response.json(issue);});assert.equal(result.error,'stale_input');assert.equal(sends,1);const outbox=(await db.query('select status,receipt from relay_outbox where project_id=$1',[f.p.id])).rows[0];assert.equal(outbox.status,'sent');assert.equal(outbox.receipt.id,'9');assert.equal((await db.query('select status from relay_jobs where id=$1',[id])).rows[0].status,'uncertain');assert.equal((await runWorker(f,async()=>{sends++;throw new Error('Must not resend');})).status,'idle');assert.equal(sends,1);});
test('asset upload/download verifies exact bytes and detects receipt mismatch',async()=>{const f=await fixture(),objects=new Map(),storage={from:()=>({upload:async(key,bytes)=>{objects.set(key,bytes);return {error:null};},download:async key=>({data:new Blob([objects.get(key)]),error:null})})},assetAdmin={...admin,storage},args={admin:assetAdmin,projectId:f.p.id,actorUserId:f.users[0],capability:'owner'};const {asset}=await assetOperation({...args,operation:'upload-asset',input:{consent:true,base64:btoa('fictional original'),fileName:'fixture.txt',mediaType:'text/plain'}});const downloaded=await assetOperation({...args,operation:'download-asset',input:{hash:asset.hash}});assert.equal(atob(downloaded.base64),'fictional original');objects.set(asset.object_key,new Uint8Array([1]));await assert.rejects(()=>assetOperation({...args,operation:'download-asset',input:{hash:asset.hash}}),{code:'asset_integrity'});});
test('OAuth mocked exchange uses PKCE and encrypted tokens; state replay is rejected',async()=>{const f=await fixture(),key=randomBytes(32).toString('base64'),secrets=name=>name==='RELAY_CREDENTIAL_KEY'?key:'fictional-client-secret',config={returnUrls:[origin+'/'],providers:{github:{clientIdEnv:'CLIENT_ID',clientSecretEnv:'CLIENT_SECRET',redirectUri:'https://fixture.example.test/callback',scopes:'repo'}}},calls=[];const oauth=createOAuthService({admin,config,secrets,fetchImpl:async(url,options)=>{calls.push({url:String(url),body:options.body});return String(url).includes('/access_token')?Response.json({access_token:'fictional-access-token'}):Response.json({id:99,login:'fixture'});}});await assert.rejects(()=>oauth.start(f.p.id,f.users[0],'github','https://untrusted.example.test/'),{code:'oauth_return_denied'});const {url}=await oauth.start(f.p.id,f.users[0],'github',origin+'/'),u=new URL(url);assert.equal(u.searchParams.get('code_challenge_method'),'S256');const state=u.searchParams.get('state');await oauth.finish(state,'fictional-code');assert.match(calls[0].body,/code_verifier=/);const record=(await db.query('select secret from relay_connector_accounts where project_id=$1',[f.p.id])).rows[0];assert.equal(JSON.stringify(record).includes('fictional-access-token'),false);assert.equal(await oauth.accessToken(f.p.id,f.users[0],'github'),'fictional-access-token');await assert.rejects(()=>oauth.finish(state,'fictional-code'),{code:'oauth_state_expired'});await db.query('update relay_memberships set active=false where project_id=$1 and user_id=$2',[f.p.id,f.users[0]]);await assert.rejects(()=>oauth.accessToken(f.p.id,f.users[0],'github'),{code:'connector_access_lost'});});
async function deliveryFixture(){const f=await fixture();assert.ifError((await admin.rpc('relay_save_delivery',{p_project:f.p.id,p_actor:f.users[1],p_channel:'webhook',p_destination:'fixture',p_enabled:true,p_digest:0,p_subscription_enabled:true})).error);await db.query('insert into relay_notifications(project_id,user_id,command_id,revision,summary) values($1,$2,$3,1,$4)',[f.p.id,f.users[1],randomUUID(),'Fictional sensitive customer fact']);return f;}
const operationWorker=(fetchImpl,extra={})=>createOperationsHandler({admin,workerSecret:secret,deliveryConfig:{destinations:{fixture:{channel:'webhook',urlEnv:'FIXTURE_URL'}}},secrets:()=> 'https://public.example.test/webhook',fetchImpl,...extra});
const workerRequest=()=>new Request('https://fixture.example.test/operations',{method:'POST',headers:{authorization:'Bearer '+secret}});
test('operations worker authenticates and delivers generic context with receipt deduplication',async()=>{const f=await deliveryFixture();let sends=0,body;const worker=operationWorker(async(url,options)=>{sends++;body=JSON.parse(options.body);return new Response(null,{status:204});});assert.equal((await worker(new Request('https://fixture.example.test/operations',{method:'POST'}))).status,403);assert.equal((await (await worker(workerRequest())).json()).status,'sent');assert.equal(sends,1);assert.equal(JSON.stringify(body).includes('sensitive customer'),false);await worker(workerRequest());assert.equal(sends,1);await db.query('update relay_delivery_settings set enabled=false where project_id=$1',[f.p.id]);});
test('notification send timeout retains uncertainty and cannot silently resend',async()=>{const f=await deliveryFixture();let sends=0;const worker=operationWorker(async()=>{sends++;throw new Error('Mock timeout after send');});const result=await (await worker(workerRequest())).json();assert.equal(result.error,'delivery_outcome_uncertain');assert.equal((await db.query('select status from relay_delivery_batches where project_id=$1',[f.p.id])).rows[0].status,'uncertain');await worker(workerRequest());assert.equal(sends,1);await db.query('update relay_delivery_settings set enabled=false where project_id=$1',[f.p.id]);});
test('revocation between batch claim and send cancels delivery without an external request',async()=>{const f=await deliveryFixture(),wrapped={...admin,rpc:async(name,args)=>{const result=await admin.rpc(name,args);if(name==='relay_claim_delivery'&&result.data?.length)await db.query('update relay_memberships set active=false where project_id=$1 and user_id=$2',[f.p.id,f.users[1]]);return result;}};let sends=0;const result=await (await operationWorker(async()=>{sends++;return new Response(null,{status:204});},{admin:wrapped})(workerRequest())).json();assert.equal(result.status,'cancelled');assert.equal(sends,0);});
test('configured delivery destinations reject private IPv4 and IPv6 before sending',async()=>{for(const url of ['http://public.example.test/','https://127.0.0.1/','https://[::1]/','https://[fd00::1]/']){const f=await deliveryFixture();let sends=0;await operationWorker(async()=>{sends++;return new Response(null,{status:204});},{secrets:()=>url})(workerRequest());assert.equal(sends,0,url);await db.query('update relay_delivery_settings set enabled=false where project_id=$1',[f.p.id]);}});
test('shared AI authorization checks current exact scoped evidence and rejects readers and forged context',async()=>{const f=await fixture(),source=D.addSource(f.p,'Fixture source','Ordinary cancellation retains paid access.'),req=L.addRecord(f.p,'requirements',{title:'Ordinary cancellation',scope:{state:'specific',flags:['fixture-rollout']},data:{description:source.revisions[0].content},evidence:[D.makeEvidence(f.p,source.id,source.revisions[0].content)]},f.members[0].id);L.approveRecord(f.p,'requirements',req.id,f.members[0].id,'Reviewed fixture scope');await db.query('update relay_project_state set payload=$2 where project_id=$1',[f.p.id,JSON.stringify(f.p)]);const input={task:'answer_question',projectId:f.p.id,...K.answerPayload(f.p,K.retrieveKnowledge(f.p,'ordinary cancellation',{flag:'fixture-rollout'}))},authorize=createProjectAIAuthorizer(admin);await authorize(f.users[0],input);await assert.rejects(()=>authorize(f.users[3],input),{code:'context_access_denied'});await assert.rejects(()=>authorize(f.users[0],{...input,answerContext:{...input.answerContext,selection:{...input.answerContext.selection,flag:'wrong-rollout'}}}),{code:'context_access_denied'});await assert.rejects(()=>authorize(f.users[0],{...input,sources:input.sources.map(s=>({...s,content:'Forged content'}))}),{code:'context_access_denied'});});
test('claimed provider source provenance without an actual reviewed job receipt is rejected',async()=>{const f=await fixture(),next=D.clone(f.p),s=D.addSource(next,'Forged provider source','Fictional statement');D.setSourceOrigin(next,s.id,{provider:'github',externalId:'7',revision:'r1',retrievedAt:new Date().toISOString(),access:'available',locator,lastJobId:randomUUID()});const response=await call(f,'commit',{commandId:randomUUID(),expectedRevision:1,baseHash:await digest(D.importProject(D.exportProject(f.p))),project:JSON.parse(D.exportProject(next))});assert.equal(response.status,400);assert.equal(response.body.error.code,'invalid_origin');assert.equal((await db.query('select revision from relay_projects where id=$1',[f.p.id])).rows[0].revision,1);});
