import test from 'node:test';import assert from 'node:assert/strict';import {createMediaProvider} from '../supabase/functions/_shared/media-provider.js';import {validateMedia} from '../src/media.js';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jJ1sAAAAASUVORK5CYII=';
function wav(seconds=1){const bytes=Buffer.alloc(44+16000*seconds);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(8000,24);bytes.writeUInt32LE(16000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(bytes.length-44,40);return bytes;}
const provider=fetchImpl=>createMediaProvider({secrets:name=>name==='OPENAI_API_KEY'?'fictional-key':'fictional-model',fetchImpl});
test('media boundary rejects malformed audio, oversized images and unsupported processing kinds',()=>{assert.throws(()=>validateMedia(new Uint8Array([1,2]),'transcribe'),/PCM WAV/);const image=Uint8Array.from(Buffer.from(png,'base64'));new DataView(image.buffer).setUint32(16,20000001);assert.throws(()=>validateMedia(image,'ocr'),/20 million/);assert.throws(()=>validateMedia(new Uint8Array([1]),'unknown'),/Unsupported/);});
test('OCR retains original hash, location, model, warning and human-review requirement',async()=>{let body;const result=await provider(async(url,options)=>{body=JSON.parse(options.body);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({text:'Fictional visible words',warnings:['One ambiguous word']})}]}]});})('ocr',{base64:png,fileName:'fixture.png',page:2});assert.equal(body.store,false);assert.equal(result.original.page,2);assert.equal(result.original.sha256.length,64);assert.equal(result.requiresHumanReview,true);assert.equal(result.model,'fictional-model');assert.deepEqual(result.warnings,['One ambiguous word']);});
test('transcription labels offset segments and does not invent cross-clip speaker identity',async()=>{const result=await provider(async()=>Response.json({segments:[{text:'Fictional speech',speaker:'A',start:0,end:1}]}))('transcribe',{base64:wav().toString('base64'),diarize:true,startSeconds:120,endSeconds:121,clip:2});assert.match(result.text,/120.00–121.00.*Clip 2 A/);assert.match(result.warnings[0],/continuity across clips/);});
test('clip duration and provider segment bounds must agree with retained original',async()=>{let sends=0;const fn=provider(async()=>{sends++;return Response.json({segments:[{text:'bad segment',speaker:'A',start:0,end:100}]});});await assert.rejects(()=>fn('transcribe',{base64:wav().toString('base64'),diarize:true,startSeconds:1,endSeconds:4}),{code:'media_limit'});assert.equal(sends,0);await assert.rejects(()=>fn('transcribe',{base64:wav().toString('base64'),diarize:true}),{code:'invalid_output'});});
test('media transport timeout, 5xx and undecodable success preserve paid-outcome uncertainty',async()=>{for(const mode of ['timeout','server','json']){let sends=0;await assert.rejects(()=>provider(async()=>{sends++;if(mode==='timeout')throw new Error('fixture timeout');return mode==='server'?Response.json({}, {status:503}):new Response('invalid json');})('ocr',{base64:png}),{code:'provider_result_uncertain'});assert.equal(sends,1);}});
test('missing provider configuration and invalid extracted output cannot produce an approved record',async()=>{await assert.rejects(()=>createMediaProvider({secrets:()=>'',fetchImpl:async()=>{throw new Error('Must not call');}})('ocr',{base64:png}),{code:'not_configured'});await assert.rejects(()=>provider(async()=>Response.json({status:'completed',output:[{content:[{type:'output_text',text:'{"text":"","warnings":[]}'}]}]}))('ocr',{base64:png}),{code:'invalid_output'});});
