// Operator-only: PostgreSQL CLI + read access to private storage; never prints secrets.
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {packBackup,unpackBackup,fileHash} from './backup-format.mjs';
export function databaseEnvironment(raw){const url=new URL(raw);if(!['postgres:','postgresql:'].includes(url.protocol))throw new Error('Use a PostgreSQL connection URL.');return {...process.env,PGHOST:url.hostname,PGPORT:url.port||'5432',PGUSER:decodeURIComponent(url.username),PGPASSWORD:decodeURIComponent(url.password),PGDATABASE:decodeURIComponent(url.pathname.slice(1)),PGSSLMODE:url.searchParams.get('sslmode')??'require'};}
export function command(binary,args,env,{output}={}){return new Promise((resolveResult,reject)=>{const child=spawn(binary,args,{env,stdio:['ignore','pipe','ignore']});let text='',size=0;child.stdout.on('data',b=>{size+=b.length;if(size>30000000){child.kill();reject(new Error('Database metadata exceeds backup budget.'));}text+=b;});child.on('error',()=>reject(new Error(binary+' unavailable.')));child.on('close',code=>code===0?resolveResult(text):reject(new Error(binary+' failed. Inspect the database operator logs.')));});}
const service=process.env.RELAY_SERVICE_URL,key=process.env.RELAY_SERVICE_SECRET_KEY,database=process.env.RELAY_DATABASE_URL;if(!service||!key||!database)throw new Error('Configure service URL, service secret and database URL in the operator environment.');const base=new URL(service);if(base.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(base.hostname))throw new Error('Use HTTPS for remote service access.');const env=databaseEnvironment(database),folder=await mkdtemp(resolve(tmpdir(),'relay-backup-')),destination=resolve(process.env.RELAY_BACKUP_DIRECTORY??'work/backups');await mkdir(destination,{recursive:true,mode:0o700});let holder;
try{
 holder=spawn('psql',['-X','-q','-t','-A'],{env,stdio:['pipe','pipe','ignore']});const snapshot=await new Promise((done,reject)=>{let text='';holder.stdout.on('data',b=>{text+=b;if(text.includes('\n'))done(text.trim().split('\n')[0]);});holder.on('error',()=>reject(new Error('psql unavailable.')));holder.on('exit',()=>reject(new Error('Snapshot connection closed.')));holder.stdin.write('BEGIN ISOLATION LEVEL REPEATABLE READ; SELECT pg_export_snapshot();\n');});if(!/^[A-Fa-f0-9-]+$/.test(snapshot))throw new Error('Invalid database snapshot.');
 const dump=resolve(folder,'database.dump');await command('pg_dump',['--format=custom','--no-owner','--snapshot='+snapshot,'--file='+dump],env);
 const query="BEGIN ISOLATION LEVEL REPEATABLE READ; SET TRANSACTION SNAPSHOT '"+snapshot+"'; SELECT json_build_object('projects',(SELECT coalesce(json_agg(json_build_object('id',id,'revision',revision)),'[]') FROM public.relay_projects),'assets',(SELECT coalesce(json_agg(row_to_json(a)),'[]') FROM public.relay_asset_receipts a)); COMMIT;";
 const metadata=JSON.parse((await command('psql',['-X','-q','-t','-A','-c',query],env)).trim());holder.stdin.end('ROLLBACK;\n');holder=null;
 if(metadata.assets.length>100000)throw new Error('Asset count exceeds backup budget.');const files=[{name:'database.dump',path:dump}],objects=[];await mkdir(resolve(folder,'objects'));
 for(const asset of metadata.assets){const name='objects/'+createHash('sha256').update(asset.object_key).digest('hex'),path=resolve(folder,name),url=new URL('/storage/v1/object/authenticated/relay-originals/'+asset.object_key.split('/').map(encodeURIComponent).join('/'),base),response=await fetch(url,{headers:{Authorization:'Bearer '+key,apikey:key},redirect:'error',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('A private original could not be backed up.');const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length!==asset.byte_length||createHash('sha256').update(bytes).digest('hex')!==asset.hash)throw new Error('Original checksum differs from its receipt.');await writeFile(path,bytes,{mode:0o600});files.push({name,path});objects.push({file:name,key:asset.object_key,hash:asset.hash,mediaType:asset.media_type});}
 const captured={},names=new Set(['RELAY_ALLOWED_ORIGINS','RELAY_DEFAULT_PROVIDER','RELAY_WORKER_SECRET','RELAY_CREDENTIAL_KEY','RELAY_CONNECTORS_JSON','RELAY_OAUTH_JSON','RELAY_DELIVERY_JSON','OPENAI_API_KEY','OPENAI_MODEL','OPENAI_OCR_MODEL','OPENAI_TRANSCRIBE_MODEL','OPENAI_DIARIZE_MODEL','ANTHROPIC_API_KEY','ANTHROPIC_MODEL']);
 function collectSecrets(value){if(!value||typeof value!=='object')return;for(const [field,item] of Object.entries(value)){if(field.endsWith('Env')&&typeof item==='string'&&/^[A-Z][A-Z0-9_]{0,100}$/.test(item))names.add(item);else if(item&&typeof item==='object')collectSecrets(item);}}
 for(const name of ['RELAY_CONNECTORS_JSON','RELAY_OAUTH_JSON','RELAY_DELIVERY_JSON'])if(process.env[name])collectSecrets(JSON.parse(process.env[name]));for(const name of names)if(process.env[name])captured[name]=process.env[name];await writeFile(resolve(folder,'operator-config.json'),JSON.stringify(captured),{mode:0o600});files.push({name:'operator-config.json',path:resolve(folder,'operator-config.json')});
 const manifest={format:'product-relay-service-backup',version:1,createdAt:new Date().toISOString(),sourceDatabaseHash:createHash('sha256').update(env.PGHOST+':'+env.PGPORT+'/'+env.PGDATABASE).digest('hex'),projects:metadata.projects,objects,capturedConfigurationKeys:Object.keys(captured),scope:'Full database snapshot and every receipted Relay private original. Unreceipted objects and unrelated application buckets are outside this package.'};await writeFile(resolve(folder,'manifest.json'),JSON.stringify(manifest),{mode:0o600});files.push({name:'manifest.json',path:resolve(folder,'manifest.json')});const path=resolve(destination,'relay-'+Date.now()+'.relay-backup'),hash=await packBackup(files,path);const verified=resolve(folder,'verified');await unpackBackup(path,verified);if(await fileHash(resolve(verified,'database.dump'))!==await fileHash(dump))throw new Error('Backup verification failed.');
 for(const p of metadata.projects){const response=await fetch(new URL('/rest/v1/relay_backup_receipts',base),{method:'POST',headers:{Authorization:'Bearer '+key,apikey:key,'Content-Type':'application/json'},body:JSON.stringify({project_id:p.id,revision:p.revision,artifact_hash:hash,storage_label:path.split('/').at(-1),verified_at:new Date().toISOString()}),redirect:'error',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Backup exists but its health receipt could not be recorded.');}
 console.log(JSON.stringify({status:'encrypted-and-checksum-verified',file:path,projects:metadata.projects.length,originals:objects.length,restoreDrill:'not run'}));
}finally{if(holder){holder.stdin.end('ROLLBACK;\n');holder.kill();}await rm(folder,{recursive:true,force:true});}
