// Restore into an explicitly selected separate environment; never runs implicitly.
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {unpackBackup,fileHash} from './backup-format.mjs';
const source=process.argv.find(a=>a.startsWith('--file='))?.slice(7),apply=process.argv.includes('--apply-to-empty-environment');if(!source)throw new Error('Supply --file=path; add --apply-to-empty-environment only for an empty isolated recovery environment.');const staging=await mkdtemp(resolve(tmpdir(),'relay-restore-')),folder=resolve(staging,'extracted'),started=Date.now();
const run=(binary,args,env)=>new Promise((done,reject)=>{const child=spawn(binary,args,{env,stdio:['ignore','pipe','ignore']});let output='';child.stdout.on('data',b=>output+=b);child.on('error',()=>reject(new Error(binary+' unavailable.')));child.on('exit',code=>code===0?done(output):reject(new Error(binary+' failed.')));});
try{await unpackBackup(source,folder);const manifest=JSON.parse(await readFile(resolve(folder,'manifest.json'),'utf8'));if(manifest.format!=='product-relay-service-backup'||manifest.version!==1)throw new Error('Invalid backup manifest.');if(!apply){console.log(JSON.stringify({status:'verified-extraction-only',projects:manifest.projects.length,originals:manifest.objects.length,restoreDrill:'not run'}));}else{
 const db=new URL(process.env.RELAY_RESTORE_DATABASE_URL??''),service=new URL(process.env.RELAY_RESTORE_SERVICE_URL??''),key=process.env.RELAY_RESTORE_SERVICE_SECRET_KEY;if(!key||service.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(service.hostname))throw new Error('Configure an isolated restore database and storage service.');const env={...process.env,PGHOST:db.hostname,PGPORT:db.port||'5432',PGDATABASE:decodeURIComponent(db.pathname.slice(1)),PGUSER:decodeURIComponent(db.username),PGPASSWORD:decodeURIComponent(db.password),PGSSLMODE:db.searchParams.get('sslmode')??'require'};if(createHash('sha256').update(env.PGHOST+':'+env.PGPORT+'/'+env.PGDATABASE).digest('hex')===manifest.sourceDatabaseHash)throw new Error('A restore drill cannot overwrite its source database.');
 const count=await run('psql',['-X','-q','-t','-A','-c',"select count(*) from pg_tables where schemaname not in ('pg_catalog','information_schema')"],env);if(Number(count.trim())>0)throw new Error('Restore target already contains application tables. Use an empty isolated environment.');await run('pg_restore',['--exit-on-error','--single-transaction','--no-owner','--dbname='+env.PGDATABASE,resolve(folder,'database.dump')],env);
 for(const object of manifest.objects){if(!/^objects\/[a-f0-9]{64}$/.test(object.file)||!/^[-a-f0-9]+\/[a-f0-9]{64}$/.test(object.key)||await fileHash(resolve(folder,object.file))!==object.hash)throw new Error('Original manifest integrity failed.');const response=await fetch(new URL('/storage/v1/object/relay-originals/'+object.key,service),{method:'POST',headers:{Authorization:'Bearer '+key,apikey:key,'Content-Type':object.mediaType,'x-upsert':'true'},body:await readFile(resolve(folder,object.file)),redirect:'error',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('Original restore failed.');const check=await fetch(new URL('/storage/v1/object/authenticated/relay-originals/'+object.key,service),{headers:{Authorization:'Bearer '+key,apikey:key},redirect:'error',signal:AbortSignal.timeout(30000)});if(!check.ok||createHash('sha256').update(Buffer.from(await check.arrayBuffer())).digest('hex')!==object.hash)throw new Error('Restored original differs.');}
 const restored=JSON.parse((await run('psql',['-X','-q','-t','-A','-c',"select coalesce(json_agg(json_build_object('id',id,'revision',revision)),'[]') from public.relay_projects"],env)).trim());if(JSON.stringify(restored.sort((a,b)=>a.id.localeCompare(b.id)))!==JSON.stringify(manifest.projects.sort((a,b)=>a.id.localeCompare(b.id))))throw new Error('Restored project revisions differ.');await run('psql',['-X','-q','-t','-A','-c',"update public.relay_jobs set status='uncertain',error_code='restore_reconciliation_required',lease_until=null where status in ('queued','leased');update public.relay_delivery_batches set status='uncertain',error_code='restore_reconciliation_required' where status in ('queued','sending');update public.relay_oauth_states set used=true;"],env);const configuration=await readFile(resolve(folder,'operator-config.json'));const configurationPath=resolve(process.env.RELAY_RESTORE_CONFIG_OUTPUT??'deploy/operator-state/restored-config.private.json');await (await import('node:fs/promises')).mkdir((await import('node:path')).dirname(configurationPath),{recursive:true,mode:0o700});await writeFile(configurationPath,configuration,{flag:'wx',mode:0o600});
 const report={status:'database-and-originals-restored',backupHash:await fileHash(source),completedAt:new Date().toISOString(),recoverySeconds:Math.round((Date.now()-started)/1000),recoverableStateAt:manifest.createdAt,projects:restored.length,originals:manifest.objects.length,limit:'Captured operator configuration is exported to a private file and not activated. Reconcile jobs/sends and verify accounts before starting workers.'};const backupHash=report.backupHash;for(const project of restored){const receipt=await fetch(new URL('/rest/v1/relay_backup_receipts',service),{method:'POST',headers:{Authorization:'Bearer '+key,apikey:key,'Content-Type':'application/json'},body:JSON.stringify({project_id:project.id,revision:project.revision,artifact_hash:backupHash,storage_label:'isolated-restore-drill',verified_at:report.completedAt,restore_at:report.completedAt,recovery_seconds:report.recoverySeconds}),redirect:'error',signal:AbortSignal.timeout(15000)});if(!receipt.ok)throw new Error('Restore completed but its evidence receipt could not be recorded.');}
 const reportPath=resolve(process.env.RELAY_RESTORE_REPORT??'work/restore-report.json');await (await import('node:fs/promises')).mkdir((await import('node:path')).dirname(reportPath),{recursive:true});await writeFile(reportPath,JSON.stringify(report,null,2),{mode:0o600});console.log(JSON.stringify({status:report.status,report:reportPath,recoverySeconds:report.recoverySeconds}));
}}finally{await rm(staging,{recursive:true,force:true});}
