import * as D from './domain.js';
import * as L from './lifecycle.js';
export function attentionItems(p,{role='Everyone',person='',ownership='team',releaseId='',environmentId='',audience='',build='',flag=''}={}){
  const items=[],context={releaseId,environmentId,audience,build,flag};
  const relevant=r=>L.roleMatches(p,r.role??r.base?.role??'Everyone',role)&&(ownership!=='mine'||(person&&(r.ownerId===person||r.reviewerId===person||r.owner===p.members.find(m=>m.id===person)?.name)));
  const add=(id,kind,record,reason,view,action='',extra={})=>{if(relevant(record)&&(!record.scope||L.scopeMatch(record.scope,context)!==false))items.push({id,kind,recordId:record.id,title:record.title??record.proposed?.title??record.base?.title??'Review',reason,view,action,record,...extra});};
  for(const c of p.behaviorChanges??[])if(c.status==='pending'){const b=p.behaviors.find(b=>b.id===c.behaviorId);if(!b?.audiences.some(a=>L.roleMatches(p,a,role)))continue;add('rule-proposal:'+c.id,'rule proposal',{...c,title:c.proposed.title,role,owner:b?.owner},c.reason,'rules','accept-rule',{reject:'reject-rule'});}
  for(const c of p.changes)if(c.status==='pending')add('handbook-proposal:'+c.id,'handbook proposal',c,c.reason,'handbook','accept',{reject:'reject'});
  for(const c of p.actionChanges??[])if(c.status==='pending')add('task-proposal:'+c.id,'task proposal',{...c,role:c.proposed.role,ownerId:c.proposed.ownerId},c.reason,'delivery','accept-action-change',{reject:'reject-action-change'});
  for(const q of p.questions??[])if(q.status==='open')add('question:'+q.id,'question',q,'Owner answer or decision is missing','questions','resolve-question');
  for(const s of p.sections)if(!s.archived&&D.isStale(p,s))add('section-source:'+s.id,'changed source',s,'Handbook evidence has a newer source revision','handbook');
  for(const b of p.behaviors??[])if(!b.archived&&b.audiences.some(a=>L.roleMatches(p,a,role))&&D.isStale(p,b))add('rule-source:'+b.id,'changed source',{...b,role},'Product rule evidence has a newer source revision','rules');
  for(const a of p.actions??[]){const review=D.actionReviewState(p,a);if(review.needsReview||review.sourceNeedsReview)add('action-stale:'+a.id,'affected work',a,review.reasons.join(' ')||'Underlying rule or source changed','delivery','rescope-action');if(a.ownerId&&a.status!=='proposed'&&a.status!=='not-applicable'&&!D.currentOwnerAcknowledgment(p,a))add('action-receipt:'+a.id,'owner receipt',a,'Current owner has not acknowledged this work scope','delivery','ack-action');}
  for(const kind of ['requirements','cases','guidance','components','objectives','templates'])for(const r of L.list(p,kind).filter(r=>!r.archived)){if(r.status==='draft')add(`draft:${kind}:${r.id}`,'draft approval',r,'Draft awaits evidence/owner review','lifecycle','lc-approve',{family:kind});else if(D.isStale(p,r)||L.staleRefs(p,r).length||kind==='guidance'&&L.guidanceNeedsReview(p,r)||L.scopeMatch(r.scope,context)===null)add(`stale:${kind}:${r.id}`,'affected context',r,'Source or linked agreement changed; review applicability','lifecycle','lc-detail',{family:kind});}
  for(const r of L.list(p,'proposals').filter(r=>r.status==='pending'))add('native-proposal:'+r.id,'delivery proposal',r,r.note,'lifecycle','lc-decide',{family:'proposals'});
  for(const r of L.list(p,'work').filter(r=>!r.archived)){if(L.staleRefs(p,r).length)add('work-stale:'+r.id,'affected work',r,'Underlying requirement revision changed','lifecycle','lc-detail',{family:'work'});if(r.ownerId&&r.status!=='proposed'&&r.status!=='not-applicable'&&!L.currentReceipt(r))add('work-receipt:'+r.id,'owner receipt',r,'Current owner receipt is missing','lifecycle','lc-ack',{family:'work'});}
  for(const row of L.evidenceMatrix(p,context))if(row.state!=='has current evidence')add('evidence:'+row.requirement.id,'evidence gap',row.requirement,row.state,'evidence','lc-detail',{family:'requirements'});
  for(const r of L.list(p,'exceptions').filter(r=>!r.archived))if(r.status!=='accepted'||!r.ownerId||!r.data.expiresAt||Date.parse(r.data.expiresAt)<=Date.now()||L.staleRefs(p,r).length)add('exception:'+r.id,'risk review',r,'Risk decision is missing, expired or based on changed context','release','lc-detail',{family:'exceptions'});
  return items;
}
export function renderInbox(p,context){const {esc,header,button,badge}=context,items=attentionItems(p,context);return header('ONE REVIEW QUEUE','Review inbox',`${context.ownership==='mine'?'My owned items':'Team view'} · ${context.role} · proposals, questions, affected work and missing evidence.`)+`<div class="metrics"><article><span>Items in this view</span><strong>${items.length}</strong><small>Same selector as Overview and navigation</small></article><article><span>Proposals</span><strong>${items.filter(i=>i.kind.includes('proposal')).length}</strong><small>Approved context remains unchanged</small></article></div><div class="section-grid">${items.map(i=>`<article class="panel section-card"><div class="card-meta">${badge(i.kind,'warning')}</div><h2>${esc(i.title)}</h2><p>${esc(i.reason)}</p><div class="card-actions">${i.action?button('Review item',i.action,`data-id="${i.recordId}" data-kind="${i.family??''}"`,'primary'):''}${button('Open context','nav',`data-view="${i.view}"`,'secondary')}</div></article>`).join('')||'<div class="empty panel"><h2>No pending items in this filtered view</h2><p>Other owners, roles or releases may still have outstanding work.</p></div>'}</div>`;}
