import * as C from './shared.js';
import * as D from './domain.js';
import * as L from './lifecycle.js';
import {equal} from './value.js';
import {validateMedia} from './media.js';
import {changeContract} from './planning.js';

// A queue acknowledgement is never approval, test execution or deployment proof.
export function createConnectorActions(c){
 const {project,commit,modal,field,submit,options,esc,notify,render,close,button}=c;
 const select=(label,name,rows,value='')=>`<label for="connector-${name}">${esc(label)}</label><select id="connector-${name}" name="${name}">${options(rows,value)}</select>`;
 const member=()=>select('Reviewed by','memberId',project().members.map(m=>[m.id,m.name]),C.connection(project().id)?.memberId||c.person());
 const scopeFields=()=>select('Release','releaseId',[['','Unknown'],...L.list(project(),'releases').map(r=>[r.id,r.title])])+select('Environment','environmentId',[['','Unknown'],...L.list(project(),'environments').map(r=>[r.id,r.title])]);
 const scope=f=>({state:f.get('releaseId')||f.get('environmentId')?'specific':'unknown',releaseIds:f.get('releaseId')?[f.get('releaseId')]:[],environmentIds:f.get('environmentId')?[f.get('environmentId')]:[]});
 function enqueuer(kind){const commandId=crypto.randomUUID(),id=project().id,revision=C.connection(id)?.revision;let sentInput;
  return async input=>{if(sentInput&&!equal(input,sentInput))throw new Error('This command already has an uncertain outcome. Retry the same input or inspect jobs before starting a new command.');sentInput=structuredClone(input);const result=await C.sharedCall('enqueue',{projectId:id,kind,input,commandId,expectedRevision:revision,consent:true});await C.refreshSharedActivity(id);close();render();notify('Job queued: '+result.jobId+'. A configured worker must process it; review the output afterward.');};
 }
 async function chooseReference(){const {connectors}=await C.sharedCall('catalog',{projectId:project().id});const refs=[];
  for(const x of connectors){if(x.provider==='github')for(const repository of x.repositories)for(const type of ['issue','pull','run','deployment'])refs.push({provider:x.provider,repository,type,id:''});
   for(const [key,type]of [['pageIds','page'],['fileIds','file'],['workItemIds','work-item'],['runIds','run'],['taskIds','task'],['docIds','doc']])for(const id of x[key]??[])refs.push({provider:x.provider,type,id:String(id)});}
  const enqueue=enqueuer('connector-read');modal('Read an explicitly selected external reference',select('Configured reference','reference',refs.map((r,i)=>[String(i),r.provider+' · '+(r.repository??r.id)+' · '+r.type]))+field('GitHub issue / PR / run / deployment number (ignored for other providers)','number','1','number')+'<p>Only administrator-selected scopes are readable. A refresh creates a review candidate; it does not change the agreement.</p><label class="checkbox-label"><input type="checkbox" required><span>Retrieve this selected reference through my configured service.</span></label>'+submit('Queue selected read'),async f=>{const r=refs[Number(f.get('reference'))];if(!r)throw new Error('No references configured. Ask the service administrator to configure selected scopes.');await enqueue({...{locator:{...r,id:r.provider==='github'?String(f.get('number')):r.id}}});});
 }
 async function reviewResult(el){const {job}=await C.sharedCall('job-result',{projectId:project().id,jobId:el.dataset.id}),o=job.output;
  if(!o||job.status!=='review-required'){modal('Job status and retained context',`<p>${esc(job.status)} · ${esc(job.error_code??'')} ${job.cost_uncertain?'· external outcome/cost uncertain':''}</p><p>A missing reference, timeout or rate limit is not proof of deletion.</p>`+(job.error_code==='connector_access_lost'?button('Mark matching source access unavailable','connector-access-lost',`data-id="${job.id}"`,'secondary'):'')+`<pre>${esc(JSON.stringify(job.input??{},null,2))}</pre>`+submit('Close'),async()=>close());return;}
  const raw=o.description??o.text??'',native=L.list(project(),'external').find(r=>equal(r.data.locator,o.locator)),source=project().sources.find(s=>o.locator&&equal(s.origin?.locator,o.locator));
  modal('Review retrieved result',`<p>${esc(o.title??o.original?.fileName??job.kind)} · ${esc(o.revision??o.contentHash??'')}</p><p>Job ${esc(job.id)} · input server r${job.expected_revision}. Current project scope and case mappings require review.</p>${(o.warnings??[]).map(w=>`<p class="warning-banner">${esc(w)}</p>`).join('')}<pre>${esc(raw)}</pre>${o.artifactMetadata?.length?`<h3>Actual artifact metadata</h3><pre>${esc(JSON.stringify(o.artifactMetadata,null,2))}</pre><p>Artifact contents are not downloaded or treated as case results. Import the actual bounded result file separately.</p>`:''}${o.accepted?`<p>Dispatch accepted for command ${esc(o.commandId)}. Actual run and results remain unknown.</p>${button('Find actual matching workflow run','connector-correlate',`data-id="${job.id}"`,'secondary')}`:''}${o.caseResults?.length?button('Review actual result mappings','connector-map-run',`data-id="${job.id}"`,'primary'):''}${o.type==='deployment'&&o.status==='success'?button('Map deployment observation','connector-map-deploy',`data-id="${job.id}"`,'primary'):''}${o.locator?select('Apply selected content as','apply',[['external','External reference; external status remains authoritative'],['source','Unapproved source revision'],['none','Keep as job output only']]):select('Apply extraction as','apply',[['source','Unapproved source for human correction'],['none','Keep as job output only']])}${scopeFields()}${member()}${!o.title?field('Source title','title',o.original?.fileName??'Reviewed extraction'):''}<p>Earlier source revisions are retained. Extracted text is uncertain; correct it in a separately recorded human revision after import. No agreement or case approval occurs here.</p>`+submit('Apply reviewed selection'),async f=>{if(f.get('apply')==='none'){close();return;}await commit(p=>{if(f.get('apply')==='external'){if(!o.locator)throw new Error('This extraction has no external work-system reference.');const data={description:raw,externalId:o.externalId,externalRevision:o.revision,url:o.url,locator:o.locator,origin:'provider-retrieved',lastJobId:job.id,externalStatus:o.status,externalOwnedFields:['title','description'],retrievedAt:o.retrievedAt,warnings:o.warnings??[]};if(native)L.editRecord(p,'external',native.id,{title:o.title,data},f.get('memberId'),'Reviewed selected external refresh',{external:true});else L.addRecord(p,'external',{title:o.title,status:'recorded',scope:scope(f),data},f.get('memberId'));}
    else{if(!raw.trim())throw new Error('No source text returned.');let s=source?p.sources.find(s=>s.id===source.id):null;if(s)D.reviseSource(p,s.id,raw);else s=D.addSource(p,o.title??f.get('title'),raw,o.locator?'Document':o.original?.mediaType==='audio/wav'?'Walkthrough':'Document');D.setSourceOrigin(p,s.id,{provider:o.locator?o.provider:(o.original?.mediaType==='audio/wav'?'openai-transcribe':'openai-ocr'),externalId:o.externalId??job.id,revision:o.revision??o.contentHash??job.id,access:'available',retrievedAt:o.retrievedAt??new Date().toISOString(),lastJobId:job.id,locator:o.locator??{provider:o.original?.mediaType==='audio/wav'?'openai-transcribe':'openai-ocr'},...(o.original?{extraction:{...o.original,provider:o.provider,model:o.model,warnings:o.warnings??[],requiresHumanReview:true}}:{})});}
   });notify('Reviewed context retained. Approval and evidence applicability require separate decisions.');});
 }
 const actions={
  'connector-select':chooseReference,
  'connector-refresh':el=>{const r=L.get(project(),'external',el.dataset.id),enqueue=enqueuer('connector-read');if(!r?.data.locator)throw new Error('Choose a retrieved external reference first.');modal('Refresh this exact reference',`<pre>${esc(JSON.stringify(r.data.locator,null,2))}</pre><p>Old context remains until the result is reviewed.</p>`+submit('Queue refresh'),()=>enqueue({locator:r.data.locator}));},
  'shared-job-result':reviewResult,
  'connector-access-lost':async el=>{const {job}=await C.sharedCall('job-result',{projectId:project().id,jobId:el.dataset.id});if(job.error_code!=='connector_access_lost')throw new Error('This is not an access-loss receipt.');const affected=project().sources.filter(s=>equal(s.origin?.locator,job.input?.locator));if(!affected.length)throw new Error('No matching retrieved source is retained.');modal('Mark retrieved context unavailable',affected.map(s=>`<p>${esc(s.title)}: future answers and approvals require available context.</p>`).join('')+submit('Record access loss'),async()=>{await commit(p=>{for(const s of affected)D.setSourceOrigin(p,s.id,{...s.origin,access:'lost',lastJobId:job.id});});notify('Unavailable source context flagged.');});},
  'connector-map-run':async el=>{const {job}=await C.sharedCall('job-result',{projectId:project().id,jobId:el.dataset.id}),o=job.output;if(job.status!=='review-required'||!o?.caseResults?.length)throw new Error('No actual case results returned.');const cases=L.list(project(),'cases').filter(r=>r.status==='approved'&&!r.archived);modal('Map actual retrieved case results',`<p>Build ${esc(o.build||'unknown')} · executed ${esc(o.executedAt||'unknown')}. ${o.caseResults.length} results; unmapped results cannot establish requirement coverage.</p>`+scopeFields()+member()+o.caseResults.map((r,i)=>`<section class="panel"><h3>${esc(r.title)} · ${esc(r.result)}</h3>${select('Exact approved case','case-'+i,[['','Unmapped'],...cases.map(c=>[c.id,c.title+' · r'+c.revision])])}<p>${esc(r.note)}</p></section>`).join('')+submit('Retain immutable actual results'),async f=>{await commit(p=>L.recordRun(p,{title:o.title,results:o.caseResults.map((r,i)=>({...r,caseId:f.get('case-'+i)})),build:o.build??'',releaseId:f.get('releaseId'),environmentId:f.get('environmentId'),origin:'provider-retrieved',externalId:o.externalId,artifactUrl:o.url,providerJobId:job.id,executedAt:o.executedAt??'',fingerprint:o.contentHash},f.get('memberId')));notify('Actual results retained with reviewed mappings.');});},
  'connector-map-deploy':async el=>{const {job}=await C.sharedCall('job-result',{projectId:project().id,jobId:el.dataset.id}),o=job.output;if(o?.type!=='deployment'||o.status!=='success')throw new Error('Successful provider deployment observation required.');modal('Map actual deployment observation',`<p>${esc(o.description)}</p>`+scopeFields()+select('Approved requirement reviewed against the observed manifest','requirementId',[['','No mapped agreement; behavior remains unknown'],...L.list(project(),'requirements').filter(r=>r.status==='approved').map(r=>[r.id,r.title])])+member()+submit('Retain deployment observation'),async f=>{await commit(p=>L.recordDeployment(p,{title:o.title,build:o.build,releaseId:f.get('releaseId'),environmentId:f.get('environmentId'),origin:'provider-retrieved',providerJobId:job.id,artifactUrl:o.url,providerObservedAt:o.observedAt,contextRefs:f.get('requirementId')?[L.reference(p,'requirements',f.get('requirementId'))]:[]},f.get('memberId')));});},
  'connector-media':el=>{const kind=el.dataset.kind,enqueue=enqueuer(kind);modal(kind==='ocr'?'Review image extraction consent':'Review audio transcription consent',`<label for="connector-media-file">Selected ${kind==='ocr'?'PNG/JPEG':'PCM WAV'} file</label><input id="connector-media-file" type="file" name="file" required accept="${kind==='ocr'?'.png,.jpg,.jpeg':'.wav'}"><p>At most 2 MB; images at most 20 million pixels; WAV clips at most two minutes. This sends original content to the configured OpenAI provider through your service and consumes its allowance.</p><label class="checkbox-label"><input type="checkbox" required><span>I authorize this selected file and will review extracted wording.</span></label>`+submit('Queue selected extraction'),async f=>{const file=f.get('file');if(file.size>2000000)throw new Error('Media limit: 2 MB.');const bytes=new Uint8Array(await file.arrayBuffer());validateMedia(bytes,kind);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));await enqueue({fileName:file.name,base64:btoa(binary)});});},
  'connector-write':el=>{const r=L.get(project(),'external',el.dataset.id),enqueue=enqueuer('connector-write');if(!r?.data.locator||r.data.locator.provider!=='github')throw new Error('Reviewed GitHub issue/PR reference required.');modal('Review external comment write',field('Exact comment to publish','body',changeContract(project(),'external',r.id,location.href),'textarea')+`<p>Target: ${esc(r.data.url)} · expected external revision ${esc(r.data.externalRevision)}. This publishes the reviewed comment to that issue/PR through the configured account. The server checks the external revision immediately before writing.</p><label class="checkbox-label"><input type="checkbox" required><span>Publish this exact comment to this target.</span></label>`+submit('Queue reviewed external comment'),f=>enqueue({externalRecordId:r.id,locator:r.data.locator,expectedRevision:r.data.externalRevision,body:f.get('body')}));},
  'connector-dispatch':async el=>{const r=L.get(project(),'external',el.dataset.id),{connectors}=await C.sharedCall('catalog',{projectId:project().id}),workflows=connectors.find(x=>x.provider==='github')?.workflows.filter(w=>w.testOnly&&w.repository===r?.data.locator?.repository)??[],enqueue=enqueuer('test-dispatch');modal('Authorize a configured test workflow',select('Administrator-selected test workflow','workflow',workflows.map((w,i)=>[String(i),w.repository+' · '+w.id]))+field('Allowed ref','ref',workflows[0]?.refs[0]??'')+field('Exact commit SHA expected at that ref','sha')+L.list(project(),'cases').filter(x=>x.status==='approved'&&!x.archived).map(x=>`<label class="checkbox-label"><input name="caseIds" type="checkbox" value="${x.id}"><span>Requested case scope: ${esc(x.title)} · r${x.revision}</span></label>`).join('')+field('Workflow inputs as JSON (relay_command_id is added by service)','inputs','{}','textarea')+`<p>Only test workflows explicitly configured by the administrator can be dispatched. Queue acceptance and dispatch acceptance do not mean tests ran or passed. Inspect the actual run afterward.</p><label class="checkbox-label"><input type="checkbox" required><span>Execute this configured test workflow for this exact ref and SHA.</span></label>`+submit('Queue reviewed test dispatch'),async f=>{const w=workflows[Number(f.get('workflow'))];if(!w)throw new Error('No configured test workflow matches this retrieved repository.');let inputs;try{inputs=JSON.parse(f.get('inputs'));}catch{throw new Error('Inputs must be a JSON object.');}await enqueue({externalRecordId:r.id,repository:w.repository,workflowId:w.id,ref:f.get('ref'),expectedSha:f.get('sha'),inputs,caseRefs:f.getAll('caseIds').map(id=>L.reference(project(),'cases',id))});});},
  'connector-correlate':async el=>{const {job}=await C.sharedCall('job-result',{projectId:project().id,jobId:el.dataset.id}),o=job.output;if(!o?.accepted)throw new Error('Dispatch receipt required.');const enqueue=enqueuer('connector-read');modal('Find the actual dispatched run',`<p>Find command ${esc(o.commandId)} in actual workflow run names. Configure run-name to include relay_command_id; no unique match remains unknown.</p>`+submit('Queue run correlation'),()=>enqueue({locator:{provider:'github',repository:o.repository,type:'dispatch',id:String(o.workflowId),commandId:o.commandId}}));}
 };return actions;
}
