import * as D from './domain.js';
import {ruleSummary} from './behavior-ui.js';

export function renderDelivery(p,context) {
  const {role,esc,badge,button,header,icon,date}=context;
  const relevant=a=>role==='Everyone'||a.role===role;
  const actions=(p.actions??[]).filter(relevant);
  const summary=D.reviewSummary(p);
  const rules=D.listBehaviors(p,{includeDrafts:false});
  const ownerName=id=>p.members.find(m=>m.id===id)?.name??'Unassigned';
  const verificationCards=(p.verifications??[]).filter(v=>role==='Everyone'||v.behaviorSnapshot.audiences.includes('Everyone')||v.behaviorSnapshot.audiences.includes(role)).slice().reverse();
  const needsReview=actions.filter(a=>{const state=D.actionReviewState(p,a);return state.needsReview||state.sourceNeedsReview;});
  const cards=actions.map(a=>{
    const state=D.actionReviewState(p,a),acknowledgments=(p.acknowledgments??[]).filter(receipt=>receipt.actionId===a.id);
    return `<article class="panel delivery-card"><div class="card-meta">${badge(a.role,'blue')}${badge(a.status,a.status==='completed'?'approved':a.status==='blocked'||a.status==='proposed'?'warning':'')}${state.needsReview?badge('Needs review','warning'):''}${state.sourceNeedsReview?badge('Source needs review','warning'):''}<span>Owner: ${esc(ownerName(a.ownerId))}</span></div><h2>${esc(a.title)}</h2><p class="muted">${esc(a.rationale)}</p><div class="delivery-scope"><strong>${esc(a.behaviorSnapshot.title)} · rule revision ${a.behaviorRevision}</strong><p><b>When:</b> ${esc(a.behaviorSnapshot.condition)}</p><p><b>Expected:</b> ${esc(a.behaviorSnapshot.outcome)}</p><p><b>Scope:</b> ${esc(a.behaviorSnapshot.applicability)}</p></div><h3>Completion criteria</h3><p class="prose">${esc(a.acceptanceCriteria)}</p>${state.reasons.map(reason=>`<p class="warning-banner">${esc(reason)}</p>`).join('')}<p class="small-note">${acknowledgments.length?`${acknowledgments.length} acknowledgment record(s).`:'No acknowledgment recorded.'} Acknowledgment, work completion, and verification are separate records.</p><div class="card-actions">${a.status==='proposed'?button('Edit & assign','edit-action',`data-id="${a.id}"`,'secondary')+button('Review scope','accept-action',`data-id="${a.id}" ${state.needsReview?'disabled':''}`,'primary'):button('Update work status','action-status',`data-id="${a.id}" ${state.rulesStale||state.archived?'disabled':''}`,'secondary')+button('Propose task update','propose-action',`data-id="${a.id}"`,'text-button')}${state.rulesStale?button('Review against current rule','rescope-action',`data-id="${a.id}"`,'primary'):''}${button('Acknowledge','ack-action',`data-id="${a.id}"`,'quiet')}${button('Record verification','verify-rule',`data-id="${a.behaviorId}"`,'text-button')}${button('Original context','action-context',`data-id="${a.id}"`,'text-button')}</div></article>`;
  }).join('');
  const pending=(p.actionChanges??[]).filter(c=>c.status==='pending'&&actions.some(a=>a.id===c.actionId));
  return header('TEAM FOLLOW-THROUGH','Delivery review','Review which teams need to act, assign the work, and keep checks tied to the agreed rule.',button(icon('plus')+' Plan team work','plan-work',rules.length&&p.members.length?'':'disabled','primary')+button('Export team handoff','export-delivery','','secondary'))+
    `<div class="metrics"><article><span>Proposed work</span><strong>${actions.filter(a=>a.status==='proposed').length}</strong><small>Needs scope review</small></article><article><span>Assigned work</span><strong>${actions.filter(a=>a.ownerId&&a.status!=='not-applicable').length}</strong><small>Owners recorded</small></article><article><span>Completed work</span><strong>${actions.filter(a=>a.status==='completed').length}</strong><small>Completion reported separately</small></article><article><span>Needs review</span><strong>${needsReview.length}</strong><small>Rule or source context changed</small></article></div>`+
    `<div class="note"><strong>Recorded by the team</strong><p>Names, acknowledgments, completion, and verification are self-reported in the project file. They help coordinate delivery; they are not authenticated sign-offs or a release-readiness score.</p></div>`+
    `<section class="delivery-section"><div class="section-heading"><h2>Work for ${role==='Everyone'?'the whole team':role}</h2>${badge(`${actions.length} action(s)`,'blue')}</div><div class="section-grid">${cards||'<div class="empty panel"><h2>Turn an agreement into clear team work</h2><p>Approve a product rule, add named teammates, then review its impact and choose relevant teams.</p></div>'}</div></section>`+
    (pending.length?`<section class="delivery-section"><h2>Task updates awaiting review</h2>${pending.map(c=>`<article class="panel change-card"><h3>${esc(c.proposed.title)}</h3><p class="muted">${esc(c.reason)}</p><p class="prose">${esc(c.proposed.acceptanceCriteria)}</p><div class="card-actions">${button('Review task update','accept-action-change',`data-id="${c.id}"`,'primary')}${button('Reject','reject-action-change',`data-id="${c.id}"`,'secondary')}</div></article>`).join('')}</section>`:'')+
    `<section class="delivery-section"><h2>Verification evidence</h2><div class="section-grid">${verificationCards.map(v=>{const state=D.verificationState(p,v);return `<article class="panel verification-card"><div class="card-meta">${badge(v.result,v.result==='pass'&&state.state==='applicable'?'approved':'warning')}${badge(state.state,state.state==='stale'?'warning':'')}${state.sourceNeedsReview?badge('Source needs review','warning'):''}<span>${date(v.at)}</span></div><h3>${esc(v.behaviorSnapshot.title)}</h3><p class="muted">Rule revision ${v.behaviorRevision} · ${esc(v.environment)} · ${esc(v.release)}</p><p class="small-note">Recorded by ${esc(ownerName(v.memberId))} · self-reported</p><p class="prose">${esc(v.note)}</p>${v.artifactUrl?`<a class="artifact-link" href="${esc(v.artifactUrl)}" target="_blank" rel="noopener noreferrer">Open supplied evidence</a>`:''}${state.reasons.map(reason=>`<p class="warning-banner">${esc(reason)}</p>`).join('')}</article>`;}).join('')||'<div class="empty panel"><p>No verification records yet. Work marked complete does not create a passed check.</p></div>'}</div></section>`+
    `<section class="delivery-section panel"><h2>What still needs attention</h2>${summary.missingWork.filter(item=>!item.actionId||actions.some(a=>a.id===item.actionId)).map(item=>`<div class="attention"><span class="dot amber"></span><div><strong>${esc(p.behaviors.find(b=>b.id===item.behaviorId)?.title??'Product rule')}</strong><p>${esc(item.reason)}</p></div></div>`).join('')||'<p class="muted">No missing-work indicators in this view. Review the scope and evidence before making a delivery decision.</p>'}</section>`;
}

export function actionFields(p,action,{field,esc,options}) {
  return field('Task title','title',action.title)+field('Completion criteria','acceptanceCriteria',action.acceptanceCriteria,'textarea')+field('Why this work is needed','rationale',action.rationale,'textarea')+`<label>Owner<select name="ownerId">${options([['','Unassigned'],...p.members.map(m=>[m.id,`${m.name} · ${m.role}`])],action.ownerId)}</select></label>`;
}
