import * as D from './domain.js';
import {captureStatement,resolveStatement} from './reconciliation.js';
export function completeDemoProject(){
 const p=D.demoProject(),maya=p.members.find(m=>m.name==='Maya'),alex=p.members.find(m=>m.name==='Alex'),sam=p.members.find(m=>m.name==='Sam');D.addMember(p,'Taylor','Operations');
 const transcript=D.addSource(p,'Walkthrough · fraud scope agreed for R2','For Release 2 onward, confirmed fraud cancellations revoke workspace access immediately. Ordinary cancellations still keep access until the paid billing period ends.','Walkthrough');
 const statement=captureStatement(p,{title:'Which release introduces the fraud exception?',sourceId:transcript.id,quote:transcript.revisions[0].content,role:'Product',owner:'Maya'});
 resolveStatement(p,statement.id,{reviewerId:maya.id,resolution:'Fictional owner decision: introduce the fraud exception in Release 2; ordinary cancellation is unchanged.',action:'keep'});
 const fraud=p.behaviors.find(b=>b.title==='Fraud cancellation exception');D.editBehavior(p,fraud.id,{...fraud,applicability:'Release 2 onward · confirmed fraud only',sourceId:transcript.id,quote:transcript.revisions[0].content,evidence:undefined});D.approveBehavior(p,fraud.id,'Fictional product decision from the walkthrough.');
 D.resolveQuestion(p,p.questions.find(q=>q.title.startsWith('Which release')).id,'Release 2 onward, confirmed fraud only. Fictional owner decision recorded in the walkthrough review.');
 const ordinary=p.behaviors.find(b=>b.title==='Ordinary cancellation');
 for(const behavior of [ordinary,fraud]){const review=D.confirmBehaviorImpact(p,behavior.id,{reviewerId:maya.id,roles:['Development','QA'],rationale:'Fictional impact review: implement and check this exact cancellation scope.'});const actions=D.proposeRoleActions(p,review.id,{ownerIds:{Development:sam.id,QA:alex.id}});for(const a of actions){D.acceptAction(p,a.id,{reviewerId:maya.id,note:'Fictional scope acceptance.'});D.acknowledgeAction(p,a.id,{memberId:a.ownerId,note:'Fictional acknowledgment, separate from testing.'});if(a.role==='QA')D.updateActionStatus(p,a.id,'completed',{memberId:alex.id,note:'Fictional demonstration only: team reports checking the stated cases.'});}D.recordVerification(p,behavior.id,{behaviorRevision:behavior.revision,memberId:alex.id,environment:'Fictional staging',release:behavior===ordinary?'Fictional R1 build':'Fictional R2 build',result:'pass',note:'Fictional evidence note for the demonstration. No real product tests were executed.'});}
 D.acceptChange(p,p.changes.find(c=>c.status==='pending').id,'Walkthrough clarification accepted in this fictional example.');D.saveVersion(p,'R2 agreement · before fraud handling changes',{includeActions:true});
 const source=D.addSource(p,'Fraud policy update · R3','From Release 3, confirmed fraud cancellations suspend access immediately and require a fraud operator review before permanent revocation. Ordinary cancellation behavior remains unchanged.','PRD');
 const proposal=D.proposeBehaviorChange(p,fraud.id,{...fraud,outcome:'Suspend access immediately; a fraud operator reviews the account before permanent revocation',applicability:'Release 3 onward · confirmed fraud only',evidence:undefined,sourceId:source.id,quote:source.revisions[0].content},'Fictional policy change: add an operator review for the fraud exception.');D.acceptBehaviorChange(p,proposal.id,'Fictional R3 decision; ordinary cancellations stay unchanged.');D.acknowledgeBehaviorChange(p,proposal.id,{memberId:maya.id,note:'Fictional PM receipt of the agreed change.'});
 return p;
}
