import * as L from './lifecycle.js';
import {seedTemplates} from './planning.js';
import * as D from './domain.js';
import {captureStatement,resolveStatement} from './reconciliation.js';
export function completeDemoProject(){
 const p=D.demoProject(),maya=p.members.find(m=>m.name==='Maya'),alex=p.members.find(m=>m.name==='Alex'),sam=p.members.find(m=>m.name==='Sam');D.addMember(p,'Taylor','Operations');
 const transcript=D.addSource(p,'Walkthrough · fraud scope agreed for R2','For Release 2 onward, confirmed fraud cancellations revoke workspace access immediately. Ordinary cancellations still keep access until the paid billing period ends.','Walkthrough');
 const statement=captureStatement(p,{title:'Which release introduces the fraud exception?',sourceId:transcript.id,quote:transcript.revisions[0].content,role:'Product',owner:'Maya'});
 resolveStatement(p,statement.id,{reviewerId:maya.id,resolution:'Fictional owner decision: introduce the fraud exception in Release 2; ordinary cancellation is unchanged.',action:'keep'});
 const fraud=p.behaviors.find(b=>b.title==='Fraud cancellation exception');D.editBehavior(p,fraud.id,{...fraud,applicability:'Release 2 onward · confirmed fraud only',sourceId:transcript.id,quote:transcript.revisions[0].content,evidence:undefined});D.approveBehavior(p,fraud.id,'Fictional product decision from the walkthrough.');
 D.resolveQuestion(p,p.questions.find(q=>q.title.startsWith('Which release')).id,'Release 2 onward, confirmed fraud only. Fictional owner decision recorded in the walkthrough review.');
 const ordinary=p.behaviors.find(b=>b.title==='Ordinary cancellation');
 for(const behavior of [ordinary,fraud]){const review=D.confirmBehaviorImpact(p,behavior.id,{reviewerId:maya.id,roles:['Development','QA'],rationale:'Fictional impact review: implement and check this exact cancellation scope.'});const actions=D.proposeRoleActions(p,review.id,{ownerIds:{Development:sam.id,QA:alex.id}});for(const a of actions){D.acceptAction(p,a.id,{reviewerId:maya.id,note:'Fictional scope acceptance.'});D.acknowledgeAction(p,a.id,{memberId:a.ownerId,note:'Fictional acknowledgment, separate from testing.'});if(a.role==='QA')D.updateActionStatus(p,a.id,'completed',{memberId:alex.id,note:'Fictional demonstration only: team reports checking the stated cases.'});}D.recordVerification(p,behavior.id,{behaviorRevision:behavior.revision,memberId:alex.id,environment:'Fictional staging',release:behavior===ordinary?'Fictional R1 build':'Fictional R2 build',result:'pass',note:'Fictional evidence note for the demonstration. No real product tests were executed.'});}
 D.acceptChange(p,p.changes.find(c=>c.status==='pending').id,'Walkthrough clarification accepted in this fictional example.');D.saveVersion(p,'R2 agreement · before fraud handling changes',{includeActions:true});
 const source=D.addSource(p,'Fraud policy update · R3','From Release 3, confirmed fraud cancellations suspend access immediately and require a fraud operator review before permanent revocation. Ordinary cancellation behavior remains unchanged.','PRD');
 const proposal=D.proposeBehaviorChange(p,fraud.id,{...fraud,outcome:'Suspend access immediately; a fraud operator reviews the account before permanent revocation',applicability:'Release 3 onward · confirmed fraud only',evidence:undefined,sourceId:source.id,quote:source.revisions[0].content},'Fictional policy change: add an operator review for the fraud exception.');D.acceptBehaviorChange(p,proposal.id,'Fictional R3 decision; ordinary cancellations stay unchanged.');D.acknowledgeBehaviorChange(p,proposal.id,{memberId:maya.id,note:'Fictional PM receipt of the agreed change.'});
 D.addMember(p,'Riley','BA');D.addMember(p,'Casey','Support');
 const ba=p.members.find(m=>m.role==='BA'),support=p.members.find(m=>m.role==='Support'),ops=p.members.find(m=>m.role==='Operations');
 const r2=L.addRecord(p,'releases',{title:'Fictional R2',status:'released',scope:{state:'general'},data:{description:'Demonstration only; no real product deployed'}},maya.id),r3=L.addRecord(p,'releases',{title:'Fictional R3',status:'planned',scope:{state:'general'}},maya.id),env=L.addRecord(p,'environments',{title:'Fictional staging',scope:{state:'general'},data:{description:'No actual tenant or live environment'}},ops.id);
 const sc={state:'specific',releaseIds:[r2.id],environmentIds:[env.id]},goal=L.addRecord(p,'objectives',{title:'Fictional goal: predictable cancellation boundaries',role:'Product',scope:sc,data:{description:'Reduce ambiguous handoffs while preserving fraud exceptions',measure:'Compare time and correction effort in the future pilot'}},maya.id);L.approveRecord(p,'objectives',goal.id,maya.id,'Fictional reviewed business intent.');
 const req=L.addRecord(p,'requirements',{title:'Fictional R2 ordinary cancellation',scope:sc,refs:[L.reference(p,'objectives',goal.id)],evidence:ordinary.evidence,data:{type:'behavior',actor:ordinary.actor,condition:ordinary.condition,outcome:ordinary.outcome,description:ordinary.applicability}},ba.id);L.approveRecord(p,'requirements',req.id,maya.id,'Fictional owner review: confirmed fraud is outside this ordinary case.');
 const comp=L.addRecord(p,'components',{title:'Fictional workspace authorization API',role:'Development',scope:sc,data:{description:'Check billing-period boundary and fraud handling independently',compatibility:'Old clients must retain the ordinary cancellation contract',migration:'No data migration established; clarify before rollout'}},sam.id);L.approveRecord(p,'components',comp.id,sam.id,'Fictional architecture review only.');L.addEdge(p,{from:L.reference(p,'components',comp.id),to:L.reference(p,'requirements',req.id),type:'implements',scope:sc,reason:'Fictional reviewed boundary dependency'},sam.id);
 const test=L.addRecord(p,'cases',{title:'Fictional ordinary cancellation retains paid access',role:'QA',scope:sc,refs:[L.reference(p,'requirements',req.id)],data:{steps:'Cancel an ordinary paid workspace before its billing period ends. Check the access boundary.',expected:'Access remains until the paid period ends; confirmed fraud is excluded.'}},alex.id);L.approveRecord(p,'cases',test.id,alex.id,'Fictional approved case, not an executed test.');
 L.recordRun(p,{title:'Fictional manual staging observation',build:'fictional-r2-build-001',releaseId:r2.id,environmentId:env.id,results:[{caseId:test.id,result:'pass',note:'Synthetic demonstration entry only. No actual test execution.'}]},alex.id);
 const handoff=L.proposeHandoffs(p,{kind:'requirements',id:req.id},maya.id,['Development','QA','Support','Operations']);for(const link of handoff.refs.filter(r=>r.kind==='work')){const work=L.get(p,'work',link.id),owner=p.members.find(m=>m.role===work.role);L.editRecord(p,'work',work.id,{ownerId:owner.id,status:'accepted',data:{criteria:work.role+': review the paid-period boundary and explicitly exclude confirmed fraud; retain actual implementation/check/brief/rollback observations separately.'}},owner.id,'Fictional concrete team acceptance.');if(work.role==='Development')L.acknowledge(p,work.id,owner.id,'Fictional owner receipt.');}
 const guidance=L.derivedGuidance(p,req.id,'Support',support.id);L.editRecord(p,'guidance',guidance.id,{data:{body:'Fictional Support guidance: ask whether cancellation is ordinary or confirmed fraud. Escalate unclear classification to the product owner.',escalationOwner:'Maya (fictional)',customerSafe:true}},support.id,'Fictional narrative review.');L.approveRecord(p,'guidance',guidance.id,support.id,'Fictional approved briefing with preserved ordinary/fraud distinction.');
 const runbook=L.derivedGuidance(p,req.id,'Operations',ops.id);L.editRecord(p,'guidance',runbook.id,{data:{body:'Fictional runbook: inspect the selected release/build and preserve access until the declared boundary.',rollbackCriteria:'Unknown measurable threshold: needs operator review',rollbackEvidence:'',monitorUrl:''}},ops.id,'Fictional operational draft with missing validation clearly exposed.');
 const incident=L.addRecord(p,'incidents',{title:'Fictional early-revocation report',role:'Support',scope:sc,refs:[L.reference(p,'requirements',req.id)],data:{observation:'Synthetic report: an ordinary workspace lost access early; cause not established',build:'fictional-r2-build-001'}},support.id);L.incidentFollowUp(p,incident.id,support.id,{question:'Fictional investigation: was this ordinary cancellation or confirmed fraud?',caseTitle:'Fictional draft regression: prevent early ordinary revocation',runbookTitle:'Fictional draft rollback follow-up'});
 L.addRecord(p,'glossary',{title:'Shared-file review rounds',status:'accepted',scope:{state:'general'},data:{term:'sharing round',aliases:['handoff reset','file reset','review round'],description:'Review expected returns before replacing the common starting point.'}},ba.id);
 seedTemplates(p,alex.id);L.ensure(p).masterOwnerId=maya.id;L.ensure(p).alternateOwnerId=ba.id;D.saveVersion(p,'Fictional Phase 2 delivery baseline',{includeActions:true});
 return p;
}
