import {canonical,equal} from './value.js';
import * as D from './domain.js';
import * as L from './lifecycle.js';
import {AI_LIMITS} from './ai.js';
const stop=new Set('what when where how why can does do the this that with from for are has have will would should product rule about tell please'.split(' '));
const terms=text=>[...new Set((text.toLowerCase().match(/[\p{L}\p{N}]+/gu)??[]).filter(w=>w.length>2&&!stop.has(w)).map(w=>w.replace(/(ations|ation|ing|ed|s)$/,'')))];
const same=(a,b)=>equal(a,b);
export function retrieveKnowledge(p,question,{versionId='',role='Everyone',mode='agreement',releaseId='',environmentId='',audience='',build='',flag=''}={}) {
  if(!question?.trim()||question.length>2000||!D.getRoles(p).includes(role)||!['agreement','sources','deployed'].includes(mode))throw new Error('Ask a product question of up to 2,000 characters.');
  const v=versionId?p.versions.find(v=>v.id===versionId):null;if(versionId&&!v)throw new Error('The selected baseline is unavailable.');
  const scope=v??p,scopedProject={...p,...scope,delivery:v?v.delivery:p.delivery},context={releaseId,environmentId,audience,build,flag};
  const words=terms(question);for(const g of L.list(scopedProject,'glossary').filter(g=>!g.archived&&g.status==='accepted'&&L.scopeMatch(g.scope,context)===true)){const aliases=[g.data.term??g.title,...g.data.aliases??[]];if(aliases.some(a=>terms(a).some(t=>words.includes(t))))for(const t of aliases.flatMap(terms))if(!words.includes(t))words.push(t);}
  const records=[...(scope.behaviors??[]).filter(b=>b.status==='approved'&&!b.archived&&(role==='Everyone'||b.audiences.some(a=>L.roleMatches(p,a,role)))).map(b=>({type:'rule',id:b.id,title:b.title,text:`Actor: ${b.actor}\nWhen: ${b.condition}\nOutcome: ${b.outcome}\nApplies to: ${b.applicability}`,record:b,applicability:versionId?true:null})),...scope.sections.filter(s=>s.status==='approved'&&!s.archived&&(L.roleMatches(p,s.role,role))).map(s=>({type:'section',id:s.id,title:s.title,text:s.body,record:s,applicability:versionId?true:null}))];
  records.push(...['requirements','guidance'].flatMap(kind=>L.list(scopedProject,kind).filter(r=>r.status==='approved'&&!r.archived&&L.roleMatches(p,r.role,role)&&L.scopeMatch(r.scope,context)!==false).map(r=>({type:kind==='requirements'?'requirement':'guidance',id:r.id,title:r.title,text:kind==='requirements'?L.requirementText(scopedProject,r):L.guidanceText(scopedProject,r),record:r,applicability:L.scopeMatch(r.scope,context)}))));
  let deploymentUnknown='';if(mode==='deployed'){records.length=0;const deployments=!v&&environmentId&&build?L.list(p,'deployments').filter(r=>!r.archived&&r.status==='deployed'&&r.data.build===build&&L.scopeMatch(r.scope,context)===true):[];const linked=new Map();for(const d of deployments)for(const l of d.refs.filter(l=>['requirements','guidance'].includes(l.kind))){const r=L.ref(p,l.kind,l.id,l.revision);if(r?.status==='approved'&&L.scopeMatch(r.scope,context)===true&&L.roleMatches(p,r.role,role))linked.set(l.kind+':'+l.id+':'+l.revision,{type:l.kind==='requirements'?'requirement':'guidance',id:r.id,title:r.title,text:(l.kind==='requirements'?L.requirementText(p,r):L.guidanceText(p,r))+'\nObserved deployment: '+d.title+' · '+d.data.origin+' · build '+d.data.build+'; agreement mapping is a recorded human review.',record:r,applicability:true});}records.push(...linked.values());if(!records.length)deploymentUnknown='Select an actual environment/build with explicit reviewed deployment-to-agreement references. Released intent alone does not establish observed deployed behavior.';}
  const sourceRecords=(v?[]:p.sources).filter(s=>!s.archived).flatMap(s=>{const revision=s.revisions.at(-1);return (revision.document?.blocks??[{id:'source-text',start:0,end:revision.content.length,location:{label:'Source text'}}]).map(block=>({type:'source passage',id:revision.id+':'+block.id,title:s.title+' · '+block.location.label,text:revision.content.slice(block.start,block.end),record:{id:s.id,evidence:[{sourceId:s.id,revisionId:revision.id,quote:revision.content.slice(block.start,Math.min(block.end,block.start+3000))}],ownerNote:''},applicability:null}));});
  const matches=(mode==='sources'?sourceRecords:records).map(item=>({...item,score:words.reduce((sum,w)=>sum+4*terms(item.title).filter(t=>t===w).length+terms(item.text).filter(t=>t===w).length,0),stale:Boolean((!v&&mode!=='deployed'&&(D.isStale(p,item.record)||(item.record.refs&&L.staleRefs(p,item.record).length>0)||(item.type==='guidance'&&L.guidanceNeedsReview(p,item.record))))||item.record.evidence.some(e=>p.sources.find(s=>s.id===e.sourceId)?.origin?.access==='lost')||(item.type==='guidance'&&item.record.data.reviewDate&&Date.parse(item.record.data.reviewDate)<Date.now()))})).filter(item=>item.score>=(words.length>1?2:1)).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,6);
  const questions=(scope.questions??[]).filter(q=>(L.roleMatches(p,q.role,role))&&terms(q.title+' '+q.resolution).some(w=>words.includes(w)));
  return {projectId:p.id,versionId,mode,releaseId,environmentId,audience,build,flag,baselineLabel:v?`Baseline v${v.number}: ${v.label}`:mode==='sources'?'Source exploration · interpretation is unapproved':mode==='deployed'?'Observed deployment context · explicit human mappings':'Current approved agreement',role,question,matches,questions,signature:canonical({mode,context,matches:matches.map(m=>({record:m.record,stale:m.stale,applicability:m.applicability??null})),questions}),unknowns:[...(deploymentUnknown?[deploymentUnknown]:[]),...(mode==='sources'?['Raw passages are source exploration. They do not override the reviewed agreement.']:[]),...(!matches.length?['No context matched these terms. Try reviewed product aliases or raise a question.']:[]),...(matches.some(m=>m.stale)?['Some agreements need review after their basis changed; they are excluded from AI answers.']:[]),...(matches.some(m=>m.applicability===null)?['Some scope qualifiers are unknown. Clarify release/environment/customer before relying on this as applicable guidance.']:[]),...(versionId&&mode==='sources'?['Source exploration is disabled for preserved baselines; use the exact baseline citations.']:[]),...questions.filter(q=>q.status==='open').map(q=>q.title)]};
}
export function knowledgeIsStale(p,context){if(p.id!==context.projectId)return true;try{return retrieveKnowledge(p,context.question,context).signature!==context.signature;}catch{return true;}}
export function answerPayload(p,context){if(context.mode==='sources')throw new Error('Source exploration is not an agreed answer. Review the interpretation first.');if(knowledgeIsStale(p,context))throw new Error('The selected agreement changed. Search again before asking AI.');const matches=context.matches.filter(m=>!m.stale&&m.record.evidence.length&&(m.applicability===true||!context.releaseId&&!context.environmentId&&!context.audience&&!context.build&&!context.flag));if(!matches.length)throw new Error('No current source-backed agreement is available for this question. Keep this as an unresolved question.');
 const groups=new Map();for(const match of matches)for(const e of match.record.evidence){const source=p.sources.find(s=>s.id===e.sourceId),revision=source?.revisions.find(r=>r.id===e.revisionId);if(source?.origin?.access==='lost'||!revision||!revision.content.includes(e.quote))throw new Error('Supporting evidence is unavailable.');const key=e.sourceId+':'+e.revisionId;let g=groups.get(key);if(!g){g={sourceId:e.sourceId,revisionId:e.revisionId,title:source.title,quotes:[]};groups.set(key,g);}if(!g.quotes.includes(e.quote))g.quotes.push(e.quote);}
 const sources=[...groups.values()].map(({quotes,...source})=>({...source,content:quotes.join('\n\n')}));if(sources.length>AI_LIMITS.sources||sources.some(s=>s.content.length>AI_LIMITS.sourceCharacters)||sources.reduce((sum,s)=>sum+s.content.length,0)>AI_LIMITS.contextCharacters)throw new Error('The relevant evidence exceeds one AI request. Use a narrower question.');
 return {sources,projectTitle:p.name,baselineLabel:(context.baselineLabel+' · '+JSON.stringify({releaseId:context.releaseId,environmentId:context.environmentId,audience:context.audience,build:context.build,flag:context.flag})).slice(0,200),question:context.question,answerContext:{role:context.role,selection:{versionId:context.versionId||'',releaseId:context.releaseId||'',environmentId:context.environmentId||'',audience:context.audience||'',build:context.build||'',flag:context.flag||'',mode:context.mode||'agreement'},agreements:matches.map(m=>({id:m.id,type:['requirement','rule'].includes(m.type)?'rule':'section',title:m.title,description:m.text+(m.record.scope?'\nExact scope: '+canonical(m.record.scope):''),evidence:m.record.evidence.map(({sourceId,revisionId,quote})=>({sourceId,revisionId,quote}))})),unknowns:context.unknowns.slice(0,12)}};
}
export function validateGroundedAnswer(p,context,output){if(knowledgeIsStale(p,context))throw new Error('The selected agreement changed while answering. Search again.');for(const e of output.evidence){if(!context.matches.some(m=>!m.stale&&m.record.evidence.some(ref=>ref.sourceId===e.sourceId&&ref.revisionId===e.revisionId&&ref.quote.includes(e.quote))))throw new Error('The answer cited text outside the selected approved evidence.');const revision=p.sources.find(s=>s.id===e.sourceId)?.revisions.find(r=>r.id===e.revisionId);if(!revision?.content.includes(e.quote))throw new Error('The answer quotation does not exist in the original source.');}return output;}
