import * as D from './domain.js';
import {AI_LIMITS} from './ai.js';
const stop=new Set('what when where how why can does do the this that with from for are has have will would should product rule about tell please'.split(' '));
const terms=text=>[...new Set((text.toLowerCase().match(/[\p{L}\p{N}]+/gu)??[]).filter(w=>w.length>2&&!stop.has(w)).map(w=>w.replace(/(ations|ation|ing|ed|s)$/,'')))];
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export function retrieveKnowledge(p,question,{versionId='',role='Everyone'}={}) {
  if(!question?.trim()||question.length>2000||!D.ROLES.includes(role))throw new Error('Ask a product question of up to 2,000 characters.');
  const v=versionId?p.versions.find(v=>v.id===versionId):null;if(versionId&&!v)throw new Error('The selected baseline is unavailable.');
  const words=terms(question),scope=v??p;
  const records=[...(scope.behaviors??[]).filter(b=>b.status==='approved'&&!b.archived&&(role==='Everyone'||b.audiences.includes('Everyone')||b.audiences.includes(role))).map(b=>({type:'rule',id:b.id,title:b.title,text:`Actor: ${b.actor}\nWhen: ${b.condition}\nOutcome: ${b.outcome}\nApplies to: ${b.applicability}`,record:b})),...scope.sections.filter(s=>s.status==='approved'&&!s.archived&&(role==='Everyone'||s.role==='Everyone'||s.role===role)).map(s=>({type:'section',id:s.id,title:s.title,text:s.body,record:s}))];
  const matches=records.map(item=>({...item,score:words.reduce((sum,w)=>sum+4*terms(item.title).filter(t=>t===w).length+terms(item.text).filter(t=>t===w).length,0),stale:!v&&D.isStale(p,item.record)})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,6);
  const questions=(scope.questions??[]).filter(q=>(role==='Everyone'||q.role==='Everyone'||q.role===role)&&terms(q.title+' '+q.resolution).some(w=>words.includes(w)));
  return {projectId:p.id,versionId,baselineLabel:v?`Baseline v${v.number}: ${v.label}`:'Current approved agreement',role,question,matches,questions,signature:JSON.stringify({matches:matches.map(m=>({record:m.record,stale:m.stale})),questions}),unknowns:[...(!matches.length?['No approved context matched these terms. Try the product vocabulary or raise a question.']:[]),...(matches.some(m=>m.stale)?['Some matching agreements need review after their source changed; they are excluded from AI answers.']:[]),...questions.filter(q=>q.status==='open').map(q=>q.title)]};
}
export function knowledgeIsStale(p,context){if(p.id!==context.projectId)return true;try{return retrieveKnowledge(p,context.question,context).signature!==context.signature;}catch{return true;}}
export function answerPayload(p,context){if(knowledgeIsStale(p,context))throw new Error('The selected agreement changed. Search again before asking AI.');const matches=context.matches.filter(m=>!m.stale&&m.record.evidence.length);if(!matches.length)throw new Error('No current source-backed agreement is available for this question. Keep this as an unresolved question.');
 const groups=new Map();for(const match of matches)for(const e of match.record.evidence){const source=p.sources.find(s=>s.id===e.sourceId),revision=source?.revisions.find(r=>r.id===e.revisionId);if(!revision||!revision.content.includes(e.quote))throw new Error('Supporting evidence is unavailable.');const key=e.sourceId+':'+e.revisionId;let g=groups.get(key);if(!g){g={sourceId:e.sourceId,revisionId:e.revisionId,title:source.title,quotes:[]};groups.set(key,g);}if(!g.quotes.includes(e.quote))g.quotes.push(e.quote);}
 const sources=[...groups.values()].map(({quotes,...source})=>({...source,content:quotes.join('\n\n')}));if(sources.length>AI_LIMITS.sources||sources.some(s=>s.content.length>AI_LIMITS.sourceCharacters)||sources.reduce((sum,s)=>sum+s.content.length,0)>AI_LIMITS.contextCharacters)throw new Error('The relevant evidence exceeds one AI request. Use a narrower question.');
 return {sources,projectTitle:p.name,baselineLabel:context.baselineLabel.slice(0,200),question:context.question,answerContext:{role:context.role,agreements:matches.map(m=>({id:m.id,type:m.type,title:m.title,description:m.text,evidence:m.record.evidence.map(({sourceId,revisionId,quote})=>({sourceId,revisionId,quote}))})),unknowns:context.unknowns.slice(0,12)}};
}
export function validateGroundedAnswer(p,context,output){if(knowledgeIsStale(p,context))throw new Error('The selected agreement changed while answering. Search again.');for(const e of output.evidence){if(!context.matches.some(m=>!m.stale&&m.record.evidence.some(ref=>ref.sourceId===e.sourceId&&ref.revisionId===e.revisionId&&ref.quote.includes(e.quote))))throw new Error('The answer cited text outside the selected approved evidence.');const revision=p.sources.find(s=>s.id===e.sourceId)?.revisions.find(r=>r.id===e.revisionId);if(!revision?.content.includes(e.quote))throw new Error('The answer quotation does not exist in the original source.');}return output;}
