import {canonical,equal,digest} from './value.js';
const uuid=()=>crypto.randomUUID(), now=()=>new Date().toISOString(), copy=v=>structuredClone(v);
export const FAMILIES=['roles','objectives','requirements','glossary','releases','environments','components','edges','work','cases','runs','defects','guidance','deployments','incidents','scenarios','carryForwards','returns','rounds','assets','external','subscriptions','exceptions','proposals','packages','templates'];
export const BASE_ROLES=['Everyone','Product','QA','Development','BA','Operations','Support'];
export const APPROVABLE=['requirements','cases','guidance','components','objectives','templates'];
const STATUSES=['draft','approved','planned','proposed','accepted','in-progress','blocked','completed','not-applicable','open','resolved','recorded','released','deployed','superseded','received','merged','withdrawn','pending','rejected'];
const EDGE_TYPES=['depends-on','constrains','implements','verifies','documents','affects-service','deploys','observed-against','exception-to','child-of','related'];
export function emptyLifecycle(){return {version:1,masterOwnerId:'',alternateOwnerId:'',familiesVersion:1,...Object.fromEntries(FAMILIES.map(k=>[k,[]]))};}
export const state=p=>p.delivery??emptyLifecycle();
export function ensure(p){return p.delivery??=emptyLifecycle();}
export function list(p,kind){if(!FAMILIES.includes(kind))throw new Error('Unknown delivery record type.');return state(p)[kind]??[];}
const indexes=new WeakMap();
function byId(rows,id){let entry=indexes.get(rows);if(!entry||entry.length!==rows.length){entry={length:rows.length,map:new Map(rows.map(r=>[r.id,r]))};indexes.set(rows,entry);}return entry.map.get(id);}
export function get(p,kind,id){return byId(list(p,kind),id);}
export function roleNames(p,{historical=true}={}){return [...new Set([...BASE_ROLES,...list(p,'roles').filter(r=>!r.archived||historical).flatMap(r=>[r.title,...(historical?r.data.aliases??[]:[])])])];}
export function roleId(p,label){const r=list(p,'roles').find(r=>r.id===label||r.title===label||r.data.aliases?.includes(label));return r?.id??label;}
export const roleMatches=(p,a,b)=>a==='Everyone'||b==='Everyone'||roleId(p,a)===roleId(p,b);
export function snapshot(record){const result=copy(record);delete result.history;return result;}
export function ref(p,kind,id,revision){if(kind==='behaviors'){const b=byId(p.behaviors??[],id);if(!b)return null;if(revision===undefined||b.revision===revision)return b;for(const d of p.decisions??[])for(const r of [d.before,d.after])if(r?.id===id&&r.revision===revision)return r;return null;}if(kind==='sources')return byId(p.sources,id);if(kind==='members')return byId(p.members,id);if(kind==='sections')return byId(p.sections,id);if(!FAMILIES.includes(kind))return null;const r=get(p,kind,id);if(!r)return null;if(revision===undefined||r.revision===revision)return r;return r.history?.find(h=>h.revision===revision)?.snapshot??null;}
export function reference(p,kind,id){const r=ref(p,kind,id);if(!r)throw new Error('Linked record is unavailable.');return {kind,id,...(r.revision?{revision:r.revision}:{})};}
export function scope(input={}){const unique=arr=>[...new Set(arr??[])];return {state:input.state??'unknown',releaseIds:unique(input.releaseIds),environmentIds:unique(input.environmentIds),audiences:unique(input.audiences),flags:unique(input.flags),exclusions:String(input.exclusions??'')};}
export function hasDeclaredScope(input){const s=scope(input),qualified=[s.releaseIds,s.environmentIds,s.audiences,s.flags].some(a=>a.length);return s.state==='general'&&!qualified||s.state==='specific'&&qualified;}
export function scopeMatch(s,context={}){s=scope(s);if(s.exclusions&&!context.confirmExclusions)return null;if(s.state==='unknown')return null;if(s.state==='general'&&![s.releaseIds,s.environmentIds,s.audiences,s.flags].some(a=>a.length))return true;if(s.state==='specific'&&![s.releaseIds,s.environmentIds,s.audiences,s.flags].some(a=>a.length))return null;let unknown=false;for(const [ids,key] of [[s.releaseIds,'releaseId'],[s.environmentIds,'environmentId'],[s.audiences,'audience'],[s.flags,'flag']])if(ids.length){if(!context[key])unknown=true;else if(!ids.includes(context[key]))return false;}return unknown?null:true;}
function actor(p,id){if(!p.members.some(m=>m.id===id))throw new Error('Choose a named teammate to record this decision.');return id;}
function remember(p,r,memberId,reason){r.history??=[];r.history.push({revision:r.revision,snapshot:snapshot(r),memberId:actor(p,memberId),reason:String(reason||'Recorded update'),at:now()});r.revision++;r.updatedAt=now();}
function event(p,text){p.events.push({id:uuid(),text,at:now()});}
export function addRecord(p,kind,input={},memberId){const s=ensure(p);if(!FAMILIES.includes(kind)||kind==='runs')throw new Error('Use the dedicated run recorder for results.');if(!input.title?.trim())throw new Error('Give this record a title.');const r={id:uuid(),kind,title:input.title.trim(),revision:1,status:APPROVABLE.includes(kind)?'draft':input.status??(kind==='work'?'proposed':kind==='releases'?'planned':'open'),ownerId:input.ownerId??'',role:input.role??'Everyone',scope:scope(input.scope),evidence:copy(input.evidence??[]),refs:copy(input.refs??[]),data:copy(input.data??{}),note:String(input.note??''),updatedAt:now(),history:[],archived:false};if(!STATUSES.includes(r.status))throw new Error('Unknown record status.');if(memberId)actor(p,memberId);s[kind].push(r);event(p,`Added ${kind}: ${r.title}`);return r;}
export function editRecord(p,kind,id,updates,memberId,reason,{external=false}={}){const r=get(p,kind,id);if(!r)throw new Error('Record unavailable.');if(kind==='runs')throw new Error('Runs are immutable. Record another run.');if(r.status==='approved'&&APPROVABLE.includes(kind))throw new Error('Propose a change to approved content.');if(!external&&r.data.externalOwnedFields?.some(key=>key==='description'?updates.data?.description!==undefined&&updates.data.description!==r.data.description:updates[key]!==undefined&&updates[key]!==r[key]))throw new Error('Status is owned by the external work system. Refresh that reference instead.');if(kind==='work'&&['accepted','completed'].includes(updates.status)){const owner=updates.ownerId??r.ownerId,criteria=updates.data?.criteria??r.data.criteria;if(!owner||!criteria?.trim()||!reason?.trim())throw new Error('Owned work acceptance/completion requires concrete criteria and a named recorded basis.');if(r.data.needsDetail&&criteria===r.data.criteria)throw new Error('Replace the proposed handoff checklist with concrete completion criteria before accepting.');updates={...updates,data:{...updates.data,needsDetail:false}};}remember(p,r,memberId,reason);for(const key of ['title','status','ownerId','role','note','archived'])if(updates[key]!==undefined)r[key]=updates[key];if(updates.scope)r.scope=scope(updates.scope);if(updates.data)r.data={...r.data,...copy(updates.data)};if(updates.evidence)r.evidence=copy(updates.evidence);if(updates.refs)r.refs=copy(updates.refs);event(p,`Updated ${kind}: ${r.title}`);return r;}
export function validMeasures(values){return Array.isArray(values)&&values.length>0&&values.length<=20&&new Set(values.map(m=>m.name)).size===values.length&&values.every(m=>m&&typeof m.name==='string'&&m.name.trim()&&m.name.length<=200&&typeof m.unit==='string'&&m.unit.trim()&&m.unit.length<=100&&['lte','gte','eq'].includes(m.operator)&&Number.isFinite(m.target));}
export function approveRecord(p,kind,id,memberId,note){const r=get(p,kind,id);if(!r||!APPROVABLE.includes(kind)||r.status!=='draft')throw new Error('Choose an approvable draft.');actor(p,memberId);if(!note?.trim())throw new Error('Record the source/owner basis and approval note.');if(kind==='cases'&&(!r.data.steps?.trim()||!r.data.expected?.trim()))throw new Error('Test-case approval requires steps and an observable expected outcome.');if((kind==='requirements'&&r.data.type==='NFR'||kind==='cases'&&r.refs.some(l=>l.kind==='requirements'&&ref(p,l.kind,l.id,l.revision)?.data.type==='NFR'))&&!validMeasures(r.data.acceptanceMeasures))throw new Error('NFR approval needs named measures, units, comparison operators and numerical thresholds.');if(!hasDeclaredScope(r.scope))throw new Error('Choose general applicability or declare specific scope before approval.');if(Array.isArray(r.data.unknowns)&&r.data.unknowns.length&&!r.data.unknownsResolution?.trim())throw new Error('Resolve or explicitly account for AI candidate unknowns before approval.');if(r.evidence.some(e=>{const s=p.sources.find(s=>s.id===e.sourceId);return !s||s.archived||s.origin?.access==='lost'||s.revisions.at(-1)?.id!==e.revisionId;})||staleRefs(p,r).length)throw new Error('Source evidence changed. Review it before approving.');remember(p,r,memberId,note);r.status='approved';r.approval={memberId,note:note.trim(),at:now(),identity:'self-reported'};event(p,`Approved ${kind}: ${r.title}`);return r;}
export function proposeRecord(p,kind,id,updates,memberId,reason){const target=get(p,kind,id);if(!target||!reason?.trim())throw new Error('Select existing content and explain the proposal.');actor(p,memberId);return addRecord(p,'proposals',{title:`Update ${target.title}`,status:'pending',ownerId:memberId,scope:target.scope,refs:[reference(p,kind,id)],data:{target:{kind,id},base:snapshot(target),updates:copy(updates)},note:reason},memberId);}
export function decideProposal(p,id,decision,memberId,note){const proposal=get(p,'proposals',id);if(!proposal||proposal.status!=='pending'||!['accepted','rejected'].includes(decision)||!note?.trim())throw new Error('Choose a pending proposal and record its decision.');const target=get(p,proposal.data.target.kind,proposal.data.target.id);if(!target||!equal(snapshot(target),proposal.data.base))throw new Error('The original content changed. Recreate the proposal.');if(decision==='accepted'){const changes=proposal.data.updates;if(APPROVABLE.includes(target.kind)){remember(p,target,memberId,note);target.status='draft';delete target.approval;}editRecord(p,target.kind,target.id,changes,memberId,note);if(APPROVABLE.includes(target.kind))approveRecord(p,target.kind,target.id,memberId,note);}editRecord(p,'proposals',id,{status:decision},memberId,note);return target;}
export function addRole(p,title,memberId){if(roleNames(p).includes(title.trim()))throw new Error('That perspective already exists.');return addRecord(p,'roles',{title,data:{aliases:[]}},memberId);}
export function renameRole(p,id,title,memberId){const r=get(p,'roles',id);if(!r||roleNames(p).includes(title.trim()))throw new Error('Choose a role and a distinct new name.');const old=r.title;editRecord(p,'roles',id,{title:title.trim(),data:{aliases:[...r.data.aliases,old]}},memberId,'Renamed perspective; historical label retained');for(const m of p.members)if(m.role===old)m.role=title.trim();return r;}
export function linkBehavior(p,id,scopeInput,memberId){const b=ref(p,'behaviors',id);if(!b||b.status!=='approved')throw new Error('Select an approved product rule.');if(list(p,'requirements').some(r=>r.data.behaviorId===id&&!r.archived))throw new Error('This rule is already linked.');return addRecord(p,'requirements',{title:b.title,ownerId:memberId,scope:scopeInput,refs:[reference(p,'behaviors',id)],evidence:b.evidence,data:{type:'behavior-reference',behaviorId:id,description:'Read the linked agreed rule; do not maintain another copy.'}},memberId);}
export function requirementText(p,r){const link=r.refs.find(l=>l.kind==='behaviors'&&l.id===r.data.behaviorId);const b=link&&ref(p,'behaviors',link.id,link.revision);return b?`${b.actor}\nWhen: ${b.condition}\nOutcome: ${b.outcome}\nApplies to: ${b.applicability}`:[r.data.description,r.data.actor&&'Actor: '+r.data.actor,r.data.condition&&'When: '+r.data.condition,r.data.outcome&&'Expected: '+r.data.outcome,r.data.measure&&'Measure: '+r.data.measure].filter(Boolean).join('\n');}
export function edgeAllowed(type,from,to){const contract={'child-of':[['requirements'],['requirements']],'exception-to':[['requirements'],['requirements']],verifies:[['cases','runs'],['requirements','components','cases']],implements:[['components','work'],['requirements','objectives']],documents:[['guidance','sections'],['requirements','components','incidents','deployments','releases']],deploys:[['deployments'],['releases','components']],'observed-against':[['incidents','defects','runs'],['deployments','requirements','cases','releases','components']],'affects-service':[['requirements','incidents','defects'],['components']]};return !contract[type]||contract[type][0].includes(from.kind)&&contract[type][1].includes(to.kind);}
export function addEdge(p,{from,to,type,scope:sc,reason},memberId){if(!EDGE_TYPES.includes(type)||!edgeAllowed(type,from,to)||!ref(p,from.kind,from.id,from.revision)||!ref(p,to.kind,to.id,to.revision)||!reason?.trim())throw new Error('Choose valid endpoints, a relationship and its review basis.');if(from.kind===to.kind&&from.id===to.id)throw new Error('A record cannot depend on itself.');if(type==='child-of'){const visited=new Set(),queue=[to];while(queue.length){const n=queue.shift(),key=n.kind+':'+n.id;if(key===from.kind+':'+from.id)throw new Error('This would create a requirement hierarchy cycle.');if(visited.has(key))continue;visited.add(key);for(const e of list(p,'edges').filter(e=>!e.archived&&e.data.type==='child-of'&&e.data.from.kind===n.kind&&e.data.from.id===n.id))queue.push(e.data.to);}}return addRecord(p,'edges',{title:`${ref(p,from.kind,from.id).title} → ${ref(p,to.kind,to.id).title}`,scope:sc,status:'accepted',refs:[from,to],data:{from,to,type},note:reason},memberId);}
export function impact(p,subject,context={}){
 const implicit=['cases','guidance','work'].flatMap(kind=>list(p,kind).filter(r=>!r.archived&&['approved','accepted','completed'].includes(r.status)).flatMap(r=>r.refs.map(link=>({id:'reference:'+r.id+':'+link.id,status:'accepted',archived:false,scope:r.scope,data:{from:reference(p,kind,r.id),to:link,type:kind==='cases'?'verifies':kind==='guidance'?'documents':'implements'}})))),adjacency=new Map();
 for(const edge of [...list(p,'edges'),...implicit]){if(edge.archived||edge.status!=='accepted'||scopeMatch(edge.scope,context)===false)continue;const {from,to,type}=edge.data,upstream=['depends-on','verifies','documents','implements','observed-against','child-of','exception-to'].includes(type)?to:from,downstream=upstream===to?from:to,key=upstream.kind+':'+upstream.id;if(!adjacency.has(key))adjacency.set(key,[]);adjacency.get(key).push({edge,downstream});}
 const queue=[{ref:subject,path:[]}],visited=new Set(),items=[];let head=0;
 while(head<queue.length&&visited.size<2000){const node=queue[head++],key=node.ref.kind+':'+node.ref.id;if(visited.has(key))continue;visited.add(key);if(node.path.length){const revisionsCurrent=node.path.every(e=>[e.data.from,e.data.to].every(l=>l.revision===undefined||ref(p,l.kind,l.id)?.revision===l.revision));items.push({...node,record:ref(p,node.ref.kind,node.ref.id),confidence:!revisionsCurrent?'recorded path; linked revision needs review':node.path.every(e=>scopeMatch(e.scope,context)===true)?'recorded applicable path':'scope needs review'});}for(const {edge,downstream}of adjacency.get(key)??[])if(!visited.has(downstream.kind+':'+downstream.id))queue.push({ref:downstream,path:[...node.path,edge]});}
 return {items,unknowns:['Only recorded reviewed relationships are traversed. Unrecorded impacts remain unknown.',...(visited.size>=2000?['Impact traversal reached its supported bound.']:[])]};
}
export async function rehearse(p,subject,updates,memberId,reason){const original=ref(p,subject.kind,subject.id);if(!original||!reason?.trim())throw new Error('Select a record and explain the alternative.');return addRecord(p,'scenarios',{title:`Rehearsal: ${original.title}`,status:'proposed',ownerId:memberId,scope:original.scope,refs:[reference(p,subject.kind,subject.id)],data:{subject,base:snapshot(original),baseHash:await digest(snapshot(original)),updates:copy(updates)},note:reason},memberId);}
export async function acceptScenario(p,id,memberId,note,legacyPropose){const s=get(p,'scenarios',id),r=s&&ref(p,s.data.subject.kind,s.data.subject.id);if(!s||s.status!=='proposed'||!r||await digest(snapshot(r))!==s.data.baseHash)throw new Error('Scenario base changed; rehearse again.');const proposal=s.data.subject.kind==='behaviors'?(legacyPropose?legacyPropose(p,r,s.data.updates,note):(()=>{throw new Error('Use the product-rule proposal adapter for this rehearsal.');})()):proposeRecord(p,s.data.subject.kind,r.id,s.data.updates,memberId,note);editRecord(p,'scenarios',id,{status:'accepted',data:{proposalId:proposal.id}},memberId,note);return proposal;}
export function proposeHandoffs(p,subject,memberId,roles,context={}){if(!roles.length)throw new Error('Explicitly choose relevant roles.');const record=ref(p,subject.kind,subject.id),paths=impact(p,subject,context);const tasks=roles.map(role=>addRecord(p,'work',{title:`${role}: review ${record.title}`,ownerId:'',role,scope:record.scope,refs:[reference(p,subject.kind,subject.id)],data:{needsDetail:true,criteria:`Confirm relevant conditions, exclusions and acceptance criteria for ${record.title}.\nRecord concrete implementation/check/guidance obligations; unknown impact stays open.`,dependencyPaths:paths.items.map(i=>i.ref),acknowledgments:[]},note:'Proposed handoff; each team reviews its own scope'},memberId));return addRecord(p,'packages',{title:`Team handoff: ${record.title}`,status:'proposed',refs:[reference(p,subject.kind,subject.id),...tasks.map(t=>reference(p,'work',t.id))],data:{roles,unknowns:paths.unknowns}},memberId);}
export function currentReceipt(r){return (r.data.acknowledgments??[]).find(a=>a.memberId===r.ownerId&&a.scopeHash===canonical({ownerId:r.ownerId,role:r.role,scope:r.scope,refs:r.refs,criteria:r.data.criteria??''}));}
export function acknowledge(p,id,memberId,note){const r=get(p,'work',id);if(!r||r.ownerId!==memberId)throw new Error('Only the recorded owner can acknowledge their current work scope.');const receipt={id:uuid(),memberId,revision:r.revision,scopeHash:canonical({ownerId:r.ownerId,role:r.role,scope:r.scope,refs:r.refs,criteria:r.data.criteria??''}),context:copy(r.refs),note:String(note??''),at:now(),identity:'self-reported'};r.data.acknowledgments??=[];r.data.acknowledgments.push(receipt);event(p,`Recorded owner receipt: ${r.title}`);return receipt;}
export function sourceNeedsReview(p,r){return r.evidence.some(e=>{const s=p.sources.find(s=>s.id===e.sourceId);return !s||s.archived||s.origin?.access==='lost'||s.revisions.at(-1).id!==e.revisionId;});}
export function guidanceNeedsReview(p,r){return staleRefs(p,r).length>0||sourceNeedsReview(p,r)||Boolean(r.data.reviewDate&&Date.parse(r.data.reviewDate)<Date.now());}
export function staleRefs(p,r){return r.refs.filter(link=>{const current=ref(p,link.kind,link.id);return !current||current.archived||(link.revision!==undefined&&current.revision!==link.revision);});}
export function derivedGuidance(p,requirementId,role,memberId){const r=get(p,'requirements',requirementId);if(!r||r.status!=='approved')throw new Error('Approve the requirement first.');return addRecord(p,'guidance',{title:`${role} brief: ${r.title}`,role,scope:r.scope,refs:[reference(p,'requirements',r.id)],evidence:r.evidence,data:{type:role==='Operations'?'runbook':'brief',derived:true,body:'',customerSafe:false},note:'Derived facts stay linked; review any narrative override'},memberId);}
export function guidanceText(p,r){return [r.data.body,...r.refs.filter(l=>l.kind==='requirements').map(l=>{const req=ref(p,l.kind,l.id,l.revision);return req?requirementText(p,req):'Referenced requirement unavailable';})].filter(Boolean).join('\n\n');}
export function recordRun(p,{title,caseIds,results,releaseId='',environmentId='',build='',origin='self-reported',fingerprint='',externalId='',artifactUrl='',providerJobId='',executedAt='',executionTimeOrigin=''},memberId){actor(p,memberId);if(!title?.trim()||!Array.isArray(results)||!results.length||results.length>5000||!['self-reported','file-import','provider-retrieved'].includes(origin))throw new Error('A run needs bounded actual results and their origin.');if(fingerprint&&list(p,'runs').some(r=>r.data.fingerprint===fingerprint&&r.data.releaseId===releaseId&&r.data.environmentId===environmentId))throw new Error('That report was already imported for this scope.');const mapped=results.map(result=>{const c=result.caseId?ref(p,'cases',result.caseId,result.caseRevision):null;if(result.caseId&&(!c||c.status!=='approved'))throw new Error('Map results to approved cases only.');if(!['pass','fail','blocked','not-run','inconclusive'].includes(result.result))throw new Error('Invalid test result.');return {caseId:c?.id??'',caseRevision:c?.revision??0,requirementRefs:copy(c?.refs??[]),result:result.result,note:String(result.note??''),title:result.title??c?.title??'Unmapped result',measurements:copy(result.measurements??[])};});if(!executedAt&&origin==='self-reported')executedAt=now();if(executedAt&&(!Number.isFinite(Date.parse(executedAt))||Date.parse(executedAt)>Date.now()+300000))throw new Error('Record a valid actual execution time.');const r={id:uuid(),kind:'runs',title:title.trim(),revision:1,status:'recorded',ownerId:memberId,role:'QA',scope:scope({state:releaseId||environmentId?'specific':'unknown',releaseIds:releaseId?[releaseId]:[],environmentIds:environmentId?[environmentId]:[]}),evidence:[],refs:[...new Map(mapped.filter(r=>r.caseId).map(r=>[r.caseId+':'+r.caseRevision,{kind:'cases',id:r.caseId,revision:r.caseRevision}])).values()],data:{results:mapped,releaseId,environmentId,build,origin,fingerprint,externalId,artifactUrl,providerJobId,executedAt,executionTimeOrigin:executionTimeOrigin|| (origin==='provider-retrieved'?'provider-retrieved':'self-reported')},note:'Recorded results do not imply broader coverage.',updatedAt:now(),history:[],archived:false};ensure(p).runs.push(r);event(p,`Recorded ${origin} run: ${r.title}`);return r;}
export function evidenceMatrix(p,context={}) {
  const caseIndex=new Map(list(p,'cases').map(c=>[c.id,c])),casesByRequirement=new Map(),resultsByRequirement=new Map(),carryByResult=new Map();
  for(const c of caseIndex.values())if(!c.archived&&scopeMatch(c.scope,context)!==false)for(const l of c.refs.filter(l=>l.kind==='requirements')){if(!casesByRequirement.has(l.id))casesByRequirement.set(l.id,[]);casesByRequirement.get(l.id).push(c);}
  for(const run of list(p,'runs').filter(r=>!r.archived))for(const result of run.data.results)for(const l of result.requirementRefs.filter(l=>l.kind==='requirements')){if(!resultsByRequirement.has(l.id))resultsByRequirement.set(l.id,[]);resultsByRequirement.get(l.id).push({run,result});}
  for(const c of list(p,'carryForwards').filter(c=>!c.archived)){const key=c.data.runId+':'+c.data.caseId+':'+c.data.requirementId;if(!carryByResult.has(key))carryByResult.set(key,[]);carryByResult.get(key).push(c);}
  return list(p,'requirements').filter(r=>r.status==='approved'&&!r.archived&&scopeMatch(r.scope,context)!==false).map(req=>{
    const cases=casesByRequirement.get(req.id)??[];
    const results=(resultsByRequirement.get(req.id)??[]).map(({run,result})=>{
      const latestCase=caseIndex.get(result.caseId),old=result.requirementRefs.find(l=>l.kind==='requirements'&&l.id===req.id);
      const carry=(carryByResult.get(run.id+':'+result.caseId+':'+req.id)??[]).find(c=>c.data.runId===run.id&&c.data.caseId===result.caseId&&c.data.requirementId===req.id&&c.data.fromRevision===old.revision&&c.data.toRevision===req.revision&&equal(c.data.reviewedScope,req.scope)&&c.data.toCaseRevision===latestCase?.revision&&!c.archived);
      let applicability=!run.data.executedAt?'execution time unknown':Date.parse(run.data.executedAt)<Date.parse(req.approval?.at)||Date.parse(run.data.executedAt)<Date.parse(latestCase?.approval?.at)?'predates approved expectation':scopeMatch(req.scope,context)===null||scopeMatch(run.scope,context)===null||scopeMatch(latestCase?.scope,context)===null?'scope unknown':scopeMatch(run.scope,context)===false?'other scope':!context.build||!run.data.build?'build unknown':run.data.build!==context.build?'other build':old.revision!==req.revision||latestCase?.revision!==result.caseRevision||latestCase?.status!=='approved'?'stale':'current';
      if(applicability==='current'&&latestCase?.data.acceptanceMeasures?.length){const measures=latestCase.data.acceptanceMeasures,actual=result.measurements??[];if(measures.some(m=>!actual.some(a=>a.name===m.name&&a.unit===m.unit&&Number.isFinite(a.value))))applicability='measurements missing';else if(result.result==='pass'&&measures.some(m=>{const value=actual.find(a=>a.name===m.name&&a.unit===m.unit).value;return m.operator==='lte'?value>m.target:m.operator==='gte'?value<m.target:value!==m.target;}))applicability='recorded outcome conflicts with measures';}
      if(carry&&['stale','other scope','other build','predates approved expectation'].includes(applicability)&&scopeMatch(carry.scope,context)===true&&carry.data.reviewedBuild===context.build)applicability='reviewed carry-forward';
      return {run,result,applicability,origin:run.data.origin};
    });
    const caseStates=cases.map(c=>{const applicable=results.filter(x=>x.result.caseId===c.id&&x.applicability==='current'),lastTime=Math.max(...applicable.map(x=>Date.parse(x.run.data.executedAt))),current=applicable.filter(x=>Date.parse(x.run.data.executedAt)===lastTime);return {case:c,state:c.status!=='approved'?'draft case':staleRefs(p,c).length||sourceNeedsReview(p,c)?'case needs review':scopeMatch(c.scope,context)===null?'scope unknown':!current.length?'missing current result':current.some(x=>x.result.result==='fail')?'failed':current.some(x=>['blocked','inconclusive'].includes(x.result.result))?'blocked or inconclusive':current.some(x=>x.result.result==='pass')?'pass recorded':'not run'};});
    const state=sourceNeedsReview(p,req)||staleRefs(p,req).length?'agreement needs review':!cases.length?'missing cases':caseStates.some(x=>x.state==='failed')?'failed':caseStates.every(x=>x.state==='pass recorded')?'has current evidence':caseStates.some(x=>x.state==='pass recorded')?'partial current evidence':results.some(x=>x.applicability==='reviewed carry-forward')?'carry-forward reviewed':'needs review';
    return {requirement:req,cases,caseStates,results,state};
  });
}
export function carryForward(p,{runId,caseId,requirementId,reason,context={}},memberId){const run=get(p,'runs',runId),req=get(p,'requirements',requirementId),result=run?.data.results.find(x=>x.caseId===caseId),old=result?.requirementRefs.find(l=>l.kind==='requirements'&&l.id===requirementId);if(!run||!req||!old||!reason?.trim())throw new Error('Choose an actual case result and explain why its exact scope still applies.');return addRecord(p,'carryForwards',{title:`Applicability review: ${req.title}`,status:'accepted',scope:req.scope,refs:[reference(p,'runs',runId),reference(p,'requirements',requirementId)],data:{runId,caseId,requirementId,fromRevision:old.revision,toRevision:req.revision,toCaseRevision:get(p,'cases',caseId)?.revision,reviewedBuild:context.build??'',originalRunScope:copy(run.scope),reviewedScope:copy(req.scope)},note:reason},memberId);}
export function obligations(p,context={}){const issues=[];for(const r of list(p,'work').filter(r=>!r.archived&&scopeMatch(r.scope,context)!==false)){if(scopeMatch(r.scope,context)===null)issues.push({record:r,reason:'Work applicability is unknown'});if(r.ownerId&&!currentReceipt(r))issues.push({record:r,reason:'Current owner receipt missing'});if(!['completed','not-applicable'].includes(r.status))issues.push({record:r,reason:'Work remains '+r.status});if(staleRefs(p,r).length)issues.push({record:r,reason:'Underlying agreement changed'});}for(const row of evidenceMatrix(p,context))if(row.state!=='has current evidence')issues.push({record:row.requirement,reason:row.state});for(const r of list(p,'guidance').filter(r=>!r.archived&&scopeMatch(r.scope,context)!==false))if(r.status!=='approved'||guidanceNeedsReview(p,r))issues.push({record:r,reason:'Guidance needs review'});for(const r of list(p,'exceptions').filter(r=>!r.archived&&scopeMatch(r.scope,context)!==false))issues.push({record:r,reason:r.status==='accepted'?'Accepted risk remains: '+(r.data.description||r.note)+(r.data.expiresAt&&Date.parse(r.data.expiresAt)<=Date.now()?' · review expired':''):'Risk exception needs explicit owner acceptance'});for(const r of list(p,'guidance').filter(r=>!r.archived&&r.role==='Operations'&&scopeMatch(r.scope,context)!==false))if(!r.data.monitorUrl||!r.data.rollbackCriteria||!r.data.rollbackEvidence)issues.push({record:r,reason:'Operational monitoring / rollback evidence is incomplete'});for(const q of p.questions??[])if(q.status==='open')issues.push({record:q,reason:'Unresolved question'});return issues;}
export function recordDeployment(p,input,memberId){if(!input.releaseId||!input.environmentId||!get(p,'releases',input.releaseId)||!get(p,'environments',input.environmentId)||!input.build?.trim())throw new Error('Select a release, environment and actual build.');return addRecord(p,'deployments',{title:input.title||`${get(p,'releases',input.releaseId).title} deployment`,status:'deployed',ownerId:memberId,scope:{state:'specific',releaseIds:[input.releaseId],environmentIds:[input.environmentId],audiences:input.audiences??[],flags:input.flags??[]},refs:[reference(p,'releases',input.releaseId),reference(p,'environments',input.environmentId),...(input.contextRefs??[])],data:{...input,origin:input.origin??'self-reported',observedAt:now()}},memberId);}
export function incidentFollowUp(p,id,memberId,{question,caseTitle,runbookTitle}){const incident=get(p,'incidents',id);if(!incident)throw new Error('Select an incident.');const refs=[reference(p,'incidents',id),...incident.refs];const follow=[];if(question){const q={id:uuid(),title:question,role:'Product',owner:p.members.find(m=>m.id===memberId).name,status:'open',resolution:'',at:now()};p.questions.push(q);follow.push(q);}if(caseTitle)follow.push(addRecord(p,'cases',{title:caseTitle,scope:incident.scope,refs,data:{steps:incident.data.observation||incident.note,expected:'Clarify expected outcome from the linked agreement before approval'}},memberId));if(runbookTitle)follow.push(addRecord(p,'guidance',{title:runbookTitle,role:'Operations',scope:incident.scope,refs,data:{type:'runbook',body:'Review the observed incident and define prevention/rollback checks.',customerSafe:false}},memberId));event(p,`Triaged incident ${incident.title}; causes remain hypotheses`);return follow;}
export function changedSince(p,cursor){const current=new Map(FAMILIES.flatMap(kind=>list(p,kind).map(r=>[kind+':'+r.id,{kind,id:r.id,revision:r.revision,title:r.title}])));return [...current.entries()].filter(([key,r])=>cursor?.[key]!==r.revision).map(([,r])=>({...r,change:cursor?.[r.kind+':'+r.id]?'updated':'new'}));}
export function viewCursor(p){return Object.fromEntries(FAMILIES.flatMap(kind=>list(p,kind).map(r=>[kind+':'+r.id,r.revision])));}
export function capacity(p){const bytes=v=>new TextEncoder().encode(JSON.stringify(v)).byteLength;return {activeBytes:bytes({...p,sharing:undefined,mergeArchives:undefined}),baseBytes:bytes(p.sharing?.base??null),archiveBytes:bytes(p.mergeArchives??[]),assetBytes:list(p,'assets').reduce((n,r)=>n+(r.data.byteLength??0),0),totalBytes:bytes(p),limit:10000000,archives:(p.mergeArchives??[]).length};}
export async function retainAsset(p,file,memberId){if(file.size>2000000)throw new Error('Original attachments are limited to 2 MB each in portable mode.');if(list(p,'assets').filter(r=>!r.data.remote).reduce((n,r)=>n+r.data.byteLength,0)+file.size>6000000)throw new Error('Portable originals have a 6 MB total budget.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');if(list(p,'assets').some(r=>r.data.hash===hash))throw new Error('This original is already retained.');return addRecord(p,'assets',{title:file.name,status:'recorded',data:{fileName:file.name,mediaType:file.type,byteLength:file.size,hash,base64:btoa(binary)}},memberId);}
export function readingPack(p,{role='Support',context={},ids=[]}){const selected=list(p,'guidance').filter(r=>ids.includes(r.id)&&r.status==='approved'&&!r.archived&&r.data.customerSafe===true&&scopeMatch(r.scope,context)===true&&roleMatches(p,r.role,role)&&!guidanceNeedsReview(p,r));if(!selected.length)throw new Error('Select approved customer-safe guidance with a known applicable scope.');return {format:'product-relay-reading-pack',version:1,projectLabel:p.name,createdAt:now(),context:copy(context),items:selected.map(r=>({title:r.title,body:guidanceText(p,r),scope:copy(r.scope),revision:r.revision}))};}
export function validateLifecycle(p,{identifier,timestamp,validateEvidence}) {
  if(p.delivery===undefined)return undefined;
  const s=p.delivery,member=id=>typeof id==='string'&&(!id||p.members.some(m=>m.id===id));
  if(!s||s.version!==1||s.familiesVersion!==1||FAMILIES.some(k=>!Array.isArray(s[k])||s[k].length>5000))throw new Error('Invalid delivery workspace.');
  const ids=new Set(),names=roleNames(p),text=(v,max=20000)=>typeof v==='string'&&v.length<=max;
  const linkCheck=link=>{if(!link||typeof link.kind!=='string'||!identifier(link.id)||(link.revision!==undefined&&(!Number.isSafeInteger(link.revision)||link.revision<1))||!ref(p,link.kind,link.id,link.revision))throw new Error('Unknown or malformed linked delivery revision.');};
  function validateScope(sc){if(!sc||!['unknown','general','specific'].includes(sc.state)||['releaseIds','environmentIds','audiences','flags'].some(k=>!Array.isArray(sc[k])||sc[k].length>100||sc[k].some(v=>!text(v,300))||new Set(sc[k]).size!==sc[k].length)||!text(sc.exclusions))throw new Error('Invalid applicability.');if(sc.state==='general'&&[sc.releaseIds,sc.environmentIds,sc.audiences,sc.flags].some(a=>a.length))throw new Error('General applicability cannot hide specific qualifiers. Choose Specific scope.');for(const id of sc.releaseIds)if(!get(p,'releases',id))throw new Error('Unknown release scope.');for(const id of sc.environmentIds)if(!get(p,'environments',id))throw new Error('Unknown environment scope.');}
  function recordShape(r,kind){if(!r||!identifier(r.id)||r.kind!==kind||!text(r.title,2000)||!r.title.trim()||!Number.isSafeInteger(r.revision)||r.revision<1||!STATUSES.includes(r.status)||!member(r.ownerId)||!names.includes(r.role)||!timestamp(r.updatedAt)||typeof r.archived!=='boolean'||!text(r.note)||!r.data||typeof r.data!=='object'||Array.isArray(r.data)||!Array.isArray(r.refs)||r.refs.length>1000)throw new Error('Invalid '+kind+' record.');validateEvidence(r.evidence);validateScope(r.scope);r.refs.forEach(linkCheck);if(r.status==='approved'&&APPROVABLE.includes(kind)&&(!r.approval||!identifier(r.approval.memberId)||!member(r.approval.memberId)||!text(r.approval.note)||!r.approval.note.trim()||!timestamp(r.approval.at)||!['self-reported','authenticated'].includes(r.approval.identity)))throw new Error('Approved context needs a named review basis.');if(r.status==='approved'&&APPROVABLE.includes(kind)&&!hasDeclaredScope(r.scope))throw new Error('Approved context needs declared applicability.');}
  for(const kind of FAMILIES)for(const r of s[kind]){
    if(ids.has(r.id))throw new Error('Duplicate delivery ID.');ids.add(r.id);recordShape(r,kind);
    if(!Array.isArray(r.history)||r.history.length>1000||r.history.length!==r.revision-1)throw new Error('Delivery history must preserve every revision.');
    r.history.forEach((h,i)=>{if(h.revision!==i+1||h.snapshot?.id!==r.id||h.snapshot?.revision!==h.revision||!member(h.memberId)||!identifier(h.memberId)||!timestamp(h.at)||!text(h.reason)||Object.hasOwn(h.snapshot,'history'))throw new Error('Invalid immutable delivery history.');recordShape(h.snapshot,kind);});
    if(r.data.acceptanceMeasures!==undefined&&(!Array.isArray(r.data.acceptanceMeasures)||r.data.acceptanceMeasures.length&&!validMeasures(r.data.acceptanceMeasures)))throw new Error('Invalid acceptance measures.');
    if(kind==='requirements'&&r.data.type&&!['behavior','constraint','NFR','exception','behavior-reference'].includes(r.data.type))throw new Error('Invalid requirement type.');
    if(kind==='edges') {const {from,to,type}=r.data;if(!EDGE_TYPES.includes(type)||!from||!to||!edgeAllowed(type,from,to)||from.kind===to.kind&&from.id===to.id||!r.note.trim())throw new Error('Invalid reviewed relationship.');linkCheck(from);linkCheck(to);}
    if(kind==='runs'){
      if(r.data.executedAt&&!timestamp(r.data.executedAt))throw new Error('Invalid run execution time.');
      if(r.revision!==1||r.status!=='recorded'||!Array.isArray(r.data.results)||!r.data.results.length||r.data.results.length>5000||!['self-reported','file-import','provider-retrieved'].includes(r.data.origin)||!text(r.data.build,2000))throw new Error('Invalid immutable run.');
      for(const result of r.data.results){if(!['pass','fail','blocked','not-run','inconclusive'].includes(result.result)||!text(result.title,2000)||!text(result.note)||!Array.isArray(result.requirementRefs))throw new Error('Invalid result.');if(result.caseId){linkCheck({kind:'cases',id:result.caseId,revision:result.caseRevision});if(ref(p,'cases',result.caseId,result.caseRevision).status!=='approved')throw new Error('Result case was not approved.');}else if(result.caseRevision!==0||result.requirementRefs.length)throw new Error('Unmapped result cannot claim coverage.');if(result.measurements!==undefined&&(!Array.isArray(result.measurements)||result.measurements.length>20||result.measurements.some(m=>!text(m.name,200)||!text(m.unit,100)||!Number.isFinite(m.value))))throw new Error('Invalid actual measurements.');result.requirementRefs.forEach(linkCheck);}
    }
    if(r.data.unknowns!==undefined&&(!Array.isArray(r.data.unknowns)||r.data.unknowns.length>100||r.data.unknowns.some(v=>!text(v,2000))))throw new Error('Invalid retained unknowns.');
    if(r.data.reviewDate&&!timestamp(r.data.reviewDate))throw new Error('Invalid guidance review expiry.');
    if(kind==='cases'&&new Set(r.refs.map(l=>l.kind+':'+l.id)).size!==r.refs.length)throw new Error('A case cannot pin conflicting revisions of the same context.');
    if(r.data.aiRunId&&!p.aiRuns.some(run=>run.id===r.data.aiRunId))throw new Error('AI draft provenance is unavailable.');
    if(kind==='exceptions'&&r.status==='accepted'&&(!r.ownerId||!r.note.trim()||!identifier(r.data.acceptedBy)||!member(r.data.acceptedBy)||!timestamp(r.data.expiresAt)))throw new Error('Accepted risk needs an accountable owner, reviewer, rationale and review expiry.');
    if(kind==='roles'&&(!Array.isArray(r.data.aliases)||r.data.aliases.some(v=>!text(v,100))||new Set(r.data.aliases).size!==r.data.aliases.length))throw new Error('Invalid historical role labels.');
    if(kind==='glossary'&&(!Array.isArray(r.data.aliases)||r.data.aliases.some(v=>!text(v,300))))throw new Error('Invalid glossary aliases.');
    if(kind==='assets'){const d=r.data;if(d.remote){if(!identifier(d.storageProjectId)||d.objectKey!==d.storageProjectId+'/'+d.hash||!/^[a-f0-9]{64}$/.test(d.hash)||!Number.isSafeInteger(d.byteLength)||d.byteLength<1||d.byteLength>6000000||!text(d.fileName,512)||!text(d.mediaType,150)||d.base64!==undefined)throw new Error('Invalid private original reference.');}else if(typeof d.base64!=='string'||d.base64.length>2800000||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(d.base64)||!Number.isSafeInteger(d.byteLength)||d.byteLength<0||d.byteLength>2000000||atob(d.base64).length!==d.byteLength||!/^[a-f0-9]{64}$/.test(d.hash)||!text(d.fileName,512)||!text(d.mediaType,150))throw new Error('Invalid retained original.');}
    if(kind==='proposals'){const d=r.data;if(!d.target||!d.base||d.base.id!==d.target.id||d.base.kind!==d.target.kind||!d.updates||typeof d.updates!=='object')throw new Error('Invalid delivery proposal.');linkCheck({kind:d.target.kind,id:d.target.id,revision:d.base.revision});if(!equal(snapshot(ref(p,d.target.kind,d.target.id,d.base.revision)),d.base))throw new Error('Proposal base does not match its immutable revision.');}
    if(kind==='scenarios'){const d=r.data;if(!d.subject||!d.base||d.base.id!==d.subject.id||!/^[a-f0-9]{64}$/.test(d.baseHash)||!d.updates)throw new Error('Invalid rehearsal.');linkCheck({kind:d.subject.kind,id:d.subject.id,revision:d.base.revision});if(!equal(snapshot(ref(p,d.subject.kind,d.subject.id,d.base.revision)),d.base))throw new Error('Rehearsal base was redefined.');}
    if(kind==='work'){for(const receipt of r.data.acknowledgments??[]){if(!identifier(receipt.id)||!identifier(receipt.memberId)||!member(receipt.memberId)||!timestamp(receipt.at)||!text(receipt.scopeHash,100000)||!Array.isArray(receipt.context))throw new Error('Invalid work receipt.');receipt.context.forEach(linkCheck);}}
    if(kind==='carryForwards'){const d=r.data;linkCheck({kind:'runs',id:d.runId});linkCheck({kind:'cases',id:d.caseId,revision:d.toCaseRevision});linkCheck({kind:'requirements',id:d.requirementId,revision:d.fromRevision});linkCheck({kind:'requirements',id:d.requirementId,revision:d.toRevision});if(!r.note.trim())throw new Error('Applicability review needs its rationale.');}
    if(kind==='external'&&r.data.externalOwnedFields&&(!Array.isArray(r.data.externalOwnedFields)||r.data.externalOwnedFields.some(v=>!['status','title','owner','description'].includes(v))))throw new Error('Unsupported externally owned field.');
  }
  if(list(p,'assets').filter(r=>!r.data.remote).reduce((n,r)=>n+r.data.byteLength,0)>6000000)throw new Error('Portable retained originals exceed 6 MB.');
  const hierarchy=list(p,'edges').filter(e=>!e.archived&&e.data.type==='child-of'),done=new Set(),visiting=new Set();
  function visit(key,depth=0){if(depth>1000||visiting.has(key))throw new Error('Invalid cyclic or excessive requirement hierarchy.');if(done.has(key))return;visiting.add(key);for(const e of hierarchy.filter(e=>e.data.from.kind+':'+e.data.from.id===key))visit(e.data.to.kind+':'+e.data.to.id,depth+1);visiting.delete(key);done.add(key);}hierarchy.forEach(e=>visit(e.data.from.kind+':'+e.data.from.id));
  if(!member(s.masterOwnerId)||!member(s.alternateOwnerId)||s.masterOwnerId&&s.masterOwnerId===s.alternateOwnerId)throw new Error('Choose distinct valid project custodians.');
  if(s.crossProjectLinks){if(!Array.isArray(s.crossProjectLinks)||s.crossProjectLinks.length>200)throw new Error('Too many cross-project dependencies.');for(const l of s.crossProjectLinks)if(!identifier(l.id)||!identifier(l.targetProjectId)||!identifier(l.recordId)||!FAMILIES.includes(l.kind)||!Number.isSafeInteger(l.revision)||!member(l.reviewedBy)||!identifier(l.reviewedBy)||!text(l.reason)||!l.reason.trim()||!timestamp(l.at))throw new Error('Invalid cross-project dependency.');else if(l.from)linkCheck(l.from);}
  if(s.lastViews){if(typeof s.lastViews!=='object'||Array.isArray(s.lastViews))throw new Error('Invalid reader cursors.');for(const [reader,cursor]of Object.entries(s.lastViews)){if(!member(reader)&&!names.includes(reader)||!cursor||Object.values(cursor).some(n=>!Number.isSafeInteger(n)||n<1))throw new Error('Invalid reader cursor.');}}
  for(const key of ['historyArchives','conflictReviews','workflowStudies','verificationGates'])if(s[key]!==undefined&&(!Array.isArray(s[key])||s[key].length>1000||JSON.stringify(s[key]).length>1000000))throw new Error('Bounded continuity / study records exceeded.');
  canonical(s);return copy(s);
}
