import * as L from './lifecycle.js';
import * as F from './sharing.js';
export function renderReturns(p,{esc,button}){const rows=L.list(p,'returns').filter(r=>!r.archived);return `<section class="panel"><h2>Master identity and expected returns</h2><p>Project ${esc(p.id)}<br>Round ${esc(p.sharing?.id??'not started')}<br>Base fingerprint ${esc(p.sharing?.hash??'unknown')}<br>Last known saved context ${esc(p.updatedAt??p.createdAt)}. This copy cannot detect a newer file elsewhere.</p>${button('Request named teammate returns','lineage-request','','secondary')}${rows.map(r=>`<p>${esc(p.members.find(m=>m.id===r.ownerId)?.name??'Unassigned')} · ${esc(r.status)} · ${esc(r.data.roundId)}${r.data.receivedHash?' · returned fingerprint '+esc(r.data.receivedHash):''} ${r.status==='pending'||r.status==='received'?button('Record withdrawal','lineage-withdraw',`data-id="${r.id}"`,'text-button'):''}</p>`).join('')||'<p>No expected returns recorded. Sharing a file does not establish receipt.</p>'}</section>`;}
export function createLineageActions(c){const {project,commit,modal,field,options,submit,esc,notify}=c;const reviewer=()=>`<label for="return-reviewer">Recorded by</label><select id="return-reviewer" name="memberId">${options(project().members.map(m=>[m.id,m.name]),c.person())}</select>`;return {
 'lineage-request':()=>{if(!project().sharing)throw new Error('Start a sharing round first.');modal('Request returns from named teammates',project().members.map(m=>`<label class="checkbox-label"><input type="checkbox" name="recipients" value="${m.id}"><span>${esc(m.name)} · ${esc(m.role)}</span></label>`).join('')+reviewer()+field('What should each teammate review and return?','note','','textarea')+'<p>This records the request manifest. Share the protected file and passphrase through your existing channel.</p>'+submit('Record expected returns'),async f=>{const ids=f.getAll('recipients');if(!ids.length)throw new Error('Choose at least one recipient.');await commit(p=>{for(const id of ids)if(!L.list(p,'returns').some(r=>r.ownerId===id&&r.data.roundId===p.sharing.id&&!['withdrawn','merged'].includes(r.status)))L.addRecord(p,'returns',{title:'Expected return: '+p.members.find(m=>m.id===id).name,status:'pending',ownerId:id,role:p.members.find(m=>m.id===id).role,scope:{state:'general'},data:{roundId:p.sharing.id,baseHash:p.sharing.hash,requestedAt:new Date().toISOString()},note:f.get('note')},f.get('memberId'));});notify('Expected returns recorded.');});},
 'lineage-withdraw':el=>modal('Retain withdrawal decision',reviewer()+field('Reason this return is no longer expected','note','','textarea')+submit('Record withdrawal'),async f=>{await commit(p=>L.editRecord(p,'returns',el.dataset.id,{status:'withdrawn'},f.get('memberId'),f.get('note')));}),
 'lineage-receive':()=>{const comparison=c.comparison();if(!comparison)throw new Error('Compare the returned file first.');const rows=L.list(project(),'returns').filter(r=>r.data.roundId===project().sharing?.id&&['pending','received'].includes(r.status));modal('Associate this reviewed returned copy',`<p>Fingerprint ${esc(comparison.incomingHash)}. The selected teammate identity is self-reported, not authenticated by the file.</p><label for="return-assignment">Expected return</label><select id="return-assignment" name="returnId">${options(rows.map(r=>[r.id,r.title]))}</select>`+reviewer()+field('Return receipt / origin note','note','','textarea')+submit('Record received return'),async f=>{if(L.list(project(),'returns').some(r=>r.data.receivedHash===comparison.incomingHash&&r.id!==f.get('returnId')))throw new Error('This returned fingerprint is already associated with another receipt.');await commit(p=>L.editRecord(p,'returns',f.get('returnId'),{status:'received',data:{receivedHash:comparison.incomingHash,receivedAt:new Date().toISOString()}},f.get('memberId'),f.get('note')));c.clearComparison();notify('Receipt retained. Compare the file again against the updated master before merging.');});},
 'lineage-hash':async()=>notify('Current working fingerprint: '+await F.projectHash(project()))
};}
