import * as D from './domain.js';
import {csvRows} from './structured-source.js';
import * as L from './lifecycle.js';
import * as P from './planning.js';
import {contextFor,lifecycleUI} from './lifecycle-ui.js';

export function createPlanningActions(c){
 const {project,commit,modal,field,options,submit,esc,download,notify,close}=c;
 const choose=(label,name,rows,value='')=>`<label for="planning-${name}">${esc(label)}</label><select id="planning-${name}" name="${name}">${options(rows,value)}</select>`;
 const member=()=>choose('Reviewed by','memberId',project().members.map(m=>[m.id,m.name]),c.person());
 return {
  'plan-table':()=>{const sources=project().sources.filter(s=>!s.archived&&s.origin?.access!=='lost');modal('Map a source decision table',choose('Source containing CSV','sourceId',sources.map(s=>[s.id,s.title]))+field('First data row to review (1-based after header)','start','1','number')+submit('Preview exact rows'),async f=>{const source=sources.find(s=>s.id===f.get('sourceId'));if(!source)throw new Error('Import a CSV source first.');const revision=source.revisions.at(-1),rows=csvRows(revision.content),header=rows[0]?.cells;if(!header||rows.length<2)throw new Error('A header and at least one data row are required.');const start=Math.max(1,Number(f.get('start'))),selected=rows.slice(start,start+50),columns=header.map((label,i)=>[String(i),label||'Column '+(i+1)]);modal('Review rows and map their meaning',`<p>Rows ${start}–${start+selected.length-1} of ${rows.length-1} data rows. At most 50 per batch; review later rows in another batch. Original row text remains the exact evidence.</p>`+choose('Title column','titleCol',columns)+choose('Condition / input column','conditionCol',[['','Unspecified'],...columns])+choose('Expected outcome column','outcomeCol',[['','Unspecified'],...columns])+member()+selected.map((r,i)=>`<section class="panel"><label class="checkbox-label"><input type="checkbox" name="rows" value="${i}"><span>Row ${start+i}: ${esc(r.cells.join(' | '))}</span></label></section>`).join('')+submit('Save explicitly selected requirement drafts'),async mapped=>{const chosen=mapped.getAll('rows').map(Number);if(!chosen.length)throw new Error('Select reviewed rows.');await commit(p=>{if(p.sources.find(s=>s.id===source.id)?.revisions.at(-1).id!==revision.id)throw new Error('Source changed. Review the table again.');for(const i of chosen){const row=selected[i],column=n=>mapped.get(n)===''?'':row.cells[Number(mapped.get(n))]??'',title=column('titleCol');if(!title.trim())throw new Error('Selected title cells must be nonempty.');L.addRecord(p,'requirements',{title,role:'Everyone',scope:{state:'unknown'},evidence:[D.makeRevisionEvidence(p,source.id,revision.id,revision.content.slice(row.start,row.end))],data:{type:'behavior',condition:column('conditionCol'),outcome:column('outcomeCol'),decisionRow:{sourceId:source.id,revisionId:revision.id,row:start+i+1,headers:header,cells:row.cells}},note:'Human-selected row mapping; scope and interpretation require approval'},mapped.get('memberId'));}});notify('Selected table rows saved as unapproved requirements.');});});},
  'plan-seed':()=>modal('Create editable functional and NFR templates','<p>Seven starter templates cover boundaries, performance, accessibility, authorization, retention, migration and operations. They remain drafts until a teammate reviews them.</p>'+member()+submit('Add missing starter drafts'),async f=>{await commit(p=>P.seedTemplates(p,f.get('memberId')));notify('Starter drafts added. Set measurable product-specific thresholds before approving cases.');}),
  'plan-template':el=>{const rows=L.list(project(),'requirements').filter(r=>r.status==='approved'&&!r.archived);modal('Apply a reviewed template',choose('Approved requirement','requirementId',rows.map(r=>[r.id,r.title]))+member()+submit('Create linked case draft'),async f=>{await commit(p=>P.applyTemplate(p,el.dataset.id,f.get('requirementId'),f.get('memberId')));notify('Linked case draft created.');});},
  'plan-regression':el=>{const subject={kind:el.dataset.kind,id:el.dataset.id},ctx=contextFor(lifecycleUI),plan=P.regressionCandidates(project(),subject,ctx);modal('Review regression selection',`<p>Suggestions use recorded dependency paths. Unrecorded dependencies remain unknown. Every inclusion/exclusion is retained with this plan.</p>${plan.candidates.map(x=>`<section class="panel"><label class="checkbox-label"><input type="checkbox" name="caseIds" value="${x.record.id}"><span>${esc(x.record.title)} · r${x.record.revision}</span></label><p>${esc(x.reason)} · scope ${x.applicability===true?'matches':x.applicability===false?'does not match':'unknown'}</p></section>`).join('')}${plan.unknowns.map(x=>`<p class="warning-banner">${esc(x)}</p>`).join('')}`+member()+field('Basis for the included and excluded cases','reason','','textarea')+submit('Save reviewed regression scope'),async f=>{await commit(p=>P.recordRegressionPlan(p,subject,f.getAll('caseIds'),f.get('memberId'),f.get('reason'),ctx));notify('Reviewed regression scope retained; no test results were created.');});},
  'plan-contract':el=>{const text=P.changeContract(project(),el.dataset.kind,el.dataset.id,location.href);modal('Review a portable change contract',`<pre>${esc(text)}</pre><p>This Markdown is unencrypted. The link identifies the record but does not grant project access. Imported files retain the complete history.</p>`+submit('Download reviewed Markdown'),async()=>{download('relay-change-contract.md',text,'text/markdown');close();});},
  'plan-cross-project':()=>{const candidates=c.openProjects().filter(p=>p.id!==project().id).flatMap(p=>['requirements','components','releases'].flatMap(kind=>L.list(p,kind).filter(r=>!r.archived).map(r=>({p,kind,r}))));modal('Review a dependency in another open project',choose('Dependent local record','from',['requirements','components'].flatMap(kind=>L.list(project(),kind).filter(r=>!r.archived).map(r=>[kind+':'+r.id,r.title])))+choose('Authorized open target record','target',candidates.map((x,i)=>[String(i),x.p.name+' · '+x.r.title+' · r'+x.r.revision]))+member()+field('Why does this dependency apply?','reason','','textarea')+'<p>The current file stores only the target IDs, pinned revision and your review. Target content is resolved only while that authorized project is open. An unavailable target remains unknown.</p>'+submit('Retain reviewed cross-project reference'),async f=>{const x=candidates[Number(f.get('target'))];if(!x)throw new Error('Open another authorized project file with a recorded target first.');await commit(p=>P.crossProjectLink(p,x.p,{kind:x.kind,id:x.r.id},f.get('memberId'),f.get('reason'),contextFor(lifecycleUI),(()=>{const [kind,id]=f.get('from').split(':');return L.reference(p,kind,id);})()));});},
  'plan-exception':el=>{const target=L.get(project(),el.dataset.kind,el.dataset.id);if(!target)throw new Error('Choose an unresolved record.');modal('Record a release exception with an owner',choose('Accountable owner','ownerId',project().members.map(m=>[m.id,m.name]))+member()+field('Accepted risk, mitigation and why release can proceed','reason','','textarea')+field('Review / expiry time','expiresAt','','datetime-local')+'<p>This decision preserves the original unresolved obligation. It cannot change a failed test into a pass or create deployment evidence.</p>'+submit('Record owned exception'),async f=>{await commit(p=>L.addRecord(p,'exceptions',{title:'Accepted risk: '+target.title,status:'accepted',ownerId:f.get('ownerId'),role:target.role,scope:target.scope,refs:[L.reference(p,target.kind,target.id)],note:f.get('reason'),data:{acceptedBy:f.get('memberId'),expiresAt:new Date(f.get('expiresAt')).toISOString(),mitigation:f.get('reason')}},f.get('memberId')));});}
 };
}
