import * as L from './lifecycle.js';
export const CHECK_TEMPLATES=[
 {title:'Condition and boundary table',type:'functional',steps:'List actor, precondition, boundary, input, exclusion and rollback condition for every row.',expected:'Specify the observable result for each reviewed row; unknown rows remain questions.'},
 {title:'Performance under declared load',type:'NFR',steps:'State workload, concurrency, dataset size, warm/cold state, duration, environment and measurement method.',expected:'Set latency percentile/unit, throughput unit and failure threshold before approval.'},
 {title:'Keyboard and assistive access',type:'NFR',steps:'Record supported flows/devices, keyboard path, focus order, accessible names and expected announcements.',expected:'State measurable outcomes for the selected flows and supported assistive tools.'},
 {title:'Authorization boundary',type:'NFR',steps:'Identify actors, resources, forbidden operations, expiry, session revocation and downloaded-copy boundaries.',expected:'Define allow/deny cases, evidence capture and observable failure behavior; do not infer security from a successful login.'},
 {title:'Retention and recovery',type:'NFR',steps:'Specify retained data, backups, owners, key continuity, restore target, restore dataset and drill procedure.',expected:'Define maximum data loss/time-to-restore with units; keep those targets unverified until measured.'},
 {title:'Migration and compatibility',type:'functional',steps:'List existing clients, schema versions, migrated cohorts, partial failure, replay and rollback paths.',expected:'Define compatibility outcomes and actual data-integrity checks for each selected cohort.'},
 {title:'Operations and rollback',type:'NFR',steps:'State prerequisites, flags, rollout audiences, monitoring links and rollback trigger thresholds.',expected:'Record an actual rehearsal/deployment observation; a written runbook is not rollback proof.'}
];
export function seedTemplates(p,memberId){for(const t of CHECK_TEMPLATES)if(!L.list(p,'templates').some(r=>r.title===t.title&&!r.archived))L.addRecord(p,'templates',{title:t.title,role:'QA',scope:{state:'unknown'},data:{...t,description:'Reusable starting point. Product-specific units, thresholds, conditions and exceptions require review.'}},memberId);}
export function applyTemplate(p,templateId,requirementId,memberId){const t=L.get(p,'templates',templateId),r=L.get(p,'requirements',requirementId);if(t?.status!=='approved'||r?.status!=='approved')throw new Error('Use a reviewed template and an approved requirement.');return L.addRecord(p,'cases',{title:r.title+' · '+t.title,role:'QA',scope:r.scope,refs:[L.reference(p,'requirements',r.id),L.reference(p,'templates',t.id)],data:{steps:t.data.steps,expected:t.data.expected,parameters:r.data.condition??'',measure:r.data.measure??'',acceptanceMeasures:r.data.acceptanceMeasures??[],templateId:t.id}},memberId);}
export function regressionCandidates(p,subject,context){const impact=L.impact(p,subject,context),ids=new Set([subject.kind+':'+subject.id,...impact.items.map(i=>i.ref.kind+':'+i.ref.id)]);return {candidates:L.list(p,'cases').filter(r=>!r.archived&&(ids.has('cases:'+r.id)||r.refs.some(l=>ids.has(l.kind+':'+l.id)))).map(r=>({record:r,reason:r.data.measure?'Recorded NFR measure / affected reference':'Recorded affected context reference',applicability:L.scopeMatch(r.scope,context)})),unknowns:impact.unknowns};}
export function recordRegressionPlan(p,subject,caseIds,memberId,reason,context){if(!reason?.trim()||!caseIds.length)throw new Error('Review included/excluded cases and record a basis.');const suggested=regressionCandidates(p,subject,context);const ids=new Set(suggested.candidates.map(c=>c.record.id));if(caseIds.some(id=>!ids.has(id)))throw new Error('Regression selection changed. Review again.');return L.addRecord(p,'packages',{title:'Reviewed regression scope: '+L.ref(p,subject.kind,subject.id).title,status:'accepted',ownerId:memberId,role:'QA',scope:L.ref(p,subject.kind,subject.id).scope,refs:[L.reference(p,subject.kind,subject.id),...caseIds.map(id=>L.reference(p,'cases',id))],data:{type:'regression-plan',selectedCaseIds:caseIds,excludedCaseIds:suggested.candidates.filter(c=>!caseIds.includes(c.record.id)).map(c=>c.record.id),reasons:suggested.candidates.map(c=>({caseId:c.record.id,reason:c.reason})),unknowns:suggested.unknowns,context}},memberId);}
export function changeContract(p,kind,id,baseUrl){
 const r=L.get(p,kind,id);if(!r)throw new Error('Choose a delivery record.');const before=r.history.at(-1)?.snapshot,link=new URL(baseUrl);link.hash=new URLSearchParams({project:p.id,record:kind+':'+id}).toString();
 const labels=(family,ids)=>ids.map(id=>L.get(p,family,id)?.title??'Unavailable '+family+' reference').join(', ');
 const scopeText=s=>[s.state==='unknown'?'Applicability is unknown':s.state==='general'?'General applicability':'Specific applicability',s.releaseIds.length&&'Release: '+labels('releases',s.releaseIds),s.environmentIds.length&&'Environment: '+labels('environments',s.environmentIds),s.audiences.length&&'Audience: '+s.audiences.join(', '),s.flags.length&&'Flags: '+s.flags.join(', '),s.exclusions&&'Exclusions: '+s.exclusions].filter(Boolean).join('\n');
 const description=x=>kind==='requirements'?L.requirementText(p,x):kind==='guidance'?L.guidanceText(p,x):[x.data.description,x.data.criteria,x.data.steps,x.data.expected,x.data.observation,x.data.compatibility,x.data.migration].filter(Boolean).join('\n\n')||x.note||'Content not recorded';
 const describe=x=>`${x.title} · r${x.revision} · ${x.status}\n${description(x)}\n\n${scopeText(x.scope)}\nOwner: ${p.members.find(m=>m.id===x.ownerId)?.name??'Unassigned'}`;
 const unknowns=[...(r.data.unknowns??[]),...(!L.hasDeclaredScope(r.scope)?['Applicability needs clarification.']:[]),...(L.staleRefs(p,r).length||L.sourceNeedsReview(p,r)?['Linked context or source evidence changed; applicability needs review.']:[]),'Unrecorded dependencies remain unknown.'];
 const evidence=r.evidence.map(e=>{const source=p.sources.find(s=>s.id===e.sourceId),number=source?.revisions.findIndex(v=>v.id===e.revisionId);return `${source?.title??'Unavailable source'} · revision ${number>=0?number+1:'unknown'} (${e.revisionId})\n${e.quote}`;}).join('\n\n');
 return `# ${r.title}\n\nProduct Relay change contract · r${r.revision}\n\n## Before\n\n${before?describe(before):'New record; no earlier recorded agreement.'}\n\n## After\n\n${describe(r)}\n\n## Why\n\n${r.note||'Not recorded'}\n\n## Unknown or unresolved\n\n${unknowns.map(u=>'- '+u).join('\n')}\n\n## Original evidence\n\n${evidence||'Owner-reviewed basis only; no source quotation.'}\n\nOpen the authorized project file, then [view this record](${link.href}). The contract describes r${r.revision}; if the open record has advanced, inspect its preserved history.\n\nApproval, implementation, testing and deployment are separate facts.\n`;
}
export function crossProjectLink(p,targetProject,targetRecord,memberId,reason,context,from){if(!targetProject||targetProject.id===p.id||!L.get(targetProject,targetRecord.kind,targetRecord.id)||!reason?.trim())throw new Error('Choose a record in another authorized open project and review its dependency.');L.ensure(p).crossProjectLinks??=[];const link={id:crypto.randomUUID(),targetProjectId:targetProject.id,kind:targetRecord.kind,recordId:targetRecord.id,revision:L.get(targetProject,targetRecord.kind,targetRecord.id).revision,reviewedBy:memberId,reason,context,...(from?{from}:{}),at:new Date().toISOString()};p.delivery.crossProjectLinks.push(link);return link;}
