import * as D from './domain.js';
import * as L from './lifecycle.js';
import {equal,digest} from './value.js';

const text=r=>[r.title,r.body,r.condition,r.outcome,r.data?.description,r.data?.condition,r.data?.outcome].filter(Boolean).join(' ');
const words=s=>new Set(String(s).toLowerCase().match(/[\p{L}\p{N}]+/gu)?.filter(w=>w.length>3&&!['must','should','when','with','that','this','will','only','does','shall'].includes(w))??[]);
const overlaps=(a,b)=>{const x=words(a),y=words(b);return [...x].filter(w=>y.has(w)).length/Math.max(1,Math.min(x.size,y.size));};
function scopesOverlap(a,b){for(const key of ['releaseIds','environmentIds','audiences','flags'])if(a?.[key]?.length&&b?.[key]?.length&&!a[key].some(v=>b[key].includes(v)))return false;return true;}
function interval(m){return m.operator==='lte'?[-Infinity,m.target]:m.operator==='gte'?[m.target,Infinity]:[m.target,m.target];}
/** Suggestions, never authority: fuzzy wording can over/under-match. Exact revisions bind review. */
export async function detectConflicts(p,{maxPairs=25000}={}){
 const rows=[...L.list(p,'requirements'),...(p.behaviors??[]).map(r=>({...r,kind:'behaviors'}))].filter(r=>!r.archived),candidates=[];let examined=0;
 const groups=new Map();for(const r of rows){const keys=r.data?.conflictKey?[r.data.conflictKey]:[...words(r.title)].slice(0,8);for(const k of keys){if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);}}
 const seen=new Set();outer:for(const group of groups.values())for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++){
  const a=group[i],b=group[j],pair=[a.id,b.id].sort().join(':');if(seen.has(pair))continue;seen.add(pair);if(++examined>maxPairs)break outer;
  if(!scopesOverlap(a.scope,b.scope)||overlaps(a.title,b.title)<0.5&&!a.data?.conflictKey)continue;
  const reasons=[];for(const x of a.data?.acceptanceMeasures??[])for(const y of b.data?.acceptanceMeasures??[])if(x.name.toLowerCase()===y.name.toLowerCase()&&x.unit===y.unit){const [l,h]=interval(x),[k,n]=interval(y);if(Math.max(l,k)>Math.min(h,n))reasons.push(`Incompatible ${x.name} thresholds: ${x.operator} ${x.target} versus ${y.operator} ${y.target} ${x.unit}.`);}
  const x=text(a),y=text(b),patterns=[[/\b(immediately|instantly)\b/i,/\b(end of|after|until).{0,50}(period|billing|subscription|expiry)\b/i,'Immediate versus deferred timing'],[/\b(must not|shall not|never|forbidden|cannot|not allowed)\b/i,/\b(must|shall|required|always|allowed)\b/i,'Potentially opposed obligation']];
  for(const [left,right,label]of patterns)if(overlaps(x,y)>=0.45&&(left.test(x)&&right.test(y)&&!left.test(y)||left.test(y)&&right.test(x)&&!left.test(x)))reasons.push(label+'; compare the exact conditions and exceptions.');
  if(reasons.length){const refs=[a,b].map(r=>({kind:r.kind,id:r.id,revision:r.revision})),key=await digest({refs,reasons});candidates.push({key,refs,title:a.title+' / '+b.title,reasons,scopeUnknown:[a,b].some(r=>r.scope?.state!=='general'),review:(p.delivery?.conflictReviews??[]).find(r=>r.key===key)});}
 }
 return {candidates,examined,bounded:examined>maxPairs,unknowns:['Text comparison suggests possible contradictions; it cannot prove semantic equivalence or discover unrecorded requirements.']};
}
export function reviewConflict(p,candidate,memberId,decision,note){if(!p.members.some(m=>m.id===memberId)||!['conflict','compatible','needs-context'].includes(decision)||!note?.trim())throw new Error('Choose a reviewer, conclusion and basis.');if(candidate.refs.some(r=>L.ref(p,r.kind,r.id)?.revision!==r.revision))throw new Error('Requirements changed. Scan again.');const s=L.ensure(p);s.conflictReviews??=[];s.conflictReviews.push({id:D.uid(),key:candidate.key,refs:candidate.refs,memberId,decision,note,at:new Date().toISOString()});if(decision!=='compatible')D.addQuestion(p,'Resolve conflicting context: '+candidate.title,'Product',p.members.find(m=>m.id===memberId).name);}

export async function simulateChange(p,subject,updates,context={}){
 const original=L.ref(p,subject.kind,subject.id);if(!original)throw new Error('Original record unavailable.');const sandbox=D.clone(p),candidate=L.ref(sandbox,subject.kind,subject.id);Object.assign(candidate,{...updates,...(updates.data?{data:{...candidate.data,...updates.data}}:{})});candidate.history??=[];candidate.history.push({revision:candidate.revision,snapshot:L.snapshot(original)});candidate.revision++;candidate.status='draft';
 const affected=L.impact(p,subject,context),artifacts=affected.items.filter(x=>x.record).map(x=>{const r=x.record,body=r.kind==='cases'?r.data.expected:L.guidanceText(p,r);return {ref:x.ref,title:r.title,path:x.path.map(e=>e.data.type),before:body??r.data.description??r.note,proposed:r.kind==='cases'?{steps:r.data.steps,expected:updates.data?.outcome??updates.outcome??updates.data?.description??r.data.expected}:{description:updates.data?.description??updates.outcome??r.data.description??r.note},status:'draft for review',reason:'Recorded dependency changes; wording is a mechanical candidate and must be reviewed.'};});
 return {baseHash:await digest(L.snapshot(original)),affected:artifacts,obligationsBefore:L.obligations(p,context).map(x=>({title:x.record.title,reason:x.reason})),obligationsAfter:L.obligations(sandbox,context).map(x=>({title:x.record.title,reason:x.reason})),conflicts:(await detectConflicts(sandbox)).candidates,unknowns:affected.unknowns};
}
export function createRehearsalDrafts(p,id,selected,memberId,note){const scenario=L.get(p,'scenarios',id);if(!scenario?.data.simulation||!note?.trim())throw new Error('A simulated scenario and review basis are required.');if(!equal(L.snapshot(L.ref(p,scenario.data.subject.kind,scenario.data.subject.id)),scenario.data.base))throw new Error('Scenario base changed. Rehearse again.');if(!selected.length)throw new Error('Select downstream records to propose.');return scenario.data.simulation.affected.filter(a=>selected.includes(a.ref.id)).map(a=>{const r=L.ref(p,a.ref.kind,a.ref.id);if(!r||r.revision!==a.ref.revision)throw new Error('Downstream record changed. Rehearse again.');return L.proposeRecord(p,a.ref.kind,a.ref.id,{data:a.ref.kind==='cases'?a.proposed:a.ref.kind==='guidance'?{body:a.proposed.description}:a.ref.kind==='work'?{criteria:a.proposed.description}:{description:a.proposed.description}},memberId,note);});}

const RETURN_FAMILIES=['requirements','objectives','cases','guidance','components','work','defects','incidents','templates'];
export function returnCandidates(master,returned,base){if((returned.reviewOf??returned.id)!==master.id||returned.createdAt!==master.createdAt)throw new Error('The returned copy belongs to a different project.');const result=[];
 for(const kind of [...RETURN_FAMILIES,'behaviors','sections','sources','questions'])for(const r of kind==='sources'||kind==='sections'||kind==='behaviors'||kind==='questions'?returned[kind]??[]:L.list(returned,kind)){
  const before=base&&(RETURN_FAMILIES.includes(kind)?L.get(base,kind,r.id):base[kind]?.find(x=>x.id===r.id)),current=RETURN_FAMILIES.includes(kind)?L.get(master,kind,r.id):master[kind]?.find(x=>x.id===r.id);if(equal(r,before)||equal(r,current))continue;
  result.push({kind,id:r.id,title:r.title,returned:r,current,base:before??null,conflict:!!current&&!equal(current,before)});
 }return result;
}
export function convertReturn(p,rows,selected,memberId,note){if(!p.members.some(m=>m.id===memberId)||!note?.trim())throw new Error('Choose a reviewer and record why these edits should be proposed.');const created=[];
 for(const row of rows.filter(r=>selected.includes(r.kind+':'+r.id))){const {kind,returned:r}=row;
  if(kind==='sources'){const last=r.revisions.at(-1);if(!last)continue;const source=p.sources.find(s=>s.id===r.id);if(source)D.reviseSource(p,r.id,last.content,last.document);else D.addSource(p,r.title,last.content,r.kind,last.document);created.push({kind,id:source?.id});continue;}
  if(kind==='questions'){created.push(D.addQuestion(p,r.title,r.role,r.owner));continue;}
  if(kind==='behaviors'){const current=p.behaviors.find(b=>b.id===r.id);if(!current)created.push(D.addBehavior(p,{...r,status:'draft',evidence:[],owner:p.members.find(m=>m.id===memberId).name}));else if(current.status==='approved')created.push(D.proposeBehaviorChange(p,r.id,{...r,evidence:current.evidence},note));else {D.editBehavior(p,r.id,{...r,evidence:current.evidence});created.push(current);}continue;}
  if(kind==='sections'){const current=p.sections.find(s=>s.id===r.id);if(!current)created.push(D.addSection(p,{title:r.title,body:r.body,role:r.role}));else if(current.status==='approved')created.push(D.proposeChange(p,r.id,r.body,note,'','',{title:r.title,role:r.role}));else {D.editDraft(p,r.id,{title:r.title,body:r.body,role:r.role});created.push(current);}continue;}
  const current=L.get(p,kind,r.id),data=D.clone(r.data);for(const key of ['aiRunId','acknowledgments','externalOwnedFields','approval','lastJobId','origin'])delete data[key];data.returnProvenance={recordId:r.id,revision:r.revision,note};
  const updates={title:r.title,note:r.note,role:L.roleNames(p).includes(r.role)?r.role:'Everyone',data};if(current)created.push(L.proposeRecord(p,kind,current.id,updates,memberId,note));else created.push(L.addRecord(p,kind,{...updates,status:'draft',scope:{state:'unknown'},ownerId:memberId,refs:[],evidence:[]},memberId));
 }if(!created.length)throw new Error('Select at least one changed record.');return created;
}

export async function prepareArchive(p,ids,memberId,note){if(!p.members.some(m=>m.id===memberId)||!note?.trim())throw new Error('Choose the archive custodian and a reason.');const archives=(p.mergeArchives??[]).filter(a=>ids.includes(a.id));if(!archives.length)throw new Error('Select merge parents to offload.');const body={format:'product-relay-history',version:1,projectId:p.id,createdAt:p.createdAt,archivedAt:new Date().toISOString(),reviewedBy:memberId,note,archives};return {...body,hash:await digest(body)};}
export async function offloadArchive(p,bundle){const {hash,...body}=bundle;if(await digest(body)!==hash||p.id!==bundle.projectId||p.createdAt!==bundle.createdAt)throw new Error('Archive checksum or project identity differs.');const manifest=(L.ensure(p).historyArchives??=[]);if(manifest.some(a=>a.hash===hash))throw new Error('Archive already recorded.');for(const a of bundle.archives)if(!equal(a,p.mergeArchives.find(x=>x.id===a.id)))throw new Error('Merge history changed; export again.');manifest.push({id:D.uid(),hash,archiveIds:bundle.archives.map(a=>a.id),at:bundle.archivedAt,memberId:bundle.reviewedBy,note:bundle.note});p.mergeArchives=p.mergeArchives.filter(a=>!bundle.archives.some(b=>b.id===a.id));}
export async function inspectArchive(p,bundle){const {hash,...body}=bundle;if(bundle.format!=='product-relay-history'||bundle.version!==1||await digest(body)!==hash||bundle.projectId!==p.id||bundle.createdAt!==p.createdAt||!p.delivery?.historyArchives?.some(a=>a.hash===hash))throw new Error('This archive does not match a recorded project manifest.');for(const a of bundle.archives){D.importProject(D.exportProject(a.current));D.importProject(D.exportProject(a.incoming));}return bundle.archives;}

export const PERFORMANCE_BUDGETS=Object.freeze({recordsPerFamily:5000,queryMs:1000,saveMs:5000,reopenMs:5000,mergeMs:10000});
export function recordTiming(p,operation,elapsed){const s=L.ensure(p);s.performance??=[];s.performance.push({operation,elapsedMs:Math.round(elapsed),at:new Date().toISOString()});s.performance=s.performance.slice(-50);}
