import * as D from './domain.js';
import * as L from './lifecycle.js';
import {equal,digest} from './value.js';

const text=r=>[r.title,r.body,r.condition,r.outcome,r.data?.description,r.data?.condition,r.data?.outcome].filter(Boolean).join(' ');
const words=s=>new Set(String(s).toLowerCase().match(/[\p{L}\p{N}]+/gu)?.filter(w=>w.length>3&&!['must','should','when','with','that','this','will','only','does','shall'].includes(w))??[]);
const overlaps=(a,b)=>{const x=words(a),y=words(b);return [...x].filter(w=>y.has(w)).length/Math.max(1,Math.min(x.size,y.size));};
function scopesOverlap(a,b){for(const key of ['releaseIds','environmentIds','audiences','flags'])if(a?.[key]?.length&&b?.[key]?.length&&!a[key].some(v=>b[key].includes(v)))return false;return true;}
function interval(m){return m.operator==='lte'?[-Infinity,m.target]:m.operator==='gte'?[m.target,Infinity]:[m.target,m.target];}
/** Suggestions, never authority: fuzzy wording can over/under-match. Exact revisions bind review. */
export async function detectConflicts(p,{maxPairs=25000}={}){
 const rows=[...L.list(p,'requirements'),...(p.behaviors??[]).map(r=>({...r,kind:'behaviors'}))].filter(r=>!r.archived),candidates=[];let examined=0;
 const groups=new Map();for(const r of rows){const keys=r.data?.conflictKey?[r.data.conflictKey]:[...words(r.title)].slice(0,8);for(const k of keys){if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);}}
 const seen=new Set();outer:for(const group of groups.values())for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++){
  const a=group[i],b=group[j],pair=[a.id,b.id].sort().join(':');if(seen.has(pair))continue;seen.add(pair);if(++examined>maxPairs)break outer;
  if(!scopesOverlap(a.scope,b.scope)||overlaps(a.title,b.title)<0.5&&!a.data?.conflictKey)continue;
  const reasons=[];for(const x of a.data?.acceptanceMeasures??[])for(const y of b.data?.acceptanceMeasures??[])if(x.name.toLowerCase()===y.name.toLowerCase()&&x.unit===y.unit){const [l,h]=interval(x),[k,n]=interval(y);if(Math.max(l,k)>Math.min(h,n))reasons.push(`Incompatible ${x.name} thresholds: ${x.operator} ${x.target} versus ${y.operator} ${y.target} ${x.unit}.`);}
  const x=text(a),y=text(b),patterns=[[/\b(immediately|instantly)\b/i,/\b(end of|after|until).{0,50}(period|billing|subscription|expiry)\b/i,'Immediate versus deferred timing'],[/\b(must not|shall not|never|forbidden|cannot|not allowed)\b/i,/\b(must|shall|required|always|allowed)\b/i,'Potentially opposed obligation']];
  for(const [left,right,label]of patterns)if(overlaps(x,y)>=0.45&&(left.test(x)&&right.test(y)&&!left.test(y)||left.test(y)&&right.test(x)&&!left.test(x)))reasons.push(label+'; compare the exact conditions and exceptions.');
  if(reasons.length){const refs=[a,b].map(r=>({kind:r.kind,id:r.id,revision:r.revision})),key=await digest({refs,reasons});candidates.push({key,refs,title:a.title+' / '+b.title,reasons,scopeUnknown:[a,b].some(r=>r.scope?.state!=='general'),review:(p.delivery?.conflictReviews??[]).find(r=>r.key===key)});}
 }
 return {candidates,examined,bounded:examined>maxPairs,unknowns:['Text comparison suggests possible contradictions; it cannot prove semantic equivalence or discover unrecorded requirements.']};
}
export function reviewConflict(p,candidate,memberId,decision,note){if(!p.members.some(m=>m.id===memberId)||!['conflict','compatible','needs-context'].includes(decision)||!note?.trim())throw new Error('Choose a reviewer, conclusion and basis.');if(candidate.refs.some(r=>L.ref(p,r.kind,r.id)?.revision!==r.revision))throw new Error('Requirements changed. Scan again.');const s=L.ensure(p);s.conflictReviews??=[];s.conflictReviews.push({id:D.uid(),key:candidate.key,refs:candidate.refs,snapshots:candidate.refs.map(r=>L.snapshot(L.ref(p,r.kind,r.id,r.revision))),memberId,decision,note,at:new Date().toISOString()});if(decision!=='compatible')D.addQuestion(p,'Resolve conflicting context: '+candidate.title,'Product',p.members.find(m=>m.id===memberId).name);}

export async function simulateChange(p,subject,updates,context={}){
 const original=L.ref(p,subject.kind,subject.id);if(!original)throw new Error('Original record unavailable.');const sandbox=D.clone(p),candidate=L.ref(sandbox,subject.kind,subject.id);Object.assign(candidate,{...updates,...(updates.data?{data:{...candidate.data,...updates.data}}:{})});candidate.history??=[];candidate.history.push({revision:candidate.revision,snapshot:L.snapshot(original)});candidate.revision++;candidate.status='draft';
 const affected=L.impact(p,subject,context),artifacts=affected.items.filter(x=>x.record).map(x=>{const r=x.record,body=r.kind==='cases'?r.data.expected:L.guidanceText(p,r);return {ref:x.ref,title:r.title,path:x.path.map(e=>e.data.type),canPropose:REHEARSAL_FAMILIES.includes(r.kind),before:body??r.data.description??r.note,proposed:r.kind==='cases'?{steps:r.data.steps,expected:updates.data?.outcome??updates.outcome??updates.data?.description??r.data.expected}:{description:updates.data?.description??updates.outcome??r.data.description??r.note},status:'draft for review',reason:'Recorded dependency changes; wording is a mechanical candidate and must be reviewed.'};});
 return {baseHash:await digest(L.snapshot(original)),affected:artifacts,obligationsBefore:L.obligations(p,context).map(x=>({title:x.record.title,reason:x.reason})),obligationsAfter:L.obligations(sandbox,context).map(x=>({title:x.record.title,reason:x.reason})),conflicts:(await detectConflicts(sandbox)).candidates,unknowns:affected.unknowns};
}
export const REHEARSAL_FAMILIES=['cases','guidance','work','requirements','components','objectives','templates','defects','incidents'];
export function createRehearsalDrafts(p,id,selected,memberId,note){const scenario=L.get(p,'scenarios',id);if(!scenario?.data.simulation||!note?.trim())throw new Error('A simulated scenario and review basis are required.');if(!equal(L.snapshot(L.ref(p,scenario.data.subject.kind,scenario.data.subject.id)),scenario.data.base))throw new Error('Scenario base changed. Rehearse again.');if(!selected.length)throw new Error('Select downstream records to propose.');if(selected.some(id=>!scenario.data.simulation.affected.some(a=>a.ref.id===id&&REHEARSAL_FAMILIES.includes(a.ref.kind))))throw new Error('Select editable downstream content. Executions and other observations remain review obligations.');return scenario.data.simulation.affected.filter(a=>selected.includes(a.ref.id)).map(a=>{const r=L.ref(p,a.ref.kind,a.ref.id);if(!r||r.revision!==a.ref.revision)throw new Error('Downstream record changed. Rehearse again.');return L.proposeRecord(p,a.ref.kind,a.ref.id,{data:a.ref.kind==='cases'?a.proposed:a.ref.kind==='guidance'?{body:a.proposed.description}:a.ref.kind==='work'?{criteria:a.proposed.description}:{description:a.proposed.description}},memberId,note);});}

const RETURN_FAMILIES=['requirements','objectives','cases','guidance','components','work','defects','incidents','templates','glossary','releases','environments','exceptions'];
const CONTENT_KEYS=['title','note','role','ownerId','scope','refs','evidence'];
function returnData(record){const data=D.clone(record?.data??{});for(const key of ['aiRunId','acknowledgments','externalOwnedFields','approval','lastJobId','origin','returnProvenance','acceptedBy','authenticatedBy','actorUserId','commandId'])delete data[key];return data;}
function returnedContent(kind,r){if(!r)return null;if(RETURN_FAMILIES.includes(kind))return {...Object.fromEntries(CONTENT_KEYS.map(k=>[k,r[k]])),data:returnData(r)};if(kind==='behaviors')return Object.fromEntries(['title','actor','condition','outcome','applicability','owner','audiences'].map(k=>[k,r[k]]));if(kind==='sections')return {title:r.title,body:r.body,role:r.role};if(kind==='sources')return {title:r.title,kind:r.kind,content:r.revisions.at(-1)?.content,document:r.revisions.at(-1)?.document};return {title:r.title,role:r.role,owner:r.owner,resolution:r.resolution};}
function returnContext(p,r){const unresolvedRefs=[],refs=(r.refs??[]).filter(l=>{if(L.ref(p,l.kind,l.id,l.revision))return true;unresolvedRefs.push(l);return false;}),unresolvedEvidence=[],evidence=(r.evidence??[]).filter(e=>{const source=p.sources.find(s=>s.id===e.sourceId),revision=source?.revisions.find(v=>v.id===e.revisionId);if(revision?.content.includes(e.quote))return true;unresolvedEvidence.push(e);return false;}),originalScope=L.scope(r.scope),missingScope=[...originalScope.releaseIds.filter(id=>!L.get(p,'releases',id)),...originalScope.environmentIds.filter(id=>!L.get(p,'environments',id))];
 return {refs,evidence,scope:missingScope.length?L.scope({...originalScope,state:'unknown',releaseIds:[],environmentIds:[]}):originalScope,unresolvedRefs,unresolvedEvidence,...(missingScope.length?{unresolvedScope:originalScope}:{}),...(r.ownerId&&!p.members.some(m=>m.id===r.ownerId)?{unresolvedOwnerId:r.ownerId}:{}),...(!L.roleNames(p).includes(r.role)?{unresolvedRole:r.role}:{})};}
export function returnCandidates(master,returned,base){if((returned.reviewOf??returned.id)!==master.id||returned.createdAt!==master.createdAt)throw new Error('The returned copy belongs to a different project.');const result=[];
 for(const kind of [...RETURN_FAMILIES,'behaviors','sections','sources','questions'])for(const r of kind==='sources'||kind==='sections'||kind==='behaviors'||kind==='questions'?returned[kind]??[]:L.list(returned,kind)){
  const before=base&&(RETURN_FAMILIES.includes(kind)?L.get(base,kind,r.id):base[kind]?.find(x=>x.id===r.id)),current=RETURN_FAMILIES.includes(kind)?L.get(master,kind,r.id):master[kind]?.find(x=>x.id===r.id);if(equal(returnedContent(kind,r),returnedContent(kind,before))||equal(returnedContent(kind,r),returnedContent(kind,current)))continue;
  result.push({kind,id:r.id,title:r.title,returned:r,current,base:before??null,conflict:!!current&&!equal(returnedContent(kind,current),returnedContent(kind,before))});
 }return result;
}
export function convertReturn(p,rows,selected,memberId,note){if(!p.members.some(m=>m.id===memberId)||!note?.trim())throw new Error('Choose a reviewer and record why these edits should be proposed.');const created=[];
 for(const row of rows.filter(r=>selected.includes(r.kind+':'+r.id))){const {kind,returned:r}=row;
  if(kind==='sources'){const last=r.revisions.at(-1);if(!last)continue;let source=p.sources.find(s=>s.id===r.id);if(source?.origin&&last.content!==source.revisions.at(-1).content)source=D.correctRetrievedSource(p,source.id,last.content,memberId,note);else if(source&&(source.origin||source.archived||source.title!==r.title||source.kind!==r.kind))source=D.addSource(p,'Returned context · '+r.title,'Returned source '+r.id+' / revision '+last.id+'\nReview basis: '+note+'\nReturned type: '+r.kind+'\n\n'+last.content,r.kind);else if(source)D.reviseSource(p,r.id,last.content,last.document);else source=D.addSource(p,r.title,last.content,r.kind,last.document);created.push({kind,id:source.id});continue;}
  if(kind==='questions'){created.push(D.addQuestion(p,r.title+(r.resolution?' · Returned suggested answer (needs review): '+r.resolution:''),L.roleNames(p).includes(r.role)?r.role:'Everyone',r.owner));continue;}
  if(kind==='behaviors'){if(r.audiences.some(role=>!L.roleNames(p).includes(role)))throw new Error('Add the returned rule perspectives to this master before importing '+r.title+'.');const current=p.behaviors.find(b=>b.id===r.id),input={...returnedContent(kind,r),audiences:r.audiences.filter(role=>L.roleNames(p).includes(role)),evidence:current?.evidence??[]};if(!input.audiences.length)input.audiences=['Everyone'];if(!current||current.archived)created.push(D.addBehavior(p,{...input,owner:p.members.find(m=>m.id===memberId).name}));else if(current.status==='approved')created.push(D.proposeBehaviorChange(p,r.id,input,note));else {D.editBehavior(p,r.id,input);created.push(current);}continue;}
  if(kind==='sections'){if(!L.roleNames(p).includes(r.role))throw new Error('Add the returned section perspective to this master before importing '+r.title+'.');const current=p.sections.find(s=>s.id===r.id);if(!current||current.archived)created.push(D.addSection(p,{title:r.title,body:r.body,role:r.role}));else if(current.status==='approved')created.push(D.proposeChange(p,r.id,r.body,note,'','',{title:r.title,role:r.role}));else {D.editDraft(p,r.id,{title:r.title,body:r.body,role:r.role});created.push(current);}continue;}
  const current=L.get(p,kind,r.id),data=returnData(r),context=returnContext(p,r),{refs,evidence,scope,...unresolved}=context;data.returnProvenance={recordId:r.id,revision:r.revision,note,...unresolved};
  const updates={title:r.title,note:r.note,role:L.roleNames(p).includes(r.role)?r.role:'Everyone',ownerId:p.members.some(m=>m.id===r.ownerId)?r.ownerId:current?.ownerId??memberId,scope,refs,evidence,data};if(current)created.push(L.proposeRecord(p,kind,current.id,updates,memberId,note));else created.push(L.addRecord(p,kind,{...updates,status:'draft'},memberId));
 }if(!created.length)throw new Error('Select at least one changed record.');return created;
}

export async function prepareArchive(p,ids,memberId,note){if(!p.members.some(m=>m.id===memberId)||!note?.trim())throw new Error('Choose the archive custodian and a reason.');const archives=(p.mergeArchives??[]).filter(a=>ids.includes(a.id));if(!archives.length)throw new Error('Select merge parents to offload.');const body={format:'product-relay-history',version:1,projectId:p.id,createdAt:p.createdAt,archivedAt:new Date().toISOString(),reviewedBy:memberId,note,archives};return {...body,hash:await digest(body)};}
export async function offloadArchive(p,bundle){const {hash,...body}=bundle;if(await digest(body)!==hash||p.id!==bundle.projectId||p.createdAt!==bundle.createdAt)throw new Error('Archive checksum or project identity differs.');const manifest=(L.ensure(p).historyArchives??=[]);if(manifest.some(a=>a.hash===hash))throw new Error('Archive already recorded.');for(const a of bundle.archives)if(!equal(a,p.mergeArchives.find(x=>x.id===a.id)))throw new Error('Merge history changed; export again.');manifest.push({id:D.uid(),hash,archiveIds:bundle.archives.map(a=>a.id),at:bundle.archivedAt,memberId:bundle.reviewedBy,note:bundle.note});p.mergeArchives=p.mergeArchives.filter(a=>!bundle.archives.some(b=>b.id===a.id));}
export async function inspectArchive(p,bundle){
 const {hash,...body}=bundle,manifest=p.delivery?.historyArchives?.find(a=>a.hash===hash);
 if(bundle.format!=='product-relay-history'||bundle.version!==1||await digest(body)!==hash||bundle.projectId!==p.id||bundle.createdAt!==p.createdAt||!manifest||!Array.isArray(bundle.archives)||bundle.archives.length>10||!equal(manifest.archiveIds,bundle.archives.map(a=>a.id))||manifest.at!==bundle.archivedAt||manifest.memberId!==bundle.reviewedBy||manifest.note!==bundle.note)throw new Error('This archive does not match its recorded project manifest.');
 const checked=D.importProject(D.exportProject({...p,mergeArchives:bundle.archives}));return checked.mergeArchives;
}

export const PERFORMANCE_BUDGETS=Object.freeze({recordsPerFamily:5000,queryMs:1000,saveMs:5000,reopenMs:5000,mergeMs:10000});
export function recordTiming(p,operation,elapsed){const s=L.ensure(p);s.performance??=[];s.performance.push({operation,elapsedMs:Math.round(elapsed),at:new Date().toISOString()});s.performance=s.performance.slice(-50);}
