create table public.relay_oauth_states(id uuid primary key,project_id uuid not null references public.relay_projects(id),user_id uuid not null references auth.users(id),provider text not null,secret jsonb not null,return_url text not null,expires_at timestamptz not null,used boolean not null default false);
create table public.relay_connector_accounts(project_id uuid not null references public.relay_projects(id),user_id uuid not null references auth.users(id),provider text not null,account_label text not null,secret jsonb not null,active boolean not null default true,revision bigint not null default 1,refresh_lease uuid,refresh_until timestamptz,updated_at timestamptz not null default now(),primary key(project_id,user_id,provider));
alter table public.relay_oauth_states enable row level security;alter table public.relay_connector_accounts enable row level security;
revoke all on public.relay_oauth_states,public.relay_connector_accounts from public,anon,authenticated;grant all on public.relay_oauth_states,public.relay_connector_accounts to service_role;
create function public.relay_claim_oauth_state(p_id uuid) returns setof public.relay_oauth_states language sql security definer set search_path='' as $$ update public.relay_oauth_states set used=true where id=p_id and not used and expires_at>now() returning * $$;
create function public.relay_claim_token_refresh(p_project uuid,p_user uuid,p_provider text,p_revision bigint,p_lease uuid) returns boolean language plpgsql security definer set search_path='' as $$ begin update public.relay_connector_accounts set refresh_lease=p_lease,refresh_until=now()+interval '60 seconds' where project_id=p_project and user_id=p_user and provider=p_provider and active and revision=p_revision and (refresh_until is null);return found;end $$;
create function public.relay_store_token_refresh(p_project uuid,p_user uuid,p_provider text,p_lease uuid,p_secret jsonb) returns boolean language plpgsql security definer set search_path='' as $$ begin update public.relay_connector_accounts set secret=p_secret,revision=revision+1,refresh_lease=null,refresh_until=null,updated_at=now() where project_id=p_project and user_id=p_user and provider=p_provider and active and refresh_lease=p_lease and refresh_until>now();return found;end $$;
revoke all on function public.relay_claim_oauth_state(uuid),public.relay_claim_token_refresh(uuid,uuid,text,bigint,uuid),public.relay_store_token_refresh(uuid,uuid,text,uuid,jsonb) from public,anon,authenticated;
grant execute on function public.relay_claim_oauth_state(uuid),public.relay_claim_token_refresh(uuid,uuid,text,bigint,uuid),public.relay_store_token_refresh(uuid,uuid,text,uuid,jsonb) to service_role;
